// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-web-firecrawl", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CREDENTIAL_REF = "FIRECRAWL_API_KEY";

//#endregion
//#region client/validation.ts
function messageOf(error) {
	return error instanceof Error ? error.message : String(error);
}
function sourceLabel(source) {
	return {
		env: "launch environment",
		file: "DSH credential store",
		"project-env": "project .env",
		"user-env": "user .env"
	}[source] ?? source;
}
function apiKeyFailure(value) {
	if (value.length === 0 || value.trim().length === 0) return "Enter a Firecrawl API key.";
	const trimmed = value.trim();
	if (!/^[\x21-\x7e]+$/u.test(trimmed)) return "Use an unquoted API key containing printable characters only.";
	if (/^[A-Za-z_][A-Za-z0-9_]*=/u.test(trimmed) || trimmed.startsWith("\"") && trimmed.endsWith("\"") || trimmed.startsWith("'") && trimmed.endsWith("'")) return "Paste only the API key, without FIRECRAWL_API_KEY= or surrounding quotes.";
}

//#endregion
//#region client/styles.ts
const styles = {
	section: {
		display: "flex",
		flexDirection: "column",
		gap: "16px",
		width: "min(720px, 100%)"
	},
	card: {
		display: "flex",
		flexDirection: "column",
		gap: "16px",
		padding: "18px",
		border: "1px solid color-mix(in srgb, currentColor 16%, transparent)",
		borderRadius: "12px",
		background: "color-mix(in srgb, currentColor 3%, transparent)"
	},
	row: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: "12px"
	},
	title: {
		margin: 0,
		fontSize: "16px",
		fontWeight: 650
	},
	badge: {
		display: "inline-flex",
		alignItems: "center",
		gap: "7px",
		fontSize: "13px",
		opacity: .82
	},
	dot: (configured) => ({
		width: "8px",
		height: "8px",
		borderRadius: "999px",
		background: configured ? "#22c55e" : "#ef4444"
	}),
	label: {
		display: "flex",
		flexDirection: "column",
		gap: "7px",
		fontSize: "13px",
		fontWeight: 600
	},
	input: {
		width: "100%",
		boxSizing: "border-box",
		border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
		borderRadius: "8px",
		background: "transparent",
		color: "inherit",
		font: "inherit",
		padding: "10px 12px"
	},
	hint: {
		margin: 0,
		fontSize: "13px",
		opacity: .68,
		lineHeight: 1.45
	},
	actions: {
		display: "flex",
		gap: "10px",
		flexWrap: "wrap"
	},
	button: {
		border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
		borderRadius: "8px",
		background: "color-mix(in srgb, currentColor 8%, transparent)",
		color: "inherit",
		font: "inherit",
		fontWeight: 600,
		padding: "8px 13px",
		cursor: "pointer"
	},
	danger: { color: "#ef4444" },
	message: (error) => ({
		margin: 0,
		fontSize: "13px",
		color: error ? "#ef4444" : "#22c55e"
	})
};

//#endregion
//#region client/FirecrawlSettingsSection.tsx
function FirecrawlSettingsSection(props) {
	const { api, subscribe } = props;
	const [credential, setCredential] = react.default.useState(void 0);
	const [draft, setDraft] = react.default.useState("");
	const [busy, setBusy] = react.default.useState(false);
	const [failure, setFailure] = react.default.useState(void 0);
	const [success, setSuccess] = react.default.useState(void 0);
	const [revision, setRevision] = react.default.useState(0);
	react.default.useEffect(() => subscribe(() => setRevision((value) => value + 1)), [subscribe]);
	react.default.useEffect(() => {
		let active = true;
		setFailure(void 0);
		Promise.resolve().then(() => api.credentials.describe([CREDENTIAL_REF])).then((response) => {
			if (!active) return;
			if (!response.ok) {
				setCredential(null);
				setFailure(response.error.message);
				return;
			}
			setCredential(response.value["FIRECRAWL_API_KEY"] ?? {
				configured: false,
				writable: false
			});
		}, (error) => {
			if (!active) return;
			setCredential(null);
			setFailure(messageOf(error));
		});
		return () => {
			active = false;
		};
	}, [api, revision]);
	const save = async () => {
		const validation = apiKeyFailure(draft);
		if (validation !== void 0) {
			setFailure(validation);
			setSuccess(void 0);
			return;
		}
		setBusy(true);
		setFailure(void 0);
		setSuccess(void 0);
		try {
			const response = await api.credentials.set(CREDENTIAL_REF, draft.trim());
			if (!response.ok) {
				setFailure(response.error.message);
				return;
			}
			setDraft("");
			setSuccess("Firecrawl API key saved. The next web request will use it.");
			setRevision((value) => value + 1);
		} catch (error) {
			setFailure(messageOf(error));
		} finally {
			setBusy(false);
		}
	};
	const remove = async () => {
		if (!window.confirm("Remove the stored Firecrawl API key?")) return;
		setBusy(true);
		setFailure(void 0);
		setSuccess(void 0);
		try {
			const response = await api.credentials.unset(CREDENTIAL_REF);
			if (!response.ok) {
				setFailure(response.error.message);
				return;
			}
			setDraft("");
			setSuccess("Stored Firecrawl API key removed.");
			setRevision((value) => value + 1);
		} catch (error) {
			setFailure(messageOf(error));
		} finally {
			setBusy(false);
		}
	};
	const configured = credential?.configured === true;
	const writable = credential?.writable === true;
	const source = credential?.source === void 0 ? void 0 : sourceLabel(credential.source);
	const status = credential === void 0 ? "Checking…" : credential === null ? "Unavailable" : configured ? `Configured${source === void 0 ? "" : ` via ${source}`}` : "Not configured";
	return /* @__PURE__ */ react.default.createElement("details", {
		style: {
			...styles.card,
			display: "block"
		},
		open: props.view === "page" || void 0
	}, /* @__PURE__ */ react.default.createElement("summary", { style: { cursor: "pointer" } }, /* @__PURE__ */ react.default.createElement("span", { style: styles.title }, "Firecrawl"), /* @__PURE__ */ react.default.createElement("p", { style: {
		...styles.hint,
		marginTop: "4px"
	} }, "Web search and page fetching via Firecrawl.")), /* @__PURE__ */ react.default.createElement("div", {
		style: {
			...styles.section,
			marginTop: "16px"
		},
		role: "group",
		"aria-labelledby": "firecrawl-card-title"
	}, /* @__PURE__ */ react.default.createElement("div", { style: styles.row }, /* @__PURE__ */ react.default.createElement("h3", {
		id: "firecrawl-card-title",
		style: styles.title
	}, "Firecrawl"), /* @__PURE__ */ react.default.createElement("span", {
		style: styles.badge,
		role: "status"
	}, /* @__PURE__ */ react.default.createElement("span", {
		style: styles.dot(configured),
		"aria-hidden": "true"
	}), status)), /* @__PURE__ */ react.default.createElement("label", { style: styles.label }, configured ? "Replace API key" : "API key", /* @__PURE__ */ react.default.createElement("input", {
		type: "password",
		value: draft,
		disabled: busy || !writable,
		autoComplete: "off",
		spellCheck: false,
		placeholder: configured ? "Enter a new key" : "fc-…",
		style: styles.input,
		onChange: (event) => setDraft(event.target.value),
		onKeyDown: (event) => {
			if (event.key === "Enter" && !busy && writable) save();
		}
	})), /* @__PURE__ */ react.default.createElement("p", { style: styles.hint }, credential === void 0 ? "Checking credential access…" : credential === null ? "Could not check credential access. See the error below." : writable ? "The key is sent write-only to DSH’s credential store and is never returned to this page." : configured ? "This key comes from a read-only source. Remove it from that source before managing it here." : "Credential writes are unavailable from this browser. Open DSH on its loopback URL."), /* @__PURE__ */ react.default.createElement("div", { style: styles.actions }, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy || !writable,
		style: {
			...styles.button,
			opacity: busy || !writable ? .5 : 1
		},
		onClick: () => {
			save();
		}
	}, busy ? "Saving…" : configured ? "Replace key" : "Save key"), configured && writable ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy,
		style: {
			...styles.button,
			...styles.danger,
			opacity: busy ? .5 : 1
		},
		onClick: () => {
			remove();
		}
	}, "Remove key") : null), failure === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", {
		style: styles.message(true),
		role: "alert"
	}, failure), success === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", {
		style: styles.message(false),
		role: "status"
	}, success)));
}

//#endregion
//#region client/index.ts
function FirecrawlConfigPage(props) {
	return props.view === "summary" ? "Configure Firecrawl access for web search and fetch." : react.default.createElement(FirecrawlSettingsSection, props);
}
const inject = [
	"slots",
	"remote",
	"remote.credentials"
];
function apply(ctx) {
	const subscribe = (listener) => {
		const disposers = [ctx.remote.$on("credentials/reference-updated", (ref) => {
			if (ref === "FIRECRAWL_API_KEY") listener();
		}), ctx.on("connection/reset", listener)];
		return () => {
			for (const dispose of disposers) dispose();
		};
	};
	const injected = () => ({
		api: ctx.remote,
		subscribe
	});
	ctx.slots.inject("plugins.row.config", () => ctx.slots.register({
		name: "plugins.row.config",
		key: "@local/dsh-web-firecrawl#local-web-firecrawl",
		order: 20,
		inject: injected
	}, FirecrawlConfigPage));
}

//#endregion
exports.FirecrawlSettingsSection = FirecrawlSettingsSection;
exports.apiKeyFailure = apiKeyFailure;
exports.apply = apply;
exports.inject = inject;
return module.exports; } });