// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-codex-compat", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CHANNEL = "/codex-fast-integration";
const COST_NOTICE = "Fast mode uses subscription limits at a higher rate (currently 2.5× included usage). Availability depends on your OpenAI plan and model.";
function isObject(value) {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}
function isIntegrationStatus(value) {
	return isObject(value) && typeof value.enabled === "boolean" && Number.isSafeInteger(value.revision) && typeof value.available === "boolean" && (value.error === null || typeof value.error === "string");
}
function isFastStatus(value) {
	return isIntegrationStatus(value) && isObject(value) && typeof value.sessionId === "string" && typeof value.provider === "string" && typeof value.model === "string" && typeof value.requested === "boolean" && typeof value.supported === "boolean" && Number.isSafeInteger(value.sessionRevision) && typeof value.subagentsRequested === "boolean" && Number.isSafeInteger(value.subagentsRevision) && typeof value.sessionOffPending === "boolean" && typeof value.subagentsOffPending === "boolean" && [
		"none",
		"requested",
		"error"
	].includes(String(value.observation)) && (value.notice === null || typeof value.notice === "string");
}

//#endregion
//#region client/fast/controls.tsx
async function call(rpc, endpoint, payload, valid) {
	let result;
	try {
		result = await rpc.call(CHANNEL, endpoint, payload);
	} catch {
		throw new Error("Codex Fast settings request failed.");
	}
	if (!isObject(result) || result.ok !== true || !valid(result.value)) {
		const message = isObject(result) && isObject(result.error) && typeof result.error.message === "string" ? result.error.message : "Codex Fast settings are unavailable.";
		throw new Error(message);
	}
	return result.value;
}
const box = {
	display: "flex",
	flexWrap: "wrap",
	alignItems: "center",
	gap: 8,
	fontSize: 12,
	color: "var(--dsw-alias-label-secondary)"
};
const control = {
	padding: "5px 8px",
	borderRadius: 6,
	borderWidth: 1,
	borderStyle: "solid",
	borderColor: "var(--dsw-alias-border-l1)",
	background: "var(--dsw-alias-bg-layer-1)",
	color: "var(--dsw-alias-label-primary)",
	font: "inherit",
	cursor: "pointer"
};
function FastToggle({ rpc, sessionId, useProjection }) {
	const projection = useProjection("modelSelection");
	const [state, setState] = (0, react.useState)(null);
	const [busy, setBusy] = (0, react.useState)(false);
	const [error, setError] = (0, react.useState)("");
	const [expanded, setExpanded] = (0, react.useState)(false);
	const details = (0, react.useRef)(null);
	const anchor = (0, react.useRef)(null);
	const panel = (0, react.useRef)(null);
	const [panelPosition, setPanelPosition] = (0, react.useState)({
		left: 16,
		top: 16
	});
	const generation = (0, react.useRef)(0);
	const readSequence = (0, react.useRef)(0);
	const mutating = (0, react.useRef)(false);
	(0, react.useLayoutEffect)(() => {
		if (!expanded || !anchor.current || !panel.current) return;
		const position = () => {
			if (!anchor.current || !panel.current) return;
			const trigger = anchor.current.getBoundingClientRect();
			const content = panel.current.getBoundingClientRect();
			const left = Math.max(16, Math.min(trigger.right - content.width, window.innerWidth - content.width - 16));
			const above = trigger.top - content.height - 8;
			const below = trigger.bottom + 8;
			const top = above >= 16 ? above : below + content.height <= window.innerHeight - 16 ? below : Math.max(16, window.innerHeight - content.height - 16);
			setPanelPosition((previous) => previous.left === left && previous.top === top ? previous : {
				left,
				top
			});
		};
		position();
		const observer = new ResizeObserver(position);
		observer.observe(anchor.current);
		observer.observe(panel.current);
		window.addEventListener("resize", position);
		window.addEventListener("scroll", position, true);
		return () => {
			observer.disconnect();
			window.removeEventListener("resize", position);
			window.removeEventListener("scroll", position, true);
		};
	}, [expanded]);
	(0, react.useEffect)(() => {
		if (!expanded) return;
		const closeOutside = (event) => {
			if (event.target instanceof Node && !details.current?.contains(event.target)) setExpanded(false);
		};
		const closeOnEscape = (event) => {
			if (event.key !== "Escape") return;
			event.preventDefault();
			setExpanded(false);
			details.current?.querySelector("summary")?.focus();
		};
		document.addEventListener("pointerdown", closeOutside);
		document.addEventListener("keydown", closeOnEscape);
		return () => {
			document.removeEventListener("pointerdown", closeOutside);
			document.removeEventListener("keydown", closeOnEscape);
		};
	}, [expanded]);
	(0, react.useEffect)(() => {
		const current = ++generation.current;
		mutating.current = false;
		setState(null);
		setError("");
		setBusy(false);
		setExpanded(false);
		const refresh = () => {
			if (mutating.current) return;
			const sequence = ++readSequence.current;
			call(rpc, "session-status", { sessionId }, isFastStatus).then((value) => {
				if (current === generation.current && sequence === readSequence.current && value.sessionId === sessionId) {
					setState(value);
					setError("");
				}
			}, () => {
				if (current === generation.current && sequence === readSequence.current) {
					setState(null);
					setError("Fast settings unavailable. Standard inference is unaffected while Fast is off.");
				}
			});
		};
		refresh();
		window.addEventListener("focus", refresh);
		window.addEventListener("dsh-codex-fast-changed", refresh);
		return () => {
			++generation.current;
			window.removeEventListener("focus", refresh);
			window.removeEventListener("dsh-codex-fast-changed", refresh);
		};
	}, [
		rpc,
		sessionId,
		projection
	]);
	const toggle = async (scope, desired) => {
		if (!state || busy || mutating.current) return;
		const enabled = desired ?? !(scope === "subagents" ? state.subagentsRequested : state.requested);
		const current = generation.current;
		++readSequence.current;
		mutating.current = true;
		setBusy(true);
		setError("");
		try {
			const result = scope === "subagents" ? await call(rpc, "subagents-set", {
				sessionId,
				enabled,
				revision: state.subagentsRevision
			}, isFastStatus) : await call(rpc, "session-set", {
				sessionId,
				provider: enabled ? state.provider : "openai-codex",
				model: state.model,
				enabled,
				revision: state.sessionRevision
			}, isFastStatus);
			if (current === generation.current) setState(result);
		} catch (failure) {
			if (current === generation.current) {
				setError(failure instanceof Error ? failure.message : "Fast setting failed.");
				setExpanded(true);
				try {
					const fresh = await call(rpc, "session-status", { sessionId }, isFastStatus);
					if (current === generation.current) setState(fresh);
				} catch {
					if (current === generation.current) setState(null);
				}
			}
		} finally {
			if (current === generation.current) {
				mutating.current = false;
				setBusy(false);
			}
		}
	};
	const unavailable = !state?.enabled ? "Fast integration is disabled. Enable it in Plugins → Codex Fast." : !state.available ? state.error : !state.supported ? state.notice : null;
	const checked = !!state?.requested && !!state.enabled && !!state.available && state.supported;
	const subagentsChecked = !!state?.subagentsRequested && !!state.enabled && !!state.available;
	const integrationUnavailable = !state?.enabled || !state.available;
	return /* @__PURE__ */ react.default.createElement("div", {
		ref: anchor,
		style: {
			...box,
			flexWrap: "nowrap",
			gap: 0,
			position: "relative"
		},
		"data-codex-fast-control": true
	}, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		role: "switch",
		"aria-label": "Codex Fast mode",
		"aria-checked": checked,
		disabled: busy || !state || !state.requested && !!unavailable,
		style: {
			...control,
			borderTopRightRadius: 0,
			borderBottomRightRadius: 0,
			whiteSpace: "nowrap",
			...checked ? { borderColor: "var(--dsw-alias-brand-primary)" } : {}
		},
		title: unavailable ?? "Fast mode uses subscription limits at a higher rate (currently 2.5× included usage). Availability depends on your OpenAI plan and model.",
		onClick: () => {
			toggle("session");
		}
	}, "Fast ", checked ? "On" : "Off"), /* @__PURE__ */ react.default.createElement("details", {
		ref: details,
		open: expanded,
		onToggle: () => setExpanded(details.current?.open ?? false)
	}, /* @__PURE__ */ react.default.createElement("summary", {
		role: "button",
		"aria-label": "Fast options",
		"aria-expanded": expanded,
		title: subagentsChecked ? "Fast options — Subagents Fast is on" : "Fast options and higher usage",
		style: {
			...control,
			display: "block",
			listStyle: "none",
			whiteSpace: "nowrap",
			borderTopLeftRadius: 0,
			borderBottomLeftRadius: 0,
			marginLeft: -1,
			...subagentsChecked ? { borderColor: "var(--dsw-alias-brand-primary)" } : {}
		}
	}, subagentsChecked ? "Subagents On " : "", "▾"), /* @__PURE__ */ react.default.createElement("section", {
		ref: panel,
		"aria-label": "Fast options",
		style: {
			...box,
			display: "block",
			position: "fixed",
			...panelPosition,
			zIndex: 1100,
			boxSizing: "border-box",
			width: "min(320px, calc(100vw - 32px))",
			maxHeight: "calc(100vh - 120px)",
			overflowY: "auto",
			padding: 14,
			borderRadius: 10,
			border: "1px solid var(--dsw-alias-border-l1)",
			background: "var(--dsw-alias-bg-layer-1)",
			boxShadow: "var(--dsw-elevation-prominent)",
			lineHeight: "18px"
		}
	}, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		role: "switch",
		"aria-label": "Subagents Fast",
		"aria-checked": subagentsChecked,
		disabled: busy || !state || !state.subagentsRequested && integrationUnavailable,
		style: control,
		onClick: () => {
			toggle("subagents");
		}
	}, "Subagents Fast ", subagentsChecked ? "On" : "Off"), /* @__PURE__ */ react.default.createElement("p", null, "Independent of this session’s Fast switch. Applies to eligible Codex subagents, including nested subagents. Other models stay unchanged."), /* @__PURE__ */ react.default.createElement("strong", null, "Higher usage"), /* @__PURE__ */ react.default.createElement("p", null, COST_NOTICE), /* @__PURE__ */ react.default.createElement("p", null, "Changes affect new requests. A request whose body is already prepared may still use Fast."), /* @__PURE__ */ react.default.createElement("p", null, unavailable ?? state?.notice ?? "Fast requests priority service; OpenAI’s effective tier is not confirmed."), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: control,
		onClick: () => window.dispatchEvent(new Event("dsh-codex-fast-changed"))
	}, "Refresh Fast status"), state?.sessionOffPending || state?.subagentsOffPending ? /* @__PURE__ */ react.default.createElement("div", null, /* @__PURE__ */ react.default.createElement("p", null, "Off applies in this process. Persist Off before restarting."), state.sessionOffPending ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: control,
		disabled: busy,
		onClick: () => {
			toggle("session", false);
		}
	}, "Retry session Off") : null, state.subagentsOffPending ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: control,
		disabled: busy,
		onClick: () => {
			toggle("subagents", false);
		}
	}, "Retry Subagents Off") : null) : null, error ? /* @__PURE__ */ react.default.createElement("p", {
		role: "alert",
		style: { color: "var(--dsw-alias-state-error-primary)" }
	}, error) : null)), error && !expanded ? /* @__PURE__ */ react.default.createElement("span", {
		role: "alert",
		style: {
			color: "var(--dsw-alias-state-error-primary)",
			marginLeft: 8
		}
	}, error) : null);
}
function IntegrationSettings({ rpc, view }) {
	return view === "summary" ? /* @__PURE__ */ react.default.createElement("span", null, "Optional Fast mode; disabling it preserves Codex login and Standard inference.") : /* @__PURE__ */ react.default.createElement(IntegrationForm, { rpc });
}
function IntegrationForm({ rpc }) {
	const [state, setState] = (0, react.useState)(null);
	const [busy, setBusy] = (0, react.useState)(false);
	const [error, setError] = (0, react.useState)("");
	const generation = (0, react.useRef)(0);
	const refresh = () => {
		const current = ++generation.current;
		call(rpc, "integration-status", {}, isIntegrationStatus).then((value) => {
			if (current === generation.current) {
				setState(value);
				setError("");
			}
		}, () => {
			if (current === generation.current) setError("Fast integration status is unavailable.");
		});
	};
	(0, react.useEffect)(() => {
		setState(null);
		refresh();
		return () => {
			++generation.current;
		};
	}, [rpc]);
	const toggle = async () => {
		if (!state || busy) return;
		const current = ++generation.current;
		setBusy(true);
		setError("");
		try {
			const value = await call(rpc, "integration-set", {
				enabled: !state.enabled,
				revision: state.revision
			}, isIntegrationStatus);
			if (current === generation.current) setState(value);
			window.dispatchEvent(new Event("dsh-codex-fast-changed"));
		} catch (failure) {
			if (current === generation.current) {
				setError(failure instanceof Error ? failure.message : "Fast integration update failed.");
				try {
					const value = await call(rpc, "integration-status", {}, isIntegrationStatus);
					if (current === generation.current) setState(value);
				} catch {}
			}
		} finally {
			if (current === generation.current) setBusy(false);
		}
	};
	return /* @__PURE__ */ react.default.createElement("section", {
		style: {
			...box,
			display: "block",
			maxWidth: 640
		},
		"aria-label": "Codex Fast integration settings"
	}, /* @__PURE__ */ react.default.createElement("h3", { style: { color: "var(--dsw-alias-label-primary)" } }, "Codex Fast"), /* @__PURE__ */ react.default.createElement("p", null, "Keep the plugin installed while turning its inference integration off. Codex login and Standard inference do not depend on this switch."), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		role: "switch",
		"aria-label": "Codex Fast integration",
		"aria-checked": state?.enabled ?? false,
		disabled: !state || busy,
		style: control,
		onClick: () => {
			toggle();
		}
	}, "Fast integration ", state?.enabled ? "On" : "Off"), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: {
			...control,
			marginLeft: 8
		},
		disabled: busy,
		onClick: refresh
	}, "Refresh integration status"), /* @__PURE__ */ react.default.createElement("p", null, "Off stops new Fast requests and pending payload construction. A request whose body is already prepared may still use Fast, even while its connection is opening."), /* @__PURE__ */ react.default.createElement("p", null, COST_NOTICE), /* @__PURE__ */ react.default.createElement("p", null, "New sessions start on Standard with Subagents Fast off. This session’s Fast selection stays tied to the exact selected model. Its independent Subagents Fast setting covers eligible Codex descendants, even when this session uses Standard or another provider. Both choices survive resume but are not copied to new top-level sessions or forks. Title, summary, and compaction calls stay unchanged."), /* @__PURE__ */ react.default.createElement("p", null, "Diagnostics report that Fast was requested—not that OpenAI confirmed the effective tier. No credentials or prompts are inspected."), state?.error || error ? /* @__PURE__ */ react.default.createElement("p", {
		role: "alert",
		style: { color: "var(--dsw-alias-state-error-primary)" }
	}, error || state?.error) : null);
}

//#endregion
//#region client/index.ts
function apply(ctx) {
	ctx.slots.inject("conversation.input.right", () => ctx.slots.register({
		name: "conversation.input.right",
		id: "local-codex-fast",
		order: 10,
		inject: () => ({ rpc: ctx.get("connection").rpc })
	}, FastToggle));
	ctx.slots.inject("plugins.row.config", () => ctx.slots.register({
		name: "plugins.row.config",
		key: "@local/dsh-codex-compat#local-codex-fast",
		inject: () => ({ rpc: ctx.get("connection").rpc })
	}, IntegrationSettings));
}
var client_default = {
	inject: ["slots", "connection"],
	apply
};

//#endregion
exports.apply = apply;
exports.default = client_default;
return module.exports.default; } });