import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// RC2 client-modules reads one ./client export as bytes; it does not serve
// sibling imports. Keep one registration: HMR invalidates only the package ID.
// These are lexical source fragments, not ESM or additional loader factories.
export const clientSources = Object.freeze([
  'rpc.js',
  'return-tracker.js',
  'controller.js',
  'cards.js',
  'styles.js',
  'selection-details.js',
  'recap-components.js',
  'settings-card.js',
  'registration.js',
])

export const clientPath = new URL('../client.js', import.meta.url)

export function assembleClient() {
  const fragments = clientSources.map((name) => {
    const source = readFileSync(new URL(`../client/${name}`, import.meta.url), 'utf8')
    return `    // ---- client/${name} ----\n${source.trimEnd().split('\n').map(line => line ? `    ${line}` : '').join('\n')}\n`
  })
  return `// GENERATED by scripts/build-client.mjs. Edit client/* sources, not this file.
// Committed plain-JS entry: installing this package requires no build step.
window.__ModuleLoader__.load({
  id: '@wombat9000/dsh-session-recap',
  factory: (require) => {
    const React = require('react')

${fragments.join('\n')}
    return { inject: ['slots', 'connection', 'remote'], apply, createController, RecapCard, RecapAction, SettingsCard, CARD_LABELS, CHANNEL }
  },
})
`
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2)
  if (args.length && (args.length !== 1 || args[0] !== '--check')) {
    throw new Error('Usage: node scripts/build-client.mjs [--check]')
  }
  const assembled = assembleClient()
  if (args[0] === '--check') {
    if (readFileSync(clientPath, 'utf8') !== assembled) {
      throw new Error('client.js is stale. Run node packages/dsh-session-recap/scripts/build-client.mjs from the repository root.')
    }
  } else {
    writeFileSync(clientPath, assembled)
  }
}
