import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'tsdown'
import { typecheck } from './typecheck.mjs'

const packageRoot = fileURLToPath(new URL('../', import.meta.url))
const manifest = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
export const clientPath = new URL('../client.js', import.meta.url)
const allowedExternals = new Set(['react'])

// RC2 serves one ./client file and invalidates its package ID during HMR.
// Author TypeScript/TSX; wrap the bundled CommonJS output in one lazy factory.
// This bundling API does not replace type checking; the CLI and test suite run it.
export async function buildClient() {
  const bundles = await build({
    cwd: packageRoot,
    config: false,
    tsconfig: false,
    entry: { client: 'client/index.ts' },
    outDir: packageRoot,
    format: 'cjs',
    platform: 'browser',
    target: 'es2022',
    dts: false,
    sourcemap: false,
    minify: false,
    clean: false,
    write: false,
    report: false,
    logLevel: 'silent',
    define: { 'process.env.NODE_ENV': JSON.stringify('production') },
    deps: { neverBundle: ['react'], onlyBundle: [] },
    inputOptions: { transform: { jsx: 'react' } },
    outputOptions: {
      entryFileNames: 'client.js',
      banner: `// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.\nwindow.__ModuleLoader__.load({ id: ${JSON.stringify(manifest.name)}, factory: (require) => {`,
      intro: 'var module = { exports: {} }; var exports = module.exports;',
      footer: 'return module.exports; } });',
    },
  })
  try {
    const chunks = bundles.flatMap((bundle) => bundle.chunks)
    if (chunks.length !== 1 || chunks[0].type !== 'chunk' || !chunks[0].isEntry) {
      throw new Error('Expected exactly one executable client bundle.')
    }
    const chunk = chunks[0]
    const unsupported = chunk.imports.filter((id) => !allowedExternals.has(id))
    if (unsupported.length || chunk.dynamicImports.length) {
      throw new Error(
        `Unsupported client imports: ${[...unsupported, ...chunk.dynamicImports].join(', ')}`,
      )
    }
    if (/\bprocess\.env\b/u.test(chunk.code)) {
      throw new Error('Client bundle must not depend on the Node.js process environment.')
    }
    return chunk.code
  } finally {
    for (const bundle of bundles) await bundle[Symbol.asyncDispose]()
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2)
  if (args.length && (args.length !== 1 || args[0] !== '--check')) {
    throw new Error('Usage: node scripts/build-client.mjs [--check]')
  }
  await typecheck()
  const output = await buildClient()
  if (args[0] === '--check') {
    if (readFileSync(clientPath, 'utf8') !== output) {
      throw new Error(
        'client.js is stale. Run node packages/dsh-session-recap/scripts/build-client.mjs from the repository root.',
      )
    }
  } else {
    writeFileSync(clientPath, output)
  }
}
