// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-openrouter", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CHANNEL = "/openrouter-integration";
function isObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isStatus(value) {
	return isObject(value) && typeof value.configured === "boolean" && typeof value.writable === "boolean" && typeof value.source === "string" && (typeof value.target === "string" || value.target === null) && (value.reference === void 0 || typeof value.reference === "string") && (value.error === void 0 || typeof value.error === "string");
}

//#endregion
//#region client/transport.ts
async function call(rpc, method, payload) {
	let result;
	try {
		result = await rpc.call(CHANNEL, method, payload);
	} catch {
		throw new Error("OpenRouter settings request failed.");
	}
	if (!isObject(result) || result.ok !== true) {
		const error = isObject(result) && isObject(result.error) ? result.error.message : void 0;
		throw new Error(typeof error === "string" && error ? error : "OpenRouter settings are unavailable.");
	}
	if (!isStatus(result.value)) throw new Error("OpenRouter settings are unavailable.");
	return result.value;
}

//#endregion
//#region client/styles.ts
const css = `
      .dsh-openrouter { border: .5px solid var(--dsw-alias-border-l4); border-radius: 16px; background: var(--dsw-alias-bg-layer-3); color: var(--dsw-alias-label-primary); }
      .dsh-openrouter summary { cursor: pointer; padding: 14px 16px; font-size: 15px; font-weight: 600; }
      .dsh-openrouter[open] { background: var(--dsw-alias-bg-layer-2); }
      .dsh-openrouter__body { display: grid; gap: 12px; margin: 0 16px; padding: 12px 0 16px; border-top: .5px solid var(--dsw-alias-border-l2); font-size: 13px; line-height: 1.5; }
      .dsh-openrouter p { margin: 0; }
      .dsh-openrouter label { display: grid; gap: 6px; }
      .dsh-openrouter input { box-sizing: border-box; width: 100%; min-width: 0; height: 34px; padding: 0 10px; border: .5px solid var(--dsw-alias-border-l4); border-radius: 8px; font: inherit; color: inherit; background: var(--dsw-alias-bg-layer-3); }
      .dsh-openrouter button { font: inherit; color: inherit; background: transparent; border: .5px solid var(--dsw-alias-border-l4); border-radius: 8px; padding: 5px 12px; cursor: pointer; }
      .dsh-openrouter button:disabled, .dsh-openrouter input:disabled { opacity: .5; cursor: default; }
      .dsh-openrouter button:focus-visible, .dsh-openrouter input:focus-visible, .dsh-openrouter summary:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 2px; }
      .dsh-openrouter__actions { display: flex; gap: 8px; flex-wrap: wrap; }
      .dsh-openrouter__hint { color: var(--dsw-alias-label-secondary); }
      .dsh-openrouter [role=alert] { color: var(--dsw-alias-label-error); }
    `;

//#endregion
//#region client/settings.tsx
function SettingsCard(props) {
	return props.view === "summary" ? /* @__PURE__ */ react.default.createElement("p", null, "Shared OpenRouter credential for trusted integrations.") : /* @__PURE__ */ react.default.createElement(SettingsForm, props);
}
function SettingsForm({ rpc, view }) {
	const [status, setStatus] = (0, react.useState)(null);
	const [draft, setDraft] = (0, react.useState)("");
	const [busy, setBusy] = (0, react.useState)(false);
	const [error, setError] = (0, react.useState)("");
	const [notice, setNotice] = (0, react.useState)("");
	const alive = (0, react.useRef)(false);
	(0, react.useEffect)(() => {
		alive.current = true;
		const style = document.createElement("style");
		style.dataset.pluginCss = "openrouter/settings";
		style.textContent = css;
		document.head.appendChild(style);
		call(rpc, "status", {}).then((value) => {
			if (alive.current) setStatus(value);
		}, () => {
			if (alive.current) setError("Could not read OpenRouter credential status.");
		});
		return () => {
			alive.current = false;
			style.remove();
		};
	}, [rpc]);
	const mutate = async (method) => {
		if (busy || !status?.writable || status.target === null) return;
		if (method === "clear" && !window.confirm("Remove the shared OpenRouter key? This affects every integration and DSH model route using it. A lower-priority environment key may become active.")) return;
		setBusy(true);
		setError("");
		setNotice("");
		try {
			const value = method === "save" ? await call(rpc, "save", {
				target: status.target,
				apiKey: draft.trim()
			}) : await call(rpc, "clear", { target: status.target });
			if (alive.current) {
				setStatus(value);
				setDraft("");
				setNotice(method === "save" ? "Shared OpenRouter key saved. No remote request was made." : "Stored key removed. Effective credential status refreshed.");
			}
		} catch (failure) {
			if (alive.current) {
				setError(failure instanceof Error ? failure.message : "OpenRouter settings are unavailable.");
				try {
					const value = await call(rpc, "status", {});
					if (alive.current) setStatus(value);
				} catch {
					if (alive.current) setStatus(null);
				}
			}
		} finally {
			if (alive.current) setBusy(false);
		}
	};
	return /* @__PURE__ */ react.default.createElement("details", {
		className: "dsh-openrouter",
		"aria-label": "OpenRouter settings",
		open: view === "page"
	}, /* @__PURE__ */ react.default.createElement("summary", null, "OpenRouter"), /* @__PURE__ */ react.default.createElement("div", { className: "dsh-openrouter__body" }, /* @__PURE__ */ react.default.createElement("p", { role: "status" }, status ? `Shared key: ${status.configured ? "Configured" : "Not configured"}${status.source ? ` (${status.source})` : ""}` : "Checking shared key…"), /* @__PURE__ */ react.default.createElement("p", { className: "dsh-openrouter__hint" }, "One credential for trusted OpenRouter integrations and the built-in OpenRouter model route. Replacing or removing it affects all consumers. The key is stored in DSH credentials, never ordinary plugin settings."), status && !status.writable ? /* @__PURE__ */ react.default.createElement("p", null, "This credential source is read-only. Change it where it is configured.") : null, /* @__PURE__ */ react.default.createElement("label", null, "OpenRouter API key", /* @__PURE__ */ react.default.createElement("input", {
		type: "password",
		value: draft,
		disabled: busy || !status?.writable,
		autoComplete: "off",
		spellCheck: false,
		onChange: (event) => setDraft(event.target.value)
	})), /* @__PURE__ */ react.default.createElement("div", { className: "dsh-openrouter__actions" }, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy || !status?.writable || !draft.trim(),
		onClick: () => {
			mutate("save");
		}
	}, "Save shared key"), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy || !status?.writable || !status?.configured,
		onClick: () => {
			mutate("clear");
		}
	}, "Remove shared key")), error || status?.error ? /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error || status?.error) : null, notice ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, notice) : null));
}

//#endregion
//#region client/index.ts
function apply(ctx) {
	ctx.slots.inject("plugins.row.config", () => ctx.slots.register({
		name: "plugins.row.config",
		key: "@local/dsh-openrouter#local-openrouter",
		inject: () => ({ rpc: ctx.get("connection").rpc })
	}, SettingsCard));
}
var client_default = {
	inject: ["slots", "connection"],
	apply,
	SettingsCard
};

//#endregion
exports.SettingsCard = SettingsCard;
exports.apply = apply;
exports.default = client_default;
return module.exports.default; } });