import type { CSSProperties } from 'react'

export const styles = {
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '12px',
    border: '1px solid var(--dsw-alias-border-l2-darkmode-thin)',
    borderRadius: '12px',
    background: 'var(--dsw-specific-input-major)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    fontSize: '13px',
    color: 'var(--dsw-alias-label-secondary)',
  },
  title: { fontWeight: 650, color: 'var(--dsw-alias-label-primary)' },
  gallery: { display: 'flex', flexWrap: 'wrap', gap: '10px' },
  frame: {
    display: 'block',
    maxWidth: 'min(100%, 560px)',
    padding: 0,
    border: 0,
    borderRadius: '10px',
    background: 'transparent',
    cursor: 'zoom-in',
    overflow: 'hidden',
  },
  image: {
    display: 'block',
    maxWidth: '100%',
    width: 'auto',
    height: 'auto',
    maxHeight: '420px',
    borderRadius: '10px',
    objectFit: 'contain',
  },
  placeholder: {
    display: 'grid',
    placeItems: 'center',
    minWidth: '220px',
    minHeight: '140px',
    padding: '16px',
    borderRadius: '10px',
    background: 'var(--dsw-alias-interactive-bg-hover)',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: '13px',
  },
  error: { color: 'var(--dsw-alias-label-error)', cursor: 'pointer' },
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'grid',
    placeItems: 'center',
    padding: '40px',
    border: 0,
    background: 'var(--dsw-alias-bg-mask-1)',
    backdropFilter: 'var(--dsw-mask-blur)',
    cursor: 'zoom-out',
  },
  fullImage: {
    display: 'block',
    maxWidth: 'min(100%, 1600px)',
    maxHeight: 'calc(100vh - 80px)',
    borderRadius: '12px',
    objectFit: 'contain',
    boxShadow: 'var(--dsw-shadow-lv3)',
  },
} satisfies Record<string, CSSProperties>
