import type React from 'react'
export const styles = {
  section: { display: 'flex', flexDirection: 'column', gap: '16px', width: 'min(760px, 100%)' },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '18px',
    border: '1px solid color-mix(in srgb, currentColor 16%, transparent)',
    borderRadius: '12px',
    background: 'color-mix(in srgb, currentColor 3%, transparent)',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
  title: { margin: 0, fontSize: '16px', fontWeight: 650 },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    fontSize: '13px',
    opacity: 0.82,
  },
  dot: (configured: boolean, live: boolean): React.CSSProperties => ({
    width: '8px',
    height: '8px',
    borderRadius: '999px',
    background: live ? '#22c55e' : configured ? '#f59e0b' : '#ef4444',
  }),
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    fontSize: '13px',
    fontWeight: 600,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid color-mix(in srgb, currentColor 22%, transparent)',
    borderRadius: '8px',
    background: 'transparent',
    color: 'inherit',
    font: 'inherit',
    padding: '10px 12px',
  },
  hint: { margin: 0, fontSize: '13px', opacity: 0.68, lineHeight: 1.45 },
  details: {
    display: 'grid',
    gridTemplateColumns: 'max-content 1fr',
    gap: '6px 16px',
    fontSize: '13px',
  },
  term: { opacity: 0.62 },
  actions: { display: 'flex', gap: '10px', flexWrap: 'wrap' },
  button: {
    border: '1px solid color-mix(in srgb, currentColor 22%, transparent)',
    borderRadius: '8px',
    background: 'color-mix(in srgb, currentColor 8%, transparent)',
    color: 'inherit',
    font: 'inherit',
    fontWeight: 600,
    padding: '8px 13px',
    cursor: 'pointer',
  },
  primary: { background: '#5e6ad2', borderColor: '#5e6ad2', color: '#fff' },
  danger: { color: '#ef4444' },
  message: (error: boolean): React.CSSProperties => ({
    margin: 0,
    fontSize: '13px',
    color: error ? '#ef4444' : '#22c55e',
  }),
} satisfies Record<string, React.CSSProperties | ((...args: never[]) => React.CSSProperties)>
