// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-tool-trivy", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const TRIVY_STATUS_CHANNEL = "/trivy-status";
const TRIVY_STATUS_GET = "get";
const TRIVY_STATUS_RECHECK = "recheck";

//#endregion
//#region client/styles.ts
const styles = {
	section: {
		display: "flex",
		flexDirection: "column",
		gap: "16px",
		width: "min(720px, 100%)"
	},
	heading: {
		margin: 0,
		fontSize: "20px",
		fontWeight: 650
	},
	intro: {
		margin: 0,
		opacity: .72,
		lineHeight: 1.5
	},
	card: {
		display: "flex",
		flexDirection: "column",
		gap: "14px",
		padding: "18px",
		border: "1px solid color-mix(in srgb, currentColor 16%, transparent)",
		borderRadius: "12px",
		background: "color-mix(in srgb, currentColor 3%, transparent)"
	},
	row: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: "12px"
	},
	title: {
		margin: 0,
		fontSize: "16px",
		fontWeight: 650
	},
	badge: {
		display: "inline-flex",
		alignItems: "center",
		gap: "7px",
		fontSize: "13px",
		opacity: .84
	},
	dot: (color) => ({
		width: "8px",
		height: "8px",
		borderRadius: "999px",
		background: color
	}),
	details: {
		display: "grid",
		gridTemplateColumns: "max-content minmax(0, 1fr)",
		gap: "7px 12px",
		fontSize: "13px"
	},
	key: { opacity: .62 },
	value: { overflowWrap: "anywhere" },
	hint: {
		margin: 0,
		fontSize: "13px",
		opacity: .72,
		lineHeight: 1.5
	},
	actions: {
		display: "flex",
		alignItems: "center",
		gap: "12px",
		flexWrap: "wrap"
	},
	button: {
		border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
		borderRadius: "8px",
		background: "color-mix(in srgb, currentColor 8%, transparent)",
		color: "inherit",
		font: "inherit",
		fontWeight: 600,
		padding: "8px 13px",
		cursor: "pointer"
	},
	link: {
		color: "inherit",
		fontSize: "13px",
		fontWeight: 600
	},
	error: {
		margin: 0,
		color: "#ef4444",
		fontSize: "13px"
	}
};

//#endregion
//#region client/settings.tsx
const INSTALL_URL = "https://trivy.dev/latest/getting-started/installation/";
function messageOf(error) {
	return error instanceof Error ? error.message : String(error);
}
function presentation(status, failure) {
	if (failure !== void 0) return {
		label: "Unavailable",
		color: "#ef4444"
	};
	if (status === void 0) return {
		label: "Checking…",
		color: "#94a3b8"
	};
	if (status.state === "ready") return {
		label: "Ready",
		color: "#22c55e"
	};
	if (status.state === "not-found") return {
		label: "Not found",
		color: "#ef4444"
	};
	if (status.state === "unsupported-version") return {
		label: "Unsupported version",
		color: "#f59e0b"
	};
	return {
		label: "Execution failed",
		color: "#ef4444"
	};
}
function formatCheckedAt(value) {
	if (typeof value !== "string") return void 0;
	const date = new Date(value);
	return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
}
function TrivySettingsSection({ rpc, subscribe }) {
	const [status, setStatus] = (0, react.useState)();
	const [busy, setBusy] = (0, react.useState)(false);
	const [failure, setFailure] = (0, react.useState)();
	const [revision, setRevision] = (0, react.useState)(0);
	(0, react.useEffect)(() => subscribe(() => setRevision((value) => value + 1)), [subscribe]);
	(0, react.useEffect)(() => {
		let active = true;
		setFailure(void 0);
		rpc.call(TRIVY_STATUS_CHANNEL, "get", {}).then((response) => {
			if (!active) return;
			if (!response.ok) {
				setFailure(response.error.message);
				return;
			}
			setStatus(response.value);
		}, (error) => {
			if (active) setFailure(messageOf(error));
		});
		return () => {
			active = false;
		};
	}, [rpc, revision]);
	const recheck = async () => {
		setBusy(true);
		setFailure(void 0);
		try {
			const response = await rpc.call(TRIVY_STATUS_CHANNEL, TRIVY_STATUS_RECHECK, {});
			if (!response.ok) {
				setFailure(response.error.message);
				return;
			}
			setStatus(response.value);
		} catch (error) {
			setFailure(messageOf(error));
		} finally {
			setBusy(false);
		}
	};
	const state = presentation(status, failure);
	const checkedAt = formatCheckedAt(status?.checkedAt);
	return /* @__PURE__ */ react.default.createElement("section", {
		style: styles.section,
		"aria-labelledby": "trivy-settings-title"
	}, /* @__PURE__ */ react.default.createElement("h2", {
		id: "trivy-settings-title",
		style: styles.heading
	}, "Trivy"), /* @__PURE__ */ react.default.createElement("p", { style: styles.intro }, "Check the pre-installed Trivy CLI used by vulnerability audits. DSH never installs or updates the executable."), /* @__PURE__ */ react.default.createElement("div", {
		style: styles.card,
		role: "group",
		"aria-labelledby": "trivy-card-title"
	}, /* @__PURE__ */ react.default.createElement("div", { style: styles.row }, /* @__PURE__ */ react.default.createElement("h3", {
		id: "trivy-card-title",
		style: styles.title
	}, "Trivy CLI"), /* @__PURE__ */ react.default.createElement("span", {
		style: styles.badge,
		role: "status"
	}, /* @__PURE__ */ react.default.createElement("span", {
		style: styles.dot(state.color),
		"aria-hidden": true
	}), state.label)), status === void 0 ? null : /* @__PURE__ */ react.default.createElement("div", { style: styles.details }, status.version === void 0 ? null : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("span", { style: styles.key }, "Version"), /* @__PURE__ */ react.default.createElement("span", { style: styles.value }, status.version)), status.path === void 0 ? null : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("span", { style: styles.key }, "Executable"), /* @__PURE__ */ react.default.createElement("span", { style: styles.value }, status.path)), /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("span", { style: styles.key }, "Required"), /* @__PURE__ */ react.default.createElement("span", { style: styles.value }, `Trivy ${status.minimumVersion}+`)), checkedAt === void 0 ? null : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("span", { style: styles.key }, "Last checked"), /* @__PURE__ */ react.default.createElement("span", { style: styles.value }, checkedAt))), status?.message === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", { style: styles.hint }, status.message), /* @__PURE__ */ react.default.createElement("p", { style: styles.hint }, "If Trivy works in a terminal but is not found here, DSH may have a different effective PATH. The first audit may download or update Trivy’s vulnerability database."), /* @__PURE__ */ react.default.createElement("div", { style: styles.actions }, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy,
		style: {
			...styles.button,
			opacity: busy ? .55 : 1
		},
		onClick: () => {
			recheck();
		}
	}, busy ? "Checking…" : "Recheck"), /* @__PURE__ */ react.default.createElement("a", {
		href: INSTALL_URL,
		target: "_blank",
		rel: "noreferrer",
		style: styles.link
	}, "Official installation instructions")), failure === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", {
		style: styles.error,
		role: "alert"
	}, failure)));
}

//#endregion
//#region client/registration.ts
const inject = ["slots", "connection"];
function apply(ctx) {
	const connection = ctx.get("connection");
	const subscribe = (listener) => ctx.on("connection/reset", listener);
	ctx.slots.inject("settings.section", () => ctx.slots.register({
		name: "settings.section",
		id: "trivy",
		order: 40,
		label: "Trivy",
		inject: () => ({
			rpc: connection.rpc,
			subscribe
		})
	}, TrivySettingsSection));
}

//#endregion
exports.INSTALL_URL = INSTALL_URL;
exports.STATUS_CHANNEL = TRIVY_STATUS_CHANNEL;
exports.STATUS_GET = TRIVY_STATUS_GET;
exports.STATUS_RECHECK = TRIVY_STATUS_RECHECK;
exports.TrivySettingsSection = TrivySettingsSection;
exports.apply = apply;
exports.inject = inject;
exports.presentation = presentation;
return module.exports; } });