// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-jev", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CHANNEL = "/jev-integration";

//#endregion
//#region client/rpc.ts
async function call(rpc, method, payload) {
	let result;
	try {
		result = await rpc.call(CHANNEL, method, payload);
	} catch {
		throw new Error("Jev settings request failed.");
	}
	if (!result?.ok) throw new Error(result?.error?.message || "Jev settings are unavailable.");
	return result.value;
}

//#endregion
//#region client/styles.ts
const css = `
      .dsh-jev { border: .5px solid var(--dsw-alias-border-l4); border-radius: 16px; background: var(--dsw-alias-bg-layer-3); color: var(--dsw-alias-label-primary); }
      .dsh-jev summary { cursor: pointer; padding: 14px 16px; font-size: 15px; font-weight: 600; }
      .dsh-jev[open] { background: var(--dsw-alias-bg-layer-2); }
      .dsh-jev__body { display: grid; gap: 12px; margin: 0 16px; padding: 12px 0 16px; border-top: .5px solid var(--dsw-alias-border-l2); font-size: 13px; line-height: 1.5; }
      .dsh-jev p { margin: 0; }
      .dsh-jev label { display: grid; gap: 6px; }
      .dsh-jev input { box-sizing: border-box; width: 100%; min-width: 0; height: 34px; padding: 0 10px; border: .5px solid var(--dsw-alias-border-l4); border-radius: 8px; font: inherit; color: inherit; background: var(--dsw-alias-bg-layer-3); }
      .dsh-jev button { justify-self: end; font: inherit; color: inherit; background: transparent; border: .5px solid var(--dsw-alias-border-l4); border-radius: 8px; padding: 5px 12px; cursor: pointer; }
      .dsh-jev button:disabled { opacity: .5; cursor: default; }
      .dsh-jev button:focus-visible, .dsh-jev input:focus-visible, .dsh-jev summary:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 2px; }
      .dsh-jev__hint { color: var(--dsw-alias-label-secondary); }
      .dsh-jev [role=alert] { color: var(--dsw-alias-label-error); }
    `;

//#endregion
//#region client/settings.tsx
function SettingsCard(props) {
	return props.view === "summary" ? /* @__PURE__ */ react.default.createElement("p", null, "Jev model and shared OpenRouter credential status.") : /* @__PURE__ */ react.default.createElement(SettingsForm, props);
}
function SettingsForm({ rpc, view }) {
	const [status, setStatus] = (0, react.useState)(null);
	const [model, setModel] = (0, react.useState)("");
	const [busy, setBusy] = (0, react.useState)(false);
	const [error, setError] = (0, react.useState)("");
	const [notice, setNotice] = (0, react.useState)("");
	const alive = (0, react.useRef)(false);
	const load = async (resetModel = false) => {
		try {
			const value = await call(rpc, "status", {});
			if (alive.current) {
				setStatus(value);
				if (resetModel) setModel(value.model);
			}
		} catch {
			if (alive.current) setError("Could not read Jev settings.");
		}
	};
	(0, react.useEffect)(() => {
		alive.current = true;
		const style = document.createElement("style");
		style.textContent = css;
		style.dataset.pluginCss = "jev/settings";
		document.head.appendChild(style);
		load(true);
		return () => {
			alive.current = false;
			style.remove();
		};
	}, [rpc]);
	const save = async () => {
		if (busy) return;
		setBusy(true);
		setError("");
		setNotice("");
		try {
			const value = await call(rpc, "configure", { model: model.trim() });
			if (alive.current) {
				setStatus(value);
				setModel(value.model);
				setNotice("Jev model saved. No evaluation was sent.");
			}
		} catch (failure) {
			if (alive.current) setError(failure instanceof Error ? failure.message : "Jev settings are unavailable.");
		} finally {
			if (alive.current) setBusy(false);
		}
	};
	return /* @__PURE__ */ react.default.createElement("details", {
		className: "dsh-jev",
		"aria-label": "Jev settings",
		open: view === "page"
	}, /* @__PURE__ */ react.default.createElement("summary", null, "Jev"), /* @__PURE__ */ react.default.createElement("div", { className: "dsh-jev__body" }, /* @__PURE__ */ react.default.createElement("p", { role: "status" }, status ? `Shared OpenRouter key: ${status.credential?.configured ? "Configured" : "Not configured"}` : "Checking shared OpenRouter key…"), /* @__PURE__ */ react.default.createElement("p", { className: "dsh-jev__hint" }, "Manage the shared key in the OpenRouter plugin card. Jev evaluates typed questions; it is not a chat model. Consumers choose when to send data through OpenRouter to TypeSafe."), /* @__PURE__ */ react.default.createElement("label", null, "Jev model ID", /* @__PURE__ */ react.default.createElement("input", {
		value: model,
		disabled: busy || !status,
		onChange: (event) => setModel(event.target.value),
		spellCheck: false
	})), /* @__PURE__ */ react.default.createElement("p", { className: "dsh-jev__hint" }, "Default: typesafe/jev-1.13. Use ~typesafe/jev-latest only if you want the release to change automatically."), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy || !status || !model.trim(),
		onClick: () => {
			save();
		}
	}, "Save Jev model"), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy,
		onClick: () => {
			load();
		}
	}, "Refresh credential status"), error || status?.credential?.error ? /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error || status?.credential.error) : null, notice ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, notice) : null));
}

//#endregion
//#region client/index.ts
function apply(ctx) {
	ctx.slots.inject("plugins.row.config", () => ctx.slots.register({
		name: "plugins.row.config",
		key: "@local/dsh-jev#local-jev",
		inject: () => ({ rpc: ctx.get("connection").rpc })
	}, SettingsCard));
}
var client_default = {
	inject: ["slots", "connection"],
	apply,
	SettingsCard
};

//#endregion
exports.SettingsCard = SettingsCard;
exports.apply = apply;
exports.default = client_default;
return module.exports.default; } });