// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-tool-imagegen", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region client/content.ts
function object(value) {
	return value !== null && typeof value === "object";
}
function isAttachment(value) {
	return object(value) && typeof value.attachmentId === "string" && typeof value.mediaType === "string" && [
		"image/png",
		"image/jpeg",
		"image/webp",
		"image/gif"
	].includes(value.mediaType) && typeof value.bytes === "number" && typeof value.width === "number" && typeof value.height === "number" && (value.name === void 0 || typeof value.name === "string");
}
function content(block) {
	if (!object(block) || block.kind !== "tool-result" || !Array.isArray(block.content)) return [];
	return block.content;
}
function imageBlocks(block) {
	return content(block).filter((item) => object(item) && item.type === "image" && isAttachment(item.attachment));
}
function textSummary(block) {
	const item = content(block).find((candidate) => object(candidate) && candidate.type === "text" && typeof candidate.text === "string");
	return object(item) && typeof item.text === "string" ? item.text : void 0;
}

//#endregion
//#region client/styles.ts
const styles = {
	card: {
		display: "flex",
		flexDirection: "column",
		gap: "10px",
		padding: "12px",
		border: "1px solid var(--dsw-alias-border-l2-darkmode-thin)",
		borderRadius: "12px",
		background: "var(--dsw-specific-input-major)"
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: "12px",
		fontSize: "13px",
		color: "var(--dsw-alias-label-secondary)"
	},
	title: {
		fontWeight: 650,
		color: "var(--dsw-alias-label-primary)"
	},
	gallery: {
		display: "flex",
		flexWrap: "wrap",
		gap: "10px"
	},
	frame: {
		display: "block",
		maxWidth: "min(100%, 560px)",
		padding: 0,
		border: 0,
		borderRadius: "10px",
		background: "transparent",
		cursor: "zoom-in",
		overflow: "hidden"
	},
	image: {
		display: "block",
		maxWidth: "100%",
		width: "auto",
		height: "auto",
		maxHeight: "420px",
		borderRadius: "10px",
		objectFit: "contain"
	},
	placeholder: {
		display: "grid",
		placeItems: "center",
		minWidth: "220px",
		minHeight: "140px",
		padding: "16px",
		borderRadius: "10px",
		background: "var(--dsw-alias-interactive-bg-hover)",
		color: "var(--dsw-alias-label-secondary)",
		fontSize: "13px"
	},
	error: {
		color: "var(--dsw-alias-label-error)",
		cursor: "pointer"
	},
	backdrop: {
		position: "fixed",
		inset: 0,
		zIndex: 1e3,
		display: "grid",
		placeItems: "center",
		padding: "40px",
		border: 0,
		background: "var(--dsw-alias-bg-mask-1)",
		backdropFilter: "var(--dsw-mask-blur)",
		cursor: "zoom-out"
	},
	fullImage: {
		display: "block",
		maxWidth: "min(100%, 1600px)",
		maxHeight: "calc(100vh - 80px)",
		borderRadius: "12px",
		objectFit: "contain",
		boxShadow: "var(--dsw-shadow-lv3)"
	}
};

//#endregion
//#region client/image-preview.tsx
function imageUrl(payload) {
	const bytes = Uint8Array.from(payload.data);
	const mediaType = payload.attachment?.mediaType || "application/octet-stream";
	if (typeof URL.createObjectURL !== "function") {
		let binary = "";
		for (const byte of bytes) binary += String.fromCharCode(byte);
		return {
			url: `data:${mediaType};base64,${btoa(binary)}`,
			disposable: false
		};
	}
	return {
		url: URL.createObjectURL(new Blob([bytes.buffer], { type: mediaType })),
		disposable: true
	};
}
function ImagePreview({ attachment, sessionId, readAttachment }) {
	const [src, setSrc] = (0, react.useState)();
	const [failure, setFailure] = (0, react.useState)();
	const [open, setOpen] = (0, react.useState)(false);
	const [attempt, setAttempt] = (0, react.useState)(0);
	(0, react.useEffect)(() => {
		let active = true;
		let loaded;
		setSrc(void 0);
		setFailure(void 0);
		Promise.resolve(readAttachment(sessionId, attachment)).then((payload) => {
			loaded = imageUrl(payload);
			if (!active) {
				if (loaded.disposable) URL.revokeObjectURL(loaded.url);
				return;
			}
			setSrc(loaded.url);
		}, (error) => {
			if (active) setFailure(error instanceof Error ? error.message : String(error));
		});
		return () => {
			active = false;
			if (loaded?.disposable) URL.revokeObjectURL(loaded.url);
		};
	}, [
		attachment.attachmentId,
		sessionId,
		readAttachment,
		attempt
	]);
	if (failure !== void 0) return /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: {
			...styles.placeholder,
			...styles.error
		},
		title: failure,
		onClick: () => setAttempt((value) => value + 1)
	}, "Image failed to load — retry");
	if (src === void 0) return /* @__PURE__ */ react.default.createElement("div", { style: styles.placeholder }, "Loading generated image…");
	const label = attachment.name || "Generated image";
	return /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: styles.frame,
		title: "View full image",
		"aria-label": `${label}, view full image`,
		onClick: () => setOpen(true)
	}, /* @__PURE__ */ react.default.createElement("img", {
		src,
		alt: label,
		style: styles.image,
		width: attachment.width,
		height: attachment.height
	})), open ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: styles.backdrop,
		"aria-label": "Close image preview",
		onClick: () => setOpen(false)
	}, /* @__PURE__ */ react.default.createElement("img", {
		src,
		alt: label,
		style: styles.fullImage,
		onClick: (event) => event.stopPropagation()
	})) : null);
}

//#endregion
//#region client/tool-view.tsx
function GenerateImageToolView({ block, sessionId, readAttachment }) {
	if (block.kind !== "tool-result") return /* @__PURE__ */ react.default.createElement("div", { style: styles.card }, /* @__PURE__ */ react.default.createElement("div", { style: styles.header }, /* @__PURE__ */ react.default.createElement("span", { style: styles.title }, "Generating image…")));
	const images = imageBlocks(block);
	const summary = textSummary(block);
	return /* @__PURE__ */ react.default.createElement("div", { style: styles.card }, /* @__PURE__ */ react.default.createElement("div", { style: styles.header }, /* @__PURE__ */ react.default.createElement("span", { style: styles.title }, block.isError ? "Image generation failed" : "Generated image"), images.length > 0 ? /* @__PURE__ */ react.default.createElement("span", null, images.length, " image", images.length === 1 ? "" : "s") : null), images.length > 0 ? /* @__PURE__ */ react.default.createElement("div", { style: styles.gallery }, images.map((image, index) => /* @__PURE__ */ react.default.createElement(ImagePreview, {
		key: `${image.attachment.attachmentId}:${index}`,
		attachment: image.attachment,
		sessionId,
		readAttachment
	}))) : /* @__PURE__ */ react.default.createElement("div", { style: block.isError ? {
		...styles.placeholder,
		...styles.error
	} : styles.placeholder }, summary || "No image returned."));
}

//#endregion
//#region client/index.ts
const inject = ["slots", "sessions"];
function apply(ctx) {
	const readAttachment = async (sessionId, attachment) => {
		const binding = ctx.sessions.binding(sessionId);
		if (binding?.session === void 0) throw new Error(`Image session is unavailable: ${sessionId}`);
		const result = await binding.session.readAttachment(attachment.attachmentId);
		if (!result.ok) throw new Error(`${result.error.code}: ${result.error.message}`);
		return result.value;
	};
	ctx.slots.inject("tool.call.toolview", () => ctx.slots.register({
		name: "tool.call.toolview",
		key: "generate_image",
		inject: () => ({ readAttachment })
	}, GenerateImageToolView));
}

//#endregion
exports.GenerateImageToolView = GenerateImageToolView;
exports.ImagePreview = ImagePreview;
exports.apply = apply;
exports.imageBlocks = imageBlocks;
exports.inject = inject;
exports.textSummary = textSummary;
return module.exports; } });