// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@wombat9000/dsh-session-recap", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region client/rpc.js
const CHANNEL = "/session-recap";
const ID = "wombat9000-session-recap";
function unwrap(result) {
	if (!result?.ok) throw new Error(result?.error?.message || "Session recap is unavailable.");
	return result.value;
}
function createSettingsReader(rpc) {
	let pending;
	function settings() {
		pending ??= rpc.call(CHANNEL, "settings", {}).then(unwrap).catch((error) => {
			pending = void 0;
			throw error;
		});
		return pending;
	}
	function invalidate() {
		pending = void 0;
	}
	return {
		settings,
		invalidate
	};
}

//#endregion
//#region client/return-tracker.js
function createActivityStore({ storage, now }) {
	const memory = /* @__PURE__ */ new Map();
	function key(config, sessionId) {
		return typeof config.storageScope === "string" && config.storageScope ? `${ID}:activity:${JSON.stringify([config.storageScope, sessionId])}` : void 0;
	}
	function read(key) {
		if (!key) return void 0;
		let raw = memory.get(key);
		try {
			raw = storage?.getItem(key) ?? raw;
		} catch {}
		const value = Number(raw);
		return raw != null && Number.isFinite(value) && value >= 0 && value <= now() ? value : void 0;
	}
	function touch(key) {
		if (!key) return;
		const value = String(now());
		memory.set(key, value);
		try {
			storage?.setItem(key, value);
		} catch {}
	}
	return {
		key,
		read,
		touch
	};
}
function createReturnTracker({ sessionId, document, window, rpc, settings, activityStore, now, state, publish, recap }) {
	const { key, read, touch } = activityStore;
	let alive = true;
	let active = false;
	let activityKey;
	let currentConfig;
	let checking = false;
	let retry;
	let generation = 0;
	function visible() {
		return document.visibilityState !== "hidden" && (typeof document.hasFocus !== "function" || document.hasFocus());
	}
	async function checkReturn(config) {
		if (checking) return;
		if (!config.autoRecap || !config.provider || !config.model) {
			touch(activityKey);
			return;
		}
		checking = true;
		const token = generation;
		const recapGeneration = state.generation;
		try {
			const activity = unwrap(await rpc.call(CHANNEL, "activity", { sessionId }));
			if (!alive || !active || token !== generation || recapGeneration !== state.generation || !visible()) return;
			if (!activity.ready || activity.running) {
				clearTimeout(retry);
				retry = setTimeout(() => {
					if (alive && active) checkReturn(currentConfig);
				}, 1e3);
				return;
			}
			clearTimeout(retry);
			const stored = read(activityKey);
			const fallback = activity.latestActivity;
			const previous = stored ?? (Number.isFinite(fallback) && fallback >= 0 && fallback <= now() ? fallback : void 0);
			touch(activityKey);
			const minutes = Number.isFinite(config.inactivityMinutes) && config.inactivityMinutes > 0 ? config.inactivityMinutes : 30;
			if (previous !== void 0 && now() - previous >= minutes * 6e4) recap(sessionId, true);
		} catch (error) {
			if (alive && active && token === generation && recapGeneration === state.generation) publish(state, {
				...state.value,
				error: error.message || String(error)
			});
		} finally {
			checking = false;
		}
	}
	async function enter() {
		if (!alive || active || !visible()) return;
		active = true;
		const token = ++generation;
		const recapGeneration = state.generation;
		try {
			const config = await settings();
			if (!alive || !active || token !== generation || recapGeneration !== state.generation || !visible()) return;
			activityKey = key(config, sessionId);
			currentConfig = config;
			checkReturn(config);
		} catch (error) {
			if (alive && active && recapGeneration === state.generation) publish(state, {
				...state.value,
				error: error.message || String(error)
			});
		}
	}
	function leave() {
		if (!active) return;
		clearTimeout(retry);
		if (read(activityKey) !== void 0) touch(activityKey);
		active = false;
		generation++;
	}
	function visibility() {
		if (visible()) enter();
		else leave();
	}
	function activity() {
		if (!active || !visible() || !currentConfig) return;
		settings().then((config) => {
			if (alive && active && visible()) {
				currentConfig = config;
				checkReturn(config);
			}
		}, () => {
			touch(activityKey);
		});
	}
	const handlers = [
		[
			document,
			"visibilitychange",
			visibility
		],
		[
			window,
			"focus",
			enter
		],
		[
			window,
			"blur",
			leave
		],
		[
			window,
			"pagehide",
			leave
		],
		[
			document,
			"pointerdown",
			activity
		],
		[
			document,
			"keydown",
			activity
		]
	];
	for (const [target, event, handler] of handlers) target.addEventListener(event, handler);
	enter();
	return {
		leave,
		deactivate() {
			alive = false;
		},
		removeHandlers() {
			for (const [target, event, handler] of handlers) target.removeEventListener(event, handler);
		}
	};
}

//#endregion
//#region client/controller.js
function createController({ rpc, storage, now = Date.now }) {
	const states = /* @__PURE__ */ new Map();
	const settingsReader = createSettingsReader(rpc);
	const { settings } = settingsReader;
	const activityStore = createActivityStore({
		storage,
		now
	});
	function state(sessionId) {
		if (!states.has(sessionId)) states.set(sessionId, {
			value: {},
			listeners: /* @__PURE__ */ new Set(),
			pending: null,
			generation: 0
		});
		return states.get(sessionId);
	}
	function publish(session, value) {
		session.value = value;
		for (const listener of session.listeners) listener(value);
	}
	function requestOpening(session) {
		publish(session, {
			...session.value,
			openOnReady: true
		});
	}
	function beginRecap(session, automatic) {
		publish(session, {
			...session.value,
			busy: true,
			error: void 0,
			unread: false,
			open: false,
			openOnReady: !automatic
		});
	}
	function completeRecap(session, result) {
		const open = session.value.openOnReady === true;
		publish(session, {
			busy: false,
			recap: result.recap,
			selection: result.selection,
			open,
			unread: !open,
			openOnReady: false
		});
	}
	function failRecap(session, error) {
		publish(session, {
			...session.value,
			busy: false,
			open: session.value.openOnReady === true,
			openOnReady: false,
			error: error.message || String(error)
		});
	}
	async function recap(sessionId, automatic = false) {
		const session = state(sessionId);
		if (session.pending) {
			if (!automatic) requestOpening(session);
			return session.pending;
		}
		const generation = session.generation;
		beginRecap(session, automatic);
		const pending = Promise.resolve().then(() => rpc.call(CHANNEL, "recap", {
			sessionId,
			automatic
		})).then(unwrap).then((result) => {
			if (generation !== session.generation) return;
			if (result.sessionId !== sessionId) throw new Error("Session recap returned a different session.");
			completeRecap(session, result);
		}).catch((error) => {
			if (generation === session.generation) failRecap(session, error);
		}).finally(() => {
			if (session.pending === pending) session.pending = null;
		});
		session.pending = pending;
		return pending;
	}
	function mount(sessionId, { document, window }, listener) {
		const session = state(sessionId);
		session.listeners.add(listener);
		listener(session.value);
		const tracker = createReturnTracker({
			sessionId,
			document,
			window,
			rpc,
			settings,
			activityStore,
			now,
			state: session,
			publish,
			recap
		});
		return () => {
			tracker.leave();
			tracker.deactivate();
			session.listeners.delete(listener);
			tracker.removeHandlers();
		};
	}
	function discard(sessionId) {
		const session = states.get(sessionId);
		if (!session) return;
		session.generation++;
		session.pending = null;
		publish(session, {});
	}
	function click(sessionId) {
		const session = state(sessionId);
		if (session.value.busy) {
			requestOpening(session);
			return session.pending;
		}
		if (session.value.recap && !session.value.error) {
			publish(session, {
				...session.value,
				open: !session.value.open,
				unread: false
			});
			return;
		}
		return recap(sessionId);
	}
	function observeSession(sessionId, observation) {
		const session = state(sessionId);
		const previous = session.observation;
		if (!observation.ready) return;
		if (previous && (!previous.running && observation.running || observation.latestTurn !== void 0 && (previous.latestTurn === void 0 || observation.latestTurn > previous.latestTurn))) discard(sessionId);
		session.observation = observation;
	}
	function humanMessageSent(sessionId) {
		discard(sessionId);
		settings().then((config) => {
			activityStore.touch(activityStore.key(config, sessionId));
		}, () => {});
	}
	return {
		mount,
		recap,
		click,
		turnStarted: discard,
		observeSession,
		getSnapshot(sessionId) {
			return state(sessionId).value;
		},
		subscribe(sessionId, listener) {
			const session = state(sessionId);
			session.listeners.add(listener);
			return () => session.listeners.delete(listener);
		},
		invalidateSettings: settingsReader.invalidate,
		humanMessageSent
	};
}

//#endregion
//#region client/styles.js
const recapStyles = `
  .dsh-session-recap-action { appearance: none; display: inline-flex; align-items: center; justify-content: center; gap: 6px; flex: none; font: inherit; font-size: 13px; line-height: 20px; color: var(--dsw-alias-label-secondary, inherit); background: transparent; border: 0; border-radius: 8px; padding: 5px 8px; cursor: pointer; }
  .dsh-session-recap-action:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover, #8882); color: var(--dsw-alias-label-primary, inherit); }
  .dsh-session-recap-action:focus-visible, .dsh-session-recap-card__body:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary, #6b9cff); outline-offset: 2px; }
  .dsh-session-recap-action { position: relative; overflow: hidden; width: 30px; height: 30px; padding: 6px; }
  .dsh-session-recap-action[data-unread="true"] { color: var(--dsw-alias-brand-primary, #6b9cff); }
  .dsh-session-recap-action[data-unread="true"] .dsh-session-recap-action__icon { filter: drop-shadow(0 0 4px currentColor); }
  .dsh-session-recap-action[data-unread="true"]::before { content: ''; position: absolute; top: 3px; right: 3px; width: 4px; height: 4px; border-radius: 50%; background: currentColor; }
  .dsh-session-recap-action[data-open="true"] { color: var(--dsw-alias-brand-primary, #6b9cff); background: var(--dsw-alias-interactive-bg-hover, #8882); }
  .dsh-session-recap-action__warning { position: absolute; top: 0; right: 2px; font-size: 11px; font-weight: 700; color: var(--dsw-alias-label-error, #d55); }
  .dsh-session-recap-action[data-busy="true"] { color: var(--dsw-alias-brand-primary, #6b9cff); }
  .dsh-session-recap-action[data-busy="true"]::after { content: ''; position: absolute; inset: 0; pointer-events: none; background: linear-gradient(110deg, transparent 25%, currentColor 50%, transparent 75%); opacity: .25; transform: translateX(-140%); animation: dsh-session-recap-shimmer 1.8s linear infinite; }
  @keyframes dsh-session-recap-shimmer { to { transform: translateX(140%); } }
  @media (prefers-reduced-motion: reduce) { .dsh-session-recap-action[data-busy="true"]::after { animation: none; transform: none; background: none; opacity: 1; border-bottom: 2px solid currentColor; } }
  .dsh-session-recap-card { box-sizing: border-box; width: calc(100% - 2 * var(--dsh-composer-side-clearance, 16px) - 32px); max-width: var(--dsh-chat-content-width, 680px); min-width: 0; margin: 0 auto 8px; padding: 12px 16px; border: .5px solid var(--dsw-alias-border-l2, #8883); border-radius: 16px; background: var(--dsw-alias-bg-layer-2, #8881); color: var(--dsw-alias-label-primary, inherit); font-size: 13px; line-height: 1.6; }
  .dsh-session-recap-card__body { max-height: min(240px, 30vh); overflow-y: auto; white-space: pre-wrap; overflow-wrap: anywhere; }
  .dsh-session-recap-card__headline { margin: 0 0 6px; font: inherit; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .dsh-session-recap-card__diagnostics { margin-top: 8px; font-size: 12px; white-space: normal; }
  .dsh-session-recap-card__diagnostics summary { cursor: pointer; }
  .dsh-session-recap-card__diagnostics summary:focus-visible, .dsh-session-recap-card__diagnostics button:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary, #6b9cff); outline-offset: 2px; }
  .dsh-session-recap-card__diagnostics p { margin: 6px 0; }
  .dsh-session-recap-card__diagnostics pre { white-space: pre-wrap; overflow-wrap: anywhere; font-size: 11px; }
  .dsh-session-recap-card__diagnostics button { font: inherit; color: inherit; background: transparent; border: 1px solid var(--dsw-alias-border-l2, #8885); border-radius: 6px; padding: 4px 8px; margin-top: 8px; cursor: pointer; }
  .dsh-session-recap-card__table-wrap { max-width: 100%; overflow-x: auto; margin: 8px 0; }
  .dsh-session-recap-card__table-wrap table { border-collapse: collapse; min-width: 480px; width: 100%; }
  .dsh-session-recap-card__table-wrap th, .dsh-session-recap-card__table-wrap td { padding: 4px 6px; text-align: left; vertical-align: top; border-bottom: 1px solid var(--dsw-alias-border-l2, #8883); }
  .dsh-session-recap-card__body--cards { max-height: min(420px, 45vh); }
  .dsh-session-recap-card__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 180px), 1fr)); gap: 8px; margin: 0; padding: 0; list-style: none; }
  .dsh-session-recap-card__tile { min-width: 0; padding: 10px 12px; border: .5px solid var(--dsw-alias-border-l2, #8883); border-radius: 10px; background: var(--dsw-alias-bg-layer-3, #8881); }
  .dsh-session-recap-card__title { display: flex; align-items: center; gap: 6px; margin: 0 0 4px; font: inherit; font-size: 12px; font-weight: 500; color: var(--dsw-alias-label-secondary, inherit); }
  .dsh-session-recap-card__icon { flex: none; color: color-mix(in srgb, var(--recap-accent) 75%, var(--dsw-alias-label-primary, currentColor)); }
  .dsh-session-recap-card__text { margin: 0; }
  .dsh-session-recap-card__caption { margin: 6px 0 0; font-size: 11px; color: var(--dsw-alias-label-tertiary, inherit); }
  .dsh-session-recap-card__list { margin: 0; padding-left: 18px; }
  .dsh-session-recap-card__row + .dsh-session-recap-card__row { margin-top: 4px; }
  .dsh-session-recap-card__loading { margin: 0; color: var(--dsw-alias-label-secondary, inherit); }
  .dsh-session-recap-card__error { margin: 4px 0; color: var(--dsw-alias-label-error, #d55); overflow-wrap: anywhere; }
  @media (max-width: 600px) { .dsh-session-recap-card { padding: 10px 12px; border-radius: 12px; } }
`;
const settingsStyles = `
  .dsh-session-recap-settings { border: .5px solid var(--dsw-alias-border-l4); background: var(--dsw-alias-bg-layer-3); border-radius: 16px; list-style: none; transition: border-color .16s, background .16s; }
  .dsh-session-recap-settings:hover { border-color: var(--dsw-alias-label-dimmed); }
  .dsh-session-recap-settings[data-open="true"] { background: var(--dsw-alias-bg-layer-2); border-color: var(--dsw-alias-label-dimmed); }
  .dsh-session-recap-settings__header { appearance: none; width: 100%; font: inherit; color: inherit; text-align: left; cursor: pointer; background: transparent; border: 0; border-radius: 12px; display: flex; align-items: center; gap: 12px; padding: 14px 16px; }
  .dsh-session-recap-settings__header:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px; }
  .dsh-session-recap-settings__heading { display: flex; flex-direction: column; flex: 1; gap: 4px; min-width: 0; }
  .dsh-session-recap-settings__name { color: var(--dsw-alias-label-primary); font-size: 15px; font-weight: 600; line-height: 1.4; }
  .dsh-session-recap-settings__description { color: var(--dsw-alias-label-tertiary); font-size: 13px; line-height: 1.5; }
  .dsh-session-recap-settings__chevron { color: var(--dsw-alias-label-tertiary); flex: none; transition: transform .16s; }
  .dsh-session-recap-settings[data-open="true"] .dsh-session-recap-settings__chevron { transform: rotate(180deg); }
  .dsh-session-recap-settings__body { border-top: .5px solid var(--dsw-alias-border-l2); margin: 0 16px; padding: 12px 0 8px; display: grid; gap: 12px; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 1.5; }
  .dsh-session-recap-settings__row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; font-size: 13px; font-weight: 500; }
  .dsh-session-recap-settings__row input:not([type="checkbox"]), .dsh-session-recap-settings__row select { box-sizing: border-box; min-width: 0; max-width: 100%; border: .5px solid var(--dsw-alias-border-l4); background: var(--dsw-alias-bg-layer-3); height: 34px; font: inherit; font-weight: 400; color: var(--dsw-alias-label-primary); border-radius: 8px; padding: 0 12px; }
  .dsh-session-recap-settings__row input:focus-visible, .dsh-session-recap-settings__row select:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 2px; }
  .dsh-session-recap-settings__row input:disabled, .dsh-session-recap-settings__row select:disabled { color: var(--dsw-alias-label-tertiary); cursor: default; }
  .dsh-session-recap-settings__hint { color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 1.5; }
  .dsh-session-recap-settings__footer { border-top: .5px solid var(--dsw-alias-border-l2); padding: 12px 0 4px; display: flex; justify-content: flex-end; }
  .dsh-session-recap-settings__save { appearance: none; font: inherit; cursor: pointer; border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px; padding: 5px 14px; font-size: 13px; line-height: 1.5; background: transparent; color: var(--dsw-alias-label-primary); }
  .dsh-session-recap-settings__save:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); }
  .dsh-session-recap-settings__save:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 2px; }
  .dsh-session-recap-settings__save:disabled { color: var(--dsw-alias-label-tertiary); cursor: default; }
  .dsh-session-recap-settings__body [role="alert"] { margin: 0; color: var(--dsw-alias-label-error); }
  .dsh-session-recap-settings__body [role="status"] { margin: 0; color: var(--dsw-alias-label-secondary); }
  @media (prefers-reduced-motion: reduce) { .dsh-session-recap-settings, .dsh-session-recap-settings__chevron { transition: none; } }
`;
function useRecapStyles(enabled = true) {
	(0, react.useEffect)(() => {
		if (!enabled || typeof document === "undefined") return;
		const style = document.createElement("style");
		style.dataset.pluginCss = `${ID}/recap`;
		style.textContent = recapStyles;
		document.head.appendChild(style);
		return () => style.remove();
	}, [enabled]);
}

//#endregion
//#region client/components/RecapActionButton.jsx
function recapActionLabel({ busy, error, recap, open }) {
	if (busy) return "Open recap when ready";
	if (error) return "Retry recap";
	if (recap) return open ? "Hide recap" : "Show recap";
	return "Generate recap";
}
function RecapActionButton({ busy, error, recap, open, unread, onClick }) {
	const label = recapActionLabel({
		busy,
		error,
		recap,
		open
	});
	return /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		className: "dsh-session-recap-action",
		"data-busy": !!busy,
		"data-unread": !!unread,
		"data-open": !!open,
		title: busy ? "Generating recap…" : error ? `Retry recap: ${error}` : label,
		"aria-label": label,
		"aria-expanded": !!open,
		onClick
	}, /* @__PURE__ */ react.default.createElement("svg", {
		className: "dsh-session-recap-action__icon",
		"aria-hidden": true,
		focusable: "false",
		width: 16,
		height: 16,
		viewBox: "0 0 24 24",
		fill: "none",
		stroke: "currentColor",
		strokeWidth: 1.5,
		strokeLinecap: "round",
		strokeLinejoin: "round"
	}, /* @__PURE__ */ react.default.createElement("rect", {
		x: 5,
		y: 3,
		width: 14,
		height: 18,
		rx: 3
	}), /* @__PURE__ */ react.default.createElement("path", { d: "M9 8h6M9 12h6M9 16h3" })), error ? /* @__PURE__ */ react.default.createElement("span", {
		className: "dsh-session-recap-action__warning",
		"aria-hidden": true
	}, "!") : null);
}

//#endregion
//#region client/cards.js
const CARD_LABELS = Object.freeze({
	direction: {
		title: "Direction",
		path: "m5 19 4-10 10-4-4 10-10 4Zm4-10 6 6",
		accent: "#628bc4"
	},
	decision: {
		title: "Decision",
		path: "m5 12 4 4L19 6M5 21h14",
		accent: "#548d78"
	},
	insight: {
		title: "Key insight",
		path: "M9 18h6m-5 3h4M8 14a6 6 0 1 1 8 0l-1 2H9l-1-2Z",
		accent: "#b18a48"
	},
	question: {
		title: "Open question",
		path: "M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 4h.01M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z",
		accent: "#9680b8"
	},
	next_step: {
		title: "Next step",
		path: "M4 12h16m-6-6 6 6-6 6",
		accent: "#588e9e"
	},
	paused: {
		title: "Where we paused",
		path: "M8 5v14M16 5v14",
		accent: "#a38273"
	}
});
function visualCards(recap) {
	const seen = /* @__PURE__ */ new Set();
	return (Array.isArray(recap?.cards) ? recap.cards : []).filter((card) => {
		if (!card || typeof card.label !== "string" || !Object.hasOwn(CARD_LABELS, card.label) || typeof card.text !== "string" || !card.text.trim() || seen.has(card.label)) return false;
		seen.add(card.label);
		return true;
	}).slice(0, 3);
}

//#endregion
//#region client/components/SelectionDetails.jsx
function SelectionTable({ categories, thresholds }) {
	const format = (value) => typeof value === "number" && Number.isFinite(value) ? String(Number(value.toFixed(3))) : "—";
	const reasons = {
		support: `support below ${thresholds.support}`,
		usefulness: `usefulness below ${thresholds.usefulness}`,
		confidence: `confidence below ${thresholds.confidence}`,
		"invalid-answer": "answer incomplete or invalid",
		"ranked-out": `outside the top ${thresholds.maxCards}`
	};
	return /* @__PURE__ */ react.default.createElement("div", {
		className: "dsh-session-recap-card__table-wrap",
		tabIndex: 0,
		"aria-label": "Category selection scores"
	}, /* @__PURE__ */ react.default.createElement("table", null, /* @__PURE__ */ react.default.createElement("thead", null, /* @__PURE__ */ react.default.createElement("tr", null, [
		"Category",
		"Support",
		"Usefulness",
		"Confidence",
		"Outcome"
	].map((title) => /* @__PURE__ */ react.default.createElement("th", {
		key: title,
		scope: "col"
	}, title)))), /* @__PURE__ */ react.default.createElement("tbody", null, categories.map((row) => {
		const outcome = row.selected ? "Selected" : row.reasons.length ? `Not selected: ${row.reasons.map((reason) => reasons[reason] ?? "not evaluated").join("; ")}` : "Not evaluated";
		return /* @__PURE__ */ react.default.createElement("tr", { key: row.label }, /* @__PURE__ */ react.default.createElement("th", { scope: "row" }, CARD_LABELS[row.label]?.title ?? row.label), /* @__PURE__ */ react.default.createElement("td", null, format(row.support)), /* @__PURE__ */ react.default.createElement("td", null, format(row.usefulness)), /* @__PURE__ */ react.default.createElement("td", null, format(row.confidence)), /* @__PURE__ */ react.default.createElement("td", null, outcome));
	}))));
}
function SelectionDetailsView({ diagnostics, json, copyStatus, onCopy }) {
	const thresholds = diagnostics.thresholds;
	return /* @__PURE__ */ react.default.createElement("details", { className: "dsh-session-recap-card__diagnostics" }, /* @__PURE__ */ react.default.createElement("summary", null, "Selection details"), /* @__PURE__ */ react.default.createElement("p", null, "From this recap request. Opening or copying these details makes no model call. No conversation text or credentials are included."), /* @__PURE__ */ react.default.createElement("p", null, `Model: ${diagnostics.model ?? "Unavailable"} · Questions: ${diagnostics.questionSetVersion}`), /* @__PURE__ */ react.default.createElement("p", null, `Thresholds: support ≥ ${thresholds.support}; usefulness ≥ ${thresholds.usefulness}; confidence ≥ ${thresholds.confidence}. Up to ${thresholds.maxCards} cards.`), diagnostics.status === "unavailable" ? /* @__PURE__ */ react.default.createElement("p", null, "Jev evaluation was unavailable; no category scores were retained.") : /* @__PURE__ */ react.default.createElement("p", null, "Table values are rounded to three decimals. JSON keeps full precision. Selected categories go to the writer, which can still omit a card."), /* @__PURE__ */ react.default.createElement(SelectionTable, {
		categories: diagnostics.categories,
		thresholds
	}), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		onClick: onCopy
	}, "Copy diagnostics JSON"), copyStatus ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, copyStatus) : null, /* @__PURE__ */ react.default.createElement("details", null, /* @__PURE__ */ react.default.createElement("summary", null, "Questions, probabilities, and JSON"), /* @__PURE__ */ react.default.createElement("p", null, "Question wording and rubric levels for this request, with full-precision values when evaluation succeeded:"), /* @__PURE__ */ react.default.createElement("pre", {
		tabIndex: 0,
		"aria-label": "Selection diagnostics JSON"
	}, json)));
}
function SelectionDetails({ diagnostics }) {
	const [copyStatus, setCopyStatus] = react.default.useState("");
	react.default.useEffect(() => {
		setCopyStatus("");
	}, [diagnostics]);
	if (diagnostics?.version !== 1) return null;
	const json = JSON.stringify(diagnostics, null, 2);
	async function copy() {
		try {
			await navigator.clipboard.writeText(json);
			setCopyStatus("Diagnostics copied.");
		} catch {
			setCopyStatus("Clipboard unavailable. Expand the JSON and copy it manually.");
		}
	}
	return /* @__PURE__ */ react.default.createElement(SelectionDetailsView, {
		diagnostics,
		json,
		copyStatus,
		onCopy: copy
	});
}

//#endregion
//#region client/components/RecapPanel.jsx
function RecapTile({ card }) {
	const label = CARD_LABELS[card.label];
	return /* @__PURE__ */ react.default.createElement("li", {
		"data-recap-card": card.label,
		className: "dsh-session-recap-card__tile"
	}, /* @__PURE__ */ react.default.createElement("h3", { className: "dsh-session-recap-card__title" }, /* @__PURE__ */ react.default.createElement("svg", {
		className: "dsh-session-recap-card__icon",
		style: { "--recap-accent": label.accent },
		"aria-hidden": true,
		focusable: "false",
		width: 14,
		height: 14,
		viewBox: "0 0 24 24",
		fill: "none",
		stroke: "currentColor",
		strokeWidth: 1.5,
		strokeLinecap: "round",
		strokeLinejoin: "round"
	}, /* @__PURE__ */ react.default.createElement("path", { d: label.path })), label.title), /* @__PURE__ */ react.default.createElement("p", { className: "dsh-session-recap-card__text" }, card.text.slice(0, 180)));
}
function RecapBulletList({ bullets }) {
	const items = (Array.isArray(bullets) ? bullets : []).filter((bullet) => typeof bullet === "string");
	return /* @__PURE__ */ react.default.createElement("ul", { className: "dsh-session-recap-card__list" }, items.map((bullet, index) => /* @__PURE__ */ react.default.createElement("li", {
		key: index,
		className: "dsh-session-recap-card__row"
	}, bullet)));
}
function selectionCaption(selection) {
	if (selection?.mode !== "standard") return null;
	if (selection.reason === "unavailable") return "Jev unavailable";
	if (selection.reason === "no-labels") return "No suitable categories";
	return null;
}
function RecapPanel({ busy, error, recap, selection, diagnosticsKey }) {
	const cards = visualCards(recap);
	const caption = selectionCaption(selection);
	return /* @__PURE__ */ react.default.createElement("aside", {
		"aria-label": "Session recap",
		className: "dsh-session-recap-card"
	}, busy ? /* @__PURE__ */ react.default.createElement("p", {
		role: "status",
		className: "dsh-session-recap-card__loading"
	}, "Generating recap…") : null, error ? /* @__PURE__ */ react.default.createElement("p", {
		role: "alert",
		className: "dsh-session-recap-card__error"
	}, error) : null, recap ? /* @__PURE__ */ react.default.createElement("div", {
		tabIndex: 0,
		"aria-label": "Recap content",
		className: `dsh-session-recap-card__body${cards.length ? " dsh-session-recap-card__body--cards" : ""}`
	}, /* @__PURE__ */ react.default.createElement("div", { role: busy ? void 0 : "status" }, typeof recap.headline === "string" && recap.headline.trim() ? /* @__PURE__ */ react.default.createElement("h2", {
		className: "dsh-session-recap-card__headline",
		title: recap.headline
	}, recap.headline) : null, cards.length ? /* @__PURE__ */ react.default.createElement("ul", {
		role: "list",
		"aria-label": "Recap cards",
		className: "dsh-session-recap-card__grid"
	}, cards.map((card) => /* @__PURE__ */ react.default.createElement(RecapTile, {
		key: card.label,
		card
	}))) : /* @__PURE__ */ react.default.createElement(RecapBulletList, { bullets: recap.bullets }), caption ? /* @__PURE__ */ react.default.createElement("p", { className: "dsh-session-recap-card__caption" }, caption) : null), selection?.diagnostics ? /* @__PURE__ */ react.default.createElement(SelectionDetails, {
		key: diagnosticsKey,
		diagnostics: selection.diagnostics
	}) : null) : null);
}

//#endregion
//#region client/containers/recap.jsx
function useRecapState(controller, sessionId) {
	return react.default.useSyncExternalStore(react.default.useCallback((listener) => controller.subscribe(sessionId, listener), [controller, sessionId]), react.default.useCallback(() => controller.getSnapshot(sessionId), [controller, sessionId]));
}
function latestClosingMessage(chat) {
	const turn = chat.timeline.turnOrder.at(-1);
	if (turn === void 0 || chat.timeline.turns.get(turn)?.status !== "closed") return void 0;
	for (const key of chat.locations.getTurn(turn)) {
		const node = chat.nodes.get(key);
		if (node?.kind === "turn-tail" && node.data.closing?.status === "settled") return node.data.closing.finalNode.messageId;
	}
}
function RecapAction({ sessionId, messageId, useSession, useChat, controller }) {
	const blank = useSession((session) => session.blank) !== false;
	const closingMessageId = useChat(latestClosingMessage);
	const state = useRecapState(controller, sessionId);
	const visible = !blank && !!messageId && messageId === closingMessageId;
	useRecapStyles(visible);
	if (!visible) return null;
	return /* @__PURE__ */ react.default.createElement(RecapActionButton, {
		busy: state.busy,
		error: state.error,
		recap: state.recap,
		open: state.open,
		unread: state.unread,
		onClick: () => {
			controller.click(sessionId);
		}
	});
}
function RecapCard({ sessionId, useSession, useConversation, useChat, controller }) {
	const state = useRecapState(controller, sessionId);
	const blank = useSession((session) => session.blank) !== false;
	const ready = useSession((session) => session.openState === "open");
	const running = useSession((session) => session.running);
	const hasChat = useConversation((conversation) => conversation.activeTargets.has("chat"));
	const latestTurn = useChat((chat) => chat.timeline.turnOrder.at(-1));
	useRecapStyles();
	react.default.useEffect(() => {
		controller.observeSession(sessionId, {
			ready: ready && (hasChat || blank),
			running,
			latestTurn
		});
	}, [
		controller,
		sessionId,
		ready,
		hasChat,
		blank,
		running,
		latestTurn
	]);
	react.default.useEffect(() => {
		if (!blank) return controller.mount(sessionId, {
			document,
			window
		}, () => {});
	}, [
		controller,
		sessionId,
		blank
	]);
	if (blank || running || !state.open || !(state.error || state.recap)) return null;
	return /* @__PURE__ */ react.default.createElement(RecapPanel, {
		busy: state.busy,
		error: state.error,
		recap: state.recap,
		selection: state.selection,
		diagnosticsKey: sessionId
	});
}

//#endregion
//#region client/components/SettingsForm.jsx
function SettingsRow({ label, children }) {
	return /* @__PURE__ */ react.default.createElement("label", { className: "dsh-session-recap-settings__row" }, label, children);
}
function SettingsForm({ open, draft, providers, error, notice, busy, onToggle, onChange, onChooseModel, onSave }) {
	return /* @__PURE__ */ react.default.createElement("section", {
		"aria-label": "Session recap settings",
		className: "dsh-session-recap-settings",
		"data-open": open
	}, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		"aria-expanded": open,
		"aria-label": `${open ? "Collapse" : "Expand"}: Session recap`,
		onClick: onToggle,
		className: "dsh-session-recap-settings__header"
	}, /* @__PURE__ */ react.default.createElement("span", { className: "dsh-session-recap-settings__heading" }, /* @__PURE__ */ react.default.createElement("span", { className: "dsh-session-recap-settings__name" }, "Session recap"), /* @__PURE__ */ react.default.createElement("span", { className: "dsh-session-recap-settings__description" }, "Show a short recap above the composer.")), /* @__PURE__ */ react.default.createElement("svg", {
		className: "dsh-session-recap-settings__chevron",
		"aria-hidden": true,
		focusable: "false",
		width: 14,
		height: 14,
		viewBox: "0 0 14 14",
		fill: "none"
	}, /* @__PURE__ */ react.default.createElement("path", {
		d: "M3.5 5.25 7 8.75l3.5-3.5",
		stroke: "currentColor",
		strokeWidth: 1.2,
		strokeLinecap: "round",
		strokeLinejoin: "round"
	}))), open ? /* @__PURE__ */ react.default.createElement("div", { className: "dsh-session-recap-settings__body" }, /* @__PURE__ */ react.default.createElement("p", { style: { margin: 0 } }, "Recaps use the selected model and never change the transcript."), draft ? /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Automatic recap on return" }, /* @__PURE__ */ react.default.createElement("input", {
		type: "checkbox",
		checked: draft.autoRecap,
		disabled: busy,
		onChange: (event) => onChange("autoRecap", event.target.checked)
	})), /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Use Jev to choose recap cards" }, /* @__PURE__ */ react.default.createElement("input", {
		type: "checkbox",
		checked: draft.useJev === true,
		disabled: busy,
		"aria-describedby": `${ID}-jev-privacy`,
		onChange: (event) => onChange("useJev", event.target.checked)
	})), /* @__PURE__ */ react.default.createElement("small", {
		id: `${ID}-jev-privacy`,
		className: "dsh-session-recap-settings__hint"
	}, "Optional; requires the Jev plugin. Sends the same bounded history through OpenRouter to TypeSafe to choose recap categories. Manage the shared key and model in the OpenRouter and Jev settings cards; no new key is needed."), /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Inactivity (minutes)" }, /* @__PURE__ */ react.default.createElement("input", {
		type: "number",
		min: 1,
		value: draft.inactivityMinutes,
		disabled: busy,
		onChange: (event) => onChange("inactivityMinutes", event.target.value)
	})), /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Available models" }, /* @__PURE__ */ react.default.createElement("select", {
		value: "",
		disabled: busy || providers.length === 0,
		onChange: onChooseModel
	}, /* @__PURE__ */ react.default.createElement("option", { value: "" }, "Choose a model…"), providers.map((provider) => /* @__PURE__ */ react.default.createElement("optgroup", {
		key: provider.id,
		label: provider.name || provider.id
	}, provider.models.map((model) => /* @__PURE__ */ react.default.createElement("option", {
		key: model.id,
		value: JSON.stringify([provider.id, model.id])
	}, model.name || model.id)))))), /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Provider ID" }, /* @__PURE__ */ react.default.createElement("input", {
		value: draft.provider || "",
		disabled: busy,
		onChange: (event) => onChange("provider", event.target.value)
	})), /* @__PURE__ */ react.default.createElement(SettingsRow, { label: "Model ID" }, /* @__PURE__ */ react.default.createElement("input", {
		value: draft.model || "",
		disabled: busy,
		onChange: (event) => onChange("model", event.target.value)
	})), /* @__PURE__ */ react.default.createElement("small", { className: "dsh-session-recap-settings__hint" }, "The catalog is advisory. You can enter an exact provider and model route. Saving validates the route without generating a recap."), /* @__PURE__ */ react.default.createElement("div", { className: "dsh-session-recap-settings__footer" }, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		className: "dsh-session-recap-settings__save",
		disabled: busy,
		onClick: onSave
	}, busy ? "Saving…" : "Save"))) : /* @__PURE__ */ react.default.createElement("span", null, "Loading settings…"), error ? /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error) : null, notice ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, notice) : null) : null);
}

//#endregion
//#region client/containers/SettingsCard.jsx
function SettingsCard({ rpc, controller }) {
	const [open, setOpen] = react.default.useState(false);
	const [draft, setDraft] = react.default.useState(null);
	const [providers, setProviders] = react.default.useState([]);
	const [error, setError] = react.default.useState("");
	const [notice, setNotice] = react.default.useState("");
	const [busy, setBusy] = react.default.useState(false);
	react.default.useEffect(() => {
		let alive = true;
		const style = typeof document === "undefined" ? null : document.createElement("style");
		if (style) {
			style.dataset.pluginCss = `${ID}/settings`;
			style.textContent = settingsStyles;
			document.head.appendChild(style);
		}
		async function load() {
			try {
				const result = await rpc.call(CHANNEL, "settings", {});
				if (!result.ok) throw new Error(result.error.message);
				if (alive) setDraft(result.value);
			} catch (error) {
				if (alive) setError(error.message || String(error));
			}
		}
		load();
		rpc.call(CHANNEL, "models", {}).then((result) => {
			if (!alive) return;
			if (result.ok) setProviders(result.value.providers);
			else setNotice("Model catalog unavailable. You can enter an exact route below.");
		}, () => {
			if (alive) setNotice("Model catalog unavailable. You can enter an exact route below.");
		});
		return () => {
			alive = false;
			style?.remove();
		};
	}, [rpc]);
	function change(key, value) {
		setDraft((draft) => ({
			...draft,
			[key]: value
		}));
	}
	function chooseModel(event) {
		if (event.target.value) {
			const [provider, model] = JSON.parse(event.target.value);
			setDraft((draft) => ({
				...draft,
				provider,
				model
			}));
		}
	}
	async function save() {
		setBusy(true);
		setError("");
		setNotice("");
		try {
			const { autoRecap, inactivityMinutes, provider, model } = draft;
			const result = await rpc.call(CHANNEL, "configure", {
				autoRecap,
				useJev: draft.useJev === true,
				inactivityMinutes: Number(inactivityMinutes),
				provider,
				model
			});
			if (!result.ok) throw new Error(result.error.message);
			setDraft(result.value);
			controller.invalidateSettings();
			setNotice("Session recap settings saved.");
		} catch (error) {
			setError(error.message || String(error));
		} finally {
			setBusy(false);
		}
	}
	return /* @__PURE__ */ react.default.createElement(SettingsForm, {
		open,
		draft,
		providers,
		error,
		notice,
		busy,
		onToggle: () => setOpen((value) => !value),
		onChange: change,
		onChooseModel: chooseModel,
		onSave: () => {
			save();
		}
	});
}

//#endregion
//#region client/registration.js
function apply(ctx) {
	let storage;
	try {
		storage = window.localStorage;
	} catch {}
	const controller = createController({
		rpc: ctx.get("connection").rpc,
		storage
	});
	ctx.get("remote").$on("api-session/activity", (sessionId) => controller.humanMessageSent(sessionId));
	ctx.slots.inject("conversation.input.dock", () => ctx.slots.register({
		name: "conversation.input.dock",
		id: ID,
		order: 10,
		inject: (sessionId) => ({
			sessionId,
			controller
		})
	}, RecapCard));
	ctx.slots.inject("conversation.chat.assistant-actions", () => ctx.slots.register({
		name: "conversation.chat.assistant-actions",
		id: `${ID}-action`,
		order: 10,
		inject: (sessionId) => ({
			sessionId,
			controller
		})
	}, RecapAction));
	ctx.slots.inject("settings.plugin.item", () => ctx.slots.register({
		name: "settings.plugin.item",
		key: ID,
		inject: () => ({
			rpc: ctx.get("connection").rpc,
			controller
		})
	}, SettingsCard));
}

//#endregion
//#region client/index.js
const inject = [
	"slots",
	"connection",
	"remote"
];

//#endregion
exports.CARD_LABELS = CARD_LABELS;
exports.CHANNEL = CHANNEL;
exports.RecapAction = RecapAction;
exports.RecapCard = RecapCard;
exports.SettingsCard = SettingsCard;
exports.apply = apply;
exports.createController = createController;
exports.inject = inject;
return module.exports; } });