import type { CSSProperties } from 'react'
export const styles = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: 'min(720px, 100%)',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '18px',
    border: '1px solid color-mix(in srgb, currentColor 16%, transparent)',
    borderRadius: '12px',
    background: 'color-mix(in srgb, currentColor 3%, transparent)',
  },
  row: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' },
  title: { margin: 0, fontSize: '16px', fontWeight: 650 },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    fontSize: '13px',
    opacity: 0.82,
  },
  dot: (configured: boolean): CSSProperties => ({
    width: '8px',
    height: '8px',
    borderRadius: '999px',
    background: configured ? '#22c55e' : '#ef4444',
  }),
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    fontSize: '13px',
    fontWeight: 600,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid color-mix(in srgb, currentColor 22%, transparent)',
    borderRadius: '8px',
    background: 'transparent',
    color: 'inherit',
    font: 'inherit',
    padding: '10px 12px',
  },
  hint: { margin: 0, fontSize: '13px', opacity: 0.68, lineHeight: 1.45 },
  actions: { display: 'flex', gap: '10px', flexWrap: 'wrap' },
  button: {
    border: '1px solid color-mix(in srgb, currentColor 22%, transparent)',
    borderRadius: '8px',
    background: 'color-mix(in srgb, currentColor 8%, transparent)',
    color: 'inherit',
    font: 'inherit',
    fontWeight: 600,
    padding: '8px 13px',
    cursor: 'pointer',
  },
  danger: { color: '#ef4444' },
  message: (error: boolean): CSSProperties => ({
    margin: 0,
    fontSize: '13px',
    color: error ? '#ef4444' : '#22c55e',
  }),
} satisfies Record<string, CSSProperties | ((...args: never[]) => CSSProperties)>
export const youtubeStyles = {
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '10px 12px',
    border: '1px solid var(--dsw-alias-border-l2-darkmode-thin)',
    borderRadius: '12px',
    background: 'var(--dsw-specific-input-major)',
    color: 'var(--dsw-alias-label-primary)',
  },
  disclosure: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: '26px minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: '9px',
    padding: 0,
    border: 0,
    background: 'transparent',
    color: 'inherit',
    font: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
  },
  icon: {
    display: 'inline-grid',
    placeItems: 'center',
    width: '24px',
    height: '18px',
    borderRadius: '5px',
    background: 'var(--dsw-alias-label-error, #dc2626)',
    color: 'var(--dsw-alias-bg-base, #fff)',
    fontSize: '9px',
  },
  titleWrap: { minWidth: 0, display: 'flex', flexDirection: 'column', gap: '2px' },
  title: { fontSize: '13px', fontWeight: 650 },
  summary: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: '12px',
  },
  state: (color: string): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    color,
    fontSize: '12px',
    fontWeight: 600,
  }),
  dot: (color: string): CSSProperties => ({
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    background: color,
  }),
  chevron: { color: 'var(--dsw-alias-label-secondary)', fontSize: '12px' },
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: '9px',
    paddingTop: '8px',
    borderTop: '1px solid var(--dsw-alias-border-l2-darkmode-thin)',
    fontSize: '13px',
    lineHeight: 1.45,
  },
  context: { color: 'var(--dsw-alias-label-secondary)', overflowWrap: 'anywhere' },
  link: { color: 'var(--dsw-alias-label-accent, currentColor)', textDecoration: 'underline' },
  excerpt: { margin: 0, whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' },
  metrics: { display: 'flex', flexWrap: 'wrap', gap: '6px' },
  chip: {
    padding: '2px 7px',
    borderRadius: '999px',
    background: 'var(--dsw-alias-interactive-bg-hover)',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: '12px',
  },
  callout: {
    padding: '8px 9px',
    borderRadius: '8px',
    background: 'var(--dsw-alias-interactive-bg-hover)',
  },
  error: { color: 'var(--dsw-alias-label-error)', fontWeight: 550 },
  bar: {
    height: '6px',
    overflow: 'hidden',
    borderRadius: '999px',
    background: 'var(--dsw-alias-interactive-bg-hover)',
  },
  fill: (width: string, color: string, indeterminate: boolean): CSSProperties => ({
    width,
    height: '100%',
    backgroundColor: color,
    backgroundImage: indeterminate
      ? 'repeating-linear-gradient(135deg, transparent 0 5px, color-mix(in srgb, currentColor 30%, transparent) 5px 8px)'
      : 'none',
  }),
  timeline: {
    display: 'flex',
    height: '9px',
    overflow: 'hidden',
    borderRadius: '4px',
    background: 'var(--dsw-alias-interactive-bg-hover)',
  },
  interval: (weight: number, color: string, pending: boolean): CSSProperties => ({
    flexGrow: Math.max(1, weight),
    flexBasis: 0,
    minWidth: 0,
    background: color,
    opacity: pending ? 0.4 : 1,
  }),
  intervalList: {
    margin: 0,
    paddingLeft: '20px',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: '12px',
  },
  timestampList: { display: 'flex', flexDirection: 'column', gap: '5px' },
  timestampRow: { display: 'flex', gap: '8px', alignItems: 'baseline' },
  timestamp: { flex: '0 0 auto', fontVariantNumeric: 'tabular-nums' },
  footer: { display: 'flex', justifyContent: 'flex-end' },
  action: {
    border: 0,
    background: 'transparent',
    color: 'var(--dsw-alias-label-accent, currentColor)',
    padding: 0,
    font: 'inherit',
    cursor: 'pointer',
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    border: 0,
  },
} satisfies Record<string, CSSProperties | ((...args: never[]) => CSSProperties)>
