// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-linear", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/rpc.ts
const CREDENTIAL_REF = "LINEAR_API_KEY";
const SETTINGS_NAMESPACE = "local-linear";
const CHANNEL = "/linear-integration";

//#endregion
//#region shared/api-key.ts
function apiKeyFailure(value) {
	if (typeof value !== "string" || value.length === 0 || value.trim().length === 0) return "Enter a Linear API key.";
	const trimmed = value.trim();
	if (!/^[\x21-\x7e]+$/u.test(trimmed)) return "Use an unquoted API key containing printable characters only.";
	if (/^[A-Za-z_][A-Za-z0-9_]*=/u.test(trimmed) || trimmed.startsWith("\"") && trimmed.endsWith("\"") || trimmed.startsWith("'") && trimmed.endsWith("'")) return "Paste only the API key, without LINEAR_API_KEY= or surrounding quotes.";
}

//#endregion
//#region client/styles.ts
const styles = {
	section: {
		display: "flex",
		flexDirection: "column",
		gap: "16px",
		width: "min(760px, 100%)"
	},
	card: {
		display: "flex",
		flexDirection: "column",
		gap: "16px",
		padding: "18px",
		border: "1px solid color-mix(in srgb, currentColor 16%, transparent)",
		borderRadius: "12px",
		background: "color-mix(in srgb, currentColor 3%, transparent)"
	},
	row: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: "12px",
		flexWrap: "wrap"
	},
	title: {
		margin: 0,
		fontSize: "16px",
		fontWeight: 650
	},
	badge: {
		display: "inline-flex",
		alignItems: "center",
		gap: "7px",
		fontSize: "13px",
		opacity: .82
	},
	dot: (configured, live) => ({
		width: "8px",
		height: "8px",
		borderRadius: "999px",
		background: live ? "#22c55e" : configured ? "#f59e0b" : "#ef4444"
	}),
	label: {
		display: "flex",
		flexDirection: "column",
		gap: "7px",
		fontSize: "13px",
		fontWeight: 600
	},
	input: {
		width: "100%",
		boxSizing: "border-box",
		border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
		borderRadius: "8px",
		background: "transparent",
		color: "inherit",
		font: "inherit",
		padding: "10px 12px"
	},
	hint: {
		margin: 0,
		fontSize: "13px",
		opacity: .68,
		lineHeight: 1.45
	},
	details: {
		display: "grid",
		gridTemplateColumns: "max-content 1fr",
		gap: "6px 16px",
		fontSize: "13px"
	},
	term: { opacity: .62 },
	actions: {
		display: "flex",
		gap: "10px",
		flexWrap: "wrap"
	},
	button: {
		border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
		borderRadius: "8px",
		background: "color-mix(in srgb, currentColor 8%, transparent)",
		color: "inherit",
		font: "inherit",
		fontWeight: 600,
		padding: "8px 13px",
		cursor: "pointer"
	},
	primary: {
		background: "#5e6ad2",
		borderColor: "#5e6ad2",
		color: "#fff"
	},
	danger: { color: "#ef4444" },
	message: (error) => ({
		margin: 0,
		fontSize: "13px",
		color: error ? "#ef4444" : "#22c55e"
	})
};

//#endregion
//#region client/labels.ts
function messageOf(error) {
	return error instanceof Error ? error.message : String(error);
}
function sourceLabel(source) {
	return {
		env: "launch environment",
		file: "DSH credential store",
		"project-env": "project .env",
		"user-env": "user .env",
		composition: "profile composition"
	}[source] ?? source;
}

//#endregion
//#region client/settings.tsx
function LinearSettingsSection(props) {
	const { rpc, subscribe } = props;
	const [status, setStatus] = react.default.useState(void 0);
	const [draft, setDraft] = react.default.useState("");
	const [busy, setBusy] = react.default.useState(false);
	const [failure, setFailure] = react.default.useState(void 0);
	const [success, setSuccess] = react.default.useState(void 0);
	const [revision, setRevision] = react.default.useState(0);
	react.default.useEffect(() => subscribe(() => setRevision((value) => value + 1)), [subscribe]);
	react.default.useEffect(() => {
		let active = true;
		rpc.call(CHANNEL, "status", {}).then((result) => {
			if (!active) return;
			if (!result.ok) {
				setFailure(result.error.message);
				return;
			}
			setStatus(result.value);
		}, (error) => {
			if (active) setFailure(messageOf(error));
		});
		return () => {
			active = false;
		};
	}, [rpc, revision]);
	const call = async (endpoint, payload, successMessage) => {
		setBusy(true);
		setFailure(void 0);
		setSuccess(void 0);
		try {
			const result = await rpc.call(CHANNEL, endpoint, payload);
			if (!result.ok) {
				setFailure(result.error.message);
				return false;
			}
			setStatus(result.value);
			setSuccess(successMessage);
			return true;
		} catch (error) {
			setFailure(messageOf(error));
			return false;
		} finally {
			setBusy(false);
		}
	};
	const connect = async () => {
		const validation = apiKeyFailure(draft);
		if (validation !== void 0) {
			setFailure(validation);
			setSuccess(void 0);
			return;
		}
		if (await call("connect", { apiKey: draft.trim() }, "Linear workspace connected.")) setDraft("");
	};
	const test = () => call("test", {}, "Connection verified against Linear.");
	const disconnect = async () => {
		if (!window.confirm("Remove the stored Linear API key and workspace binding?")) return;
		if (await call("disconnect", {}, "Linear workspace disconnected.")) setDraft("");
	};
	const credential = status?.credential;
	const configured = credential?.configured === true;
	const writable = credential?.writable === true;
	const source = credential?.source === void 0 ? void 0 : sourceLabel(credential.source);
	const badge = status === void 0 ? "Checking…" : status.live ? "Connected" : configured ? `Configured${source === void 0 ? "" : ` via ${source}`}` : "Not configured";
	return /* @__PURE__ */ react.default.createElement("details", {
		style: {
			...styles.card,
			display: "block"
		},
		open: props.view === "page" || void 0
	}, /* @__PURE__ */ react.default.createElement("summary", { style: { cursor: "pointer" } }, /* @__PURE__ */ react.default.createElement("span", { style: styles.title }, "Linear"), /* @__PURE__ */ react.default.createElement("p", { style: {
		...styles.hint,
		marginTop: "4px"
	} }, "Workspace connection for issue discovery and approval-gated project management.")), /* @__PURE__ */ react.default.createElement("div", {
		style: {
			...styles.section,
			marginTop: "16px"
		},
		role: "group",
		"aria-labelledby": "linear-connection-title"
	}, /* @__PURE__ */ react.default.createElement("div", { style: styles.row }, /* @__PURE__ */ react.default.createElement("h3", {
		id: "linear-connection-title",
		style: styles.title
	}, "Workspace connection"), /* @__PURE__ */ react.default.createElement("span", {
		style: styles.badge,
		role: "status"
	}, /* @__PURE__ */ react.default.createElement("span", {
		style: styles.dot(configured, status?.live === true),
		"aria-hidden": "true"
	}), badge)), status?.workspace == null ? null : /* @__PURE__ */ react.default.createElement("div", { style: styles.details }, /* @__PURE__ */ react.default.createElement("span", { style: styles.term }, "Workspace"), /* @__PURE__ */ react.default.createElement("span", null, status.workspace.name), /* @__PURE__ */ react.default.createElement("span", { style: styles.term }, "Workspace key"), /* @__PURE__ */ react.default.createElement("span", null, status.workspace.urlKey || "—"), status.viewer == null ? null : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("span", { style: styles.term }, "Authenticated as"), /* @__PURE__ */ react.default.createElement("span", null, status.viewer.email ?? status.viewer.name))), /* @__PURE__ */ react.default.createElement("label", { style: styles.label }, configured ? "Replace API key" : "Linear API key", /* @__PURE__ */ react.default.createElement("input", {
		type: "password",
		value: draft,
		disabled: busy || !writable,
		autoComplete: "off",
		spellCheck: false,
		placeholder: configured ? "Enter a replacement key" : "lin_api_…",
		style: styles.input,
		onChange: (event) => setDraft(event.target.value),
		onKeyDown: (event) => {
			if (event.key === "Enter" && !busy && writable) connect();
		}
	})), /* @__PURE__ */ react.default.createElement("p", { style: styles.hint }, writable ? "DSH validates the key against Linear, binds the returned workspace ID, and stores the key write-only in the credential store." : configured ? "This key comes from a read-only source. Remove it there before managing it in this page." : "Credential writes are unavailable from this browser. Open DSH on its loopback URL."), /* @__PURE__ */ react.default.createElement("div", { style: styles.actions }, /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy || !writable,
		style: {
			...styles.button,
			...styles.primary,
			opacity: busy || !writable ? .5 : 1
		},
		onClick: () => {
			connect();
		}
	}, busy ? "Working…" : configured ? "Replace and connect" : "Connect"), configured ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy,
		style: {
			...styles.button,
			opacity: busy ? .5 : 1
		},
		onClick: () => {
			test();
		}
	}, "Test connection") : null, configured && writable ? /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		disabled: busy,
		style: {
			...styles.button,
			...styles.danger,
			opacity: busy ? .5 : 1
		},
		onClick: () => {
			disconnect();
		}
	}, "Disconnect") : null), failure === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", {
		style: styles.message(true),
		role: "alert"
	}, failure), success === void 0 ? null : /* @__PURE__ */ react.default.createElement("p", {
		style: styles.message(false),
		role: "status"
	}, success)));
}
function LinearConfigPage(props) {
	return props.view === "summary" ? "Workspace connection for issue discovery and approval-gated project management." : /* @__PURE__ */ react.default.createElement(LinearSettingsSection, props);
}

//#endregion
//#region client/index.ts
const inject = [
	"slots",
	"connection",
	"remote"
];
function apply(ctx) {
	const connection = ctx.get("connection");
	const subscribe = (listener) => {
		const disposers = [
			ctx.remote.$on("credentials/reference-updated", (ref) => {
				if (ref === "LINEAR_API_KEY") listener();
			}),
			ctx.remote.$on("settings/document-updated", (ns) => {
				if (ns === "local-linear") listener();
			}),
			ctx.on("connection/reset", listener)
		];
		return () => {
			for (const dispose of disposers) dispose();
		};
	};
	ctx.slots.inject("plugins.row.config", () => ctx.slots.register({
		name: "plugins.row.config",
		key: "@local/dsh-linear#local-linear",
		order: 35,
		inject: () => ({
			rpc: connection.rpc,
			subscribe
		})
	}, LinearConfigPage));
}

//#endregion
exports.CHANNEL = CHANNEL;
exports.CREDENTIAL_REF = CREDENTIAL_REF;
exports.LinearSettingsSection = LinearSettingsSection;
exports.SETTINGS_NAMESPACE = SETTINGS_NAMESPACE;
exports.apiKeyFailure = apiKeyFailure;
exports.apply = apply;
exports.inject = inject;
return module.exports; } });