import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const diagnosticHost = {
  getCanonicalFileName: (name) => name,
  getCurrentDirectory: () => process.cwd(),
  getNewLine: () => '\n',
}
function fail(diagnostics) {
  if (diagnostics.length) throw new Error(ts.formatDiagnostics(diagnostics, diagnosticHost))
}

// Compile checked ESM modules rather than bundle copies of shared classes/services.
// Return bytes first, so freshness tests never rewrite the artifact they inspect.
export function buildHost(projectUrl) {
  const project = fileURLToPath(projectUrl)
  const config = ts.readConfigFile(project, ts.sys.readFile)
  if (config.error) fail([config.error])
  const parsed = ts.parseJsonConfigFileContent(
    config.config,
    ts.sys,
    dirname(project),
    {
      noEmit: false,
      noEmitOnError: true,
      sourceMap: false,
      declaration: false,
    },
    project,
  )
  fail(parsed.errors)
  const program = ts.createProgram(parsed.fileNames, parsed.options)
  fail(ts.getPreEmitDiagnostics(program))
  const output = new Map()
  const outDir = parsed.options.outDir
  if (!outDir) throw new Error('Host compiler configuration requires outDir.')
  const emitted = program.emit(undefined, (path, content) => {
    const name = relative(outDir, path).replaceAll('\\', '/')
    if (name.startsWith('test/')) return // compile-time assertions are never deployed.
    if (name.startsWith('../') || !name.endsWith('.js'))
      throw new Error(`Unexpected host output: ${name}`)
    output.set(
      name,
      `// GENERATED by scripts/build-host.mjs. Edit TypeScript sources, not this file.\n${content}`,
    )
  })
  fail(emitted.diagnostics)
  if (emitted.emitSkipped || !output.size) throw new Error('Host compilation emitted no modules.')
  return { outDir, files: output }
}

export function writeHost({ outDir, files }) {
  for (const [name, content] of files) {
    const path = resolve(outDir, name)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  }
}

export function checkHost({ outDir, files }) {
  const actual = readdirSync(outDir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(outDir, resolve(entry.parentPath, entry.name)).replaceAll('\\', '/'))
    .sort()
  if (JSON.stringify(actual) !== JSON.stringify([...files.keys()].sort())) {
    throw new Error(
      'Host artifact file set is stale; regenerate and remove obsolete generated files.',
    )
  }
  for (const [name, content] of files) {
    if (readFileSync(resolve(outDir, name), 'utf8') !== content) {
      throw new Error(`Host artifact ${name} is stale. Run the package build:host command.`)
    }
  }
}
