// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-worktree", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CHANNEL = "/local-worktrees";

//#endregion
//#region client/reader.ts
function record(value) {
	return typeof value === "object" && value !== null ? value : {};
}
function hasSnapshotEnvelope(value, sessionId) {
	return value.sessionId === sessionId && typeof value.state === "string" && [
		"ready",
		"disabled",
		"unavailable",
		"error"
	].includes(value.state);
}
function unwrap(input, sessionId) {
	const result = record(input);
	if (result?.ok !== true) throw new Error("Worktrees RPC failed.");
	const value = record(result.value);
	if (!hasSnapshotEnvelope(value, sessionId)) throw new Error("Invalid Worktrees response.");
	return value;
}
function createReader(rpc, sessionId, publish) {
	let generation = 0;
	let disposed = false;
	let selection = {};
	let value;
	return {
		async refresh(next = selection) {
			selection = next;
			const token = ++generation;
			publish({
				value,
				loading: true
			});
			try {
				const result = unwrap(await rpc.call(CHANNEL, "snapshot", {
					sessionId,
					...selection
				}), sessionId);
				if (disposed || token !== generation) return;
				if (result.state === "error" || result.state === "ready" && !Array.isArray(result.worktrees)) throw new Error("Invalid Worktrees snapshot.");
				if (result.state === "ready" && result.selected) {
					selection = {
						...selection,
						path: result.selected.path
					};
					if (result.selected.run) selection.runId = result.selected.run.id;
				}
				value = result;
				publish({
					value,
					loading: false
				});
			} catch {
				if (!disposed && token === generation) publish({
					loading: false,
					error: "Worktrees could not refresh. Try again."
				});
			}
		},
		dispose() {
			disposed = true;
			generation++;
		}
	};
}

//#endregion
//#region client/panel.tsx
const visible = () => document.visibilityState !== "hidden";
const panelCss = `
  .wt-panel{--wt-border:var(--dsw-alias-border-l2,#8884);--wt-muted:var(--dsw-alias-label-secondary,#888);--wt-accent:var(--dsw-alias-state-business-primary,#598be8);color:var(--dsw-alias-label-primary,inherit);font:13px/1.5 system-ui,sans-serif;padding:24px;box-sizing:border-box;overflow:auto;height:100%;container-type:inline-size}
  .wt-panel *{box-sizing:border-box}.wt-panel h2,.wt-panel h3,.wt-panel h4,.wt-panel p{margin:0}.wt-panel h2{font-size:20px;letter-spacing:-.4px}.wt-panel h3{font-size:18px;overflow-wrap:anywhere}.wt-panel h4{font-size:13px;font-weight:600}.wt-panel button{font:inherit;cursor:pointer;color:inherit;border:1px solid var(--wt-border);background:transparent;border-radius:8px;padding:7px 11px}.wt-panel button:hover{background:var(--dsw-alias-interactive-bg-hover,#8881)}.wt-panel button:focus-visible{outline:2px solid var(--wt-accent);outline-offset:3px}.wt-panel button:disabled{opacity:.5;cursor:wait}
  .wt-header,.wt-title,.wt-section-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.wt-header{margin-bottom:24px}.wt-subtitle,.wt-path,.wt-muted{color:var(--wt-muted)}.wt-subtitle{margin-top:4px!important}.wt-path{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere;margin-top:6px!important}.wt-layout{display:grid;grid-template-columns:minmax(230px,300px) minmax(0,1fr);gap:24px;max-width:1280px}.wt-list{list-style:none;padding:0;margin:10px 0;display:grid;gap:6px;align-content:start}.wt-panel .wt-card{display:block;width:100%;text-align:left;padding:14px;border-color:transparent}.wt-panel .wt-card[aria-pressed=true]{border-color:var(--wt-accent);background:color-mix(in srgb,var(--wt-accent) 9%,transparent)}.wt-card-name{font-weight:600;display:block;overflow-wrap:anywhere}.wt-branch{display:block;color:var(--wt-muted);font:12px/1.5 ui-monospace,monospace;overflow-wrap:anywhere;margin:3px 0 10px}.wt-badges{display:flex;gap:6px;flex-wrap:wrap}.wt-badge{display:inline-flex;font-size:11px;padding:2px 7px;border:1px solid var(--wt-border);border-radius:20px;color:var(--wt-muted)}.wt-badge[data-state=busy],.wt-badge[data-state=running]{color:var(--wt-accent);border-color:currentColor}.wt-badge[data-state=failed]{color:var(--dsw-alias-state-error-primary,#d86161)}.wt-assignment{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;color:var(--wt-muted);font-size:12px;margin-top:10px}
  .wt-detail{min-width:0;border:1px solid var(--wt-border);border-radius:12px;padding:24px;background:var(--dsw-alias-bg-layer-1,transparent)}.wt-section{margin-top:24px;padding-top:20px;border-top:1px solid var(--wt-border)}.wt-empty{padding:24px 14px;text-align:center;color:var(--wt-muted);border:1px dashed var(--wt-border);border-radius:8px;margin-top:12px!important}.wt-files{list-style:none;padding:0;margin:12px 0 0;max-height:230px;overflow:auto}.wt-files li{display:flex;gap:12px;padding:7px 0;border-bottom:1px solid var(--wt-border);font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}.wt-files code{flex:none;color:var(--wt-accent);white-space:pre}.wt-runs{list-style:none;padding:0;margin:12px 0;display:grid;gap:6px}.wt-panel .wt-run{width:100%;text-align:left;display:flex;gap:12px;align-items:center;padding:10px 12px}.wt-run[aria-pressed=true]{border-color:var(--wt-accent);background:color-mix(in srgb,var(--wt-accent) 7%,transparent)}.wt-run .wt-badge{margin-left:auto}.wt-report{margin-top:16px}.wt-panel pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.7 ui-monospace,monospace;background:var(--dsw-alias-interactive-bg-hover,#8881);border-radius:8px;padding:14px;max-height:320px;overflow:auto;margin:8px 0 16px}.wt-refresh{display:flex;align-items:center;gap:12px}.wt-refresh-status{color:var(--wt-muted);font-size:12px}.wt-notice{margin-bottom:12px!important;color:var(--wt-muted)}.wt-copy-status{font-size:12px;color:var(--wt-muted);margin-top:8px;display:block}.wt-count{font-size:11px;font-weight:400;border:1px solid var(--wt-border);border-radius:20px;padding:1px 7px;margin-left:6px}
  @container(max-width:700px){.wt-layout{grid-template-columns:1fr}.wt-list{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))}.wt-detail{padding:16px}.wt-title{align-items:flex-start;flex-wrap:wrap}.wt-header{align-items:flex-start}}@media(max-width:500px){.wt-panel{padding:16px}}
`;
function Panel({ rpc, jobs, sessionId }) {
	const [state, setState] = react.useState({ loading: true });
	const [copied, setCopied] = react.useState("");
	const readerRef = react.useRef();
	react.useEffect(() => {
		const reader = createReader(rpc, sessionId, setState);
		readerRef.current = reader;
		const refresh = () => {
			if (visible()) reader.refresh();
		};
		const unwatch = jobs.watchRows(sessionId);
		let rows = jobs.state.getSnapshot().rows[sessionId];
		const off = jobs.state.subscribe(() => {
			const next = jobs.state.getSnapshot().rows[sessionId];
			if (next !== rows) {
				rows = next;
				refresh();
			}
		});
		refresh();
		const timer = setInterval(refresh, 1e4);
		document.addEventListener("visibilitychange", refresh);
		return () => {
			reader.dispose();
			off();
			unwatch();
			clearInterval(timer);
			document.removeEventListener("visibilitychange", refresh);
		};
	}, [
		rpc,
		sessionId,
		jobs
	]);
	const value = state.value;
	const selected = value?.selected;
	const choose = (selection) => {
		setCopied("");
		readerRef.current?.refresh(selection);
	};
	const button = (text, onClick, extra = {}) => /* @__PURE__ */ react.createElement("button", {
		type: "button",
		onClick,
		...extra
	}, text);
	const badge = (text, status) => /* @__PURE__ */ react.createElement("span", {
		className: "wt-badge",
		"data-state": status
	}, text);
	const selectedRow = value?.worktrees?.find((row) => row.path === selected?.path);
	return /* @__PURE__ */ react.createElement("section", {
		"aria-label": "Worktrees",
		className: "wt-panel"
	}, /* @__PURE__ */ react.createElement("style", null, panelCss), /* @__PURE__ */ react.createElement("div", { className: "wt-header" }, /* @__PURE__ */ react.createElement("div", null, /* @__PURE__ */ react.createElement("h2", null, "Worktrees"), /* @__PURE__ */ react.createElement("p", { className: "wt-subtitle" }, "Repository checkouts · Session activity")), /* @__PURE__ */ react.createElement("div", { className: "wt-refresh" }, /* @__PURE__ */ react.createElement("span", {
		className: "wt-refresh-status",
		role: "status",
		style: { visibility: state.loading && value ? "visible" : "hidden" }
	}, "Updating…"), button("Refresh", () => readerRef.current?.refresh(), { disabled: state.loading && !value }))), state.loading && !value && /* @__PURE__ */ react.createElement("p", { role: "status" }, "Loading worktrees…"), state.error && /* @__PURE__ */ react.createElement("p", { role: "alert" }, state.error), value?.state === "error" && /* @__PURE__ */ react.createElement("p", { role: "alert" }, value.message), (value?.state === "unavailable" || value?.state === "disabled") && /* @__PURE__ */ react.createElement("p", { role: "status" }, "Worktree integration is unavailable for this session."), value?.state === "ready" && value.worktrees && /* @__PURE__ */ react.createElement("div", { className: "wt-layout" }, /* @__PURE__ */ react.createElement("nav", { "aria-label": "Repository worktrees" }, /* @__PURE__ */ react.createElement("div", { className: "wt-section-title" }, /* @__PURE__ */ react.createElement("h4", null, "Checkouts"), badge(String(value.worktrees.length))), /* @__PURE__ */ react.createElement("p", {
		className: "wt-path",
		title: value.repository
	}, value.repository), value.truncated && /* @__PURE__ */ react.createElement("p", { className: "wt-muted" }, "Showing the first 100 repository worktrees."), value.worktrees.length === 0 && /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "No worktrees found."), /* @__PURE__ */ react.createElement("ul", { className: "wt-list" }, value.worktrees.map((row) => /* @__PURE__ */ react.createElement("li", { key: row.path }, button(/* @__PURE__ */ react.createElement(react.Fragment, null, /* @__PURE__ */ react.createElement("span", { className: "wt-card-name" }, row.name), /* @__PURE__ */ react.createElement("span", { className: "wt-branch" }, row.branch ?? "detached / bare"), /* @__PURE__ */ react.createElement("span", { className: "wt-badges" }, badge(`Worker: ${row.workerStatus}`, row.workerStatus), badge(row.changes.error !== void 0 ? "Git unavailable" : row.changes.count === 0 ? "Clean" : `${row.changes.count} changed ${row.changes.count === 1 ? "file" : "files"}`)), row.cleanupUncertain && /* @__PURE__ */ react.createElement("span", { className: "wt-assignment" }, "Cleanup uncertain"), row.latestAssignment && /* @__PURE__ */ react.createElement("span", { className: "wt-assignment" }, row.latestAssignment)), () => choose({ path: row.path }), {
		className: "wt-card",
		"aria-label": `${row.name} — ${row.branch ?? "detached / bare"}`,
		"aria-pressed": selected?.path === row.path
	}))))), selected ? /* @__PURE__ */ react.createElement("section", {
		"aria-label": "Selected worktree",
		className: "wt-detail"
	}, /* @__PURE__ */ react.createElement("div", { className: "wt-title" }, /* @__PURE__ */ react.createElement("div", null, /* @__PURE__ */ react.createElement("h3", null, selectedRow?.name ?? selected.path.split(/[\\/]/).at(-1)), /* @__PURE__ */ react.createElement("p", { className: "wt-branch" }, selectedRow?.branch ?? "detached / bare")), button("Copy checkout path", async () => {
		try {
			await navigator.clipboard.writeText(selected.path);
			setCopied("Copied checkout path.");
		} catch {
			setCopied("Copy failed. Select and copy the path above.");
		}
	})), /* @__PURE__ */ react.createElement("p", { className: "wt-path" }, selected.path), /* @__PURE__ */ react.createElement("span", {
		role: "status",
		className: "wt-copy-status"
	}, copied), /* @__PURE__ */ react.createElement("div", { className: "wt-section" }, /* @__PURE__ */ react.createElement("h4", null, "Changed files", /* @__PURE__ */ react.createElement("span", { className: "wt-count" }, selected.changes.error !== void 0 ? "—" : selected.changes.count))), selected.changes.error !== void 0 ? /* @__PURE__ */ react.createElement("p", null, selected.changes.error) : /* @__PURE__ */ react.createElement(react.Fragment, null, selected.changes.count === 0 && /* @__PURE__ */ react.createElement("p", null, "No changed files."), /* @__PURE__ */ react.createElement("ul", { className: "wt-files" }, selected.changes.files.map((file, index) => /* @__PURE__ */ react.createElement("li", { key: index }, /* @__PURE__ */ react.createElement("code", null, file.status), /* @__PURE__ */ react.createElement("span", null, `${file.path}${file.from ? ` ← ${file.from}` : ""}`)))), selected.changes.truncated && /* @__PURE__ */ react.createElement("p", null, "Showing the first 500 changed files.")), /* @__PURE__ */ react.createElement("div", { className: "wt-section" }, /* @__PURE__ */ react.createElement("h4", null, `This session’s recorded runs (${selected.runs.length})`)), selected.runs.length === 0 && /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "No recorded runs for this worktree."), selected.runs.length > 0 && !selected.run && /* @__PURE__ */ react.createElement("p", null, "The selected run is no longer available. Select a retained run below."), /* @__PURE__ */ react.createElement("ol", { className: "wt-runs" }, selected.runs.map((run, index) => /* @__PURE__ */ react.createElement("li", { key: run.id }, button(/* @__PURE__ */ react.createElement(react.Fragment, null, /* @__PURE__ */ react.createElement("span", { className: "wt-muted" }, `#${selected.runs.length - index}`), /* @__PURE__ */ react.createElement("span", null, run.mode === "read-only" ? "Read-only run" : "Write run"), badge(run.status, run.status)), () => choose({
		path: selected.path,
		runId: run.id
	}), {
		className: "wt-run",
		"aria-label": `${selected.runs.length - index}. ${run.mode} · ${run.status}`,
		"aria-pressed": selected.run?.id === run.id
	})))), selected.run && /* @__PURE__ */ react.createElement("div", { className: "wt-report" }, /* @__PURE__ */ react.createElement("h4", null, "Full assignment"), /* @__PURE__ */ react.createElement("pre", null, selected.run.task), /* @__PURE__ */ react.createElement("h4", null, "Available report"), /* @__PURE__ */ react.createElement("pre", null, selected.run.report ?? "No report available."))) : /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "Select a worktree. The previous selection may no longer be registered.")));
}

//#endregion
//#region client/capability.ts
function watchCapability({ sessions, rpc, register, interval = setInterval, clear = clearInterval, document: doc = document }) {
	let current;
	let generation = 0;
	let offTab;
	let stopped = false;
	let pending;
	const remove = () => {
		offTab?.();
		offTab = void 0;
	};
	function check() {
		const selected = Object.values(sessions.list.getSnapshot().byId).filter((session) => (session.retainedBy.mainView ?? 0) > 0);
		const id = selected.length === 1 ? selected[0].id : void 0;
		if (id !== current) {
			current = id;
			generation++;
			pending = void 0;
			remove();
		}
		if (stopped || !id || doc.visibilityState === "hidden" || pending) return;
		const token = generation;
		pending = Promise.resolve().then(() => rpc.call(CHANNEL, "capability", { sessionId: id })).then((result) => {
			if (stopped || token !== generation) return;
			const value = unwrap(result, id);
			if (value?.sessionId === id && value.state === "ready") {
				if (!offTab) offTab = register(id);
			} else remove();
		}).catch(() => {
			if (!stopped && token === generation) remove();
		}).finally(() => {
			if (token === generation) pending = void 0;
		});
	}
	const off = sessions.list.subscribe(check);
	const timer = interval(check, 1e4);
	doc.addEventListener("visibilitychange", check);
	check();
	return () => {
		stopped = true;
		generation++;
		remove();
		off();
		clear(timer);
		doc.removeEventListener("visibilitychange", check);
	};
}

//#endregion
//#region client/session-contracts.ts
function shellSeats(ctx) {
	return ctx.slots;
}

//#endregion
//#region shared/session-contracts.ts
const SESSION_CHANNEL = "/local-worktree-sessions";

//#endregion
//#region client/session-store.ts
function errorMessage(error) {
	return error instanceof Error ? error.message : "Session worktree request failed.";
}
function currentSession(ctx) {
	const selected = Object.values(ctx.sessions.list.getSnapshot().byId).filter((row) => (row.retainedBy.mainView ?? 0) > 0);
	return selected.length === 1 ? selected[0]?.id : void 0;
}
function createSessionRequest(ctx) {
	const rpc = ctx.connection.rpc;
	return async (endpoint, input, signal) => {
		const response = await rpc.call(SESSION_CHANNEL, endpoint, input, signal);
		if (typeof response !== "object" || response === null || !("ok" in response)) throw new Error("Invalid session worktree response.");
		const result = response;
		if (!result.ok) throw new Error(`${result.error.code}: ${result.error.message}`);
		return result.value;
	};
}
function createSessionStore(ctx) {
	const request = createSessionRequest(ctx);
	const listeners = /* @__PURE__ */ new Set();
	const reviewed = /* @__PURE__ */ new Set();
	const blocks = /* @__PURE__ */ new Map();
	let state = {
		sessionId: currentSession(ctx),
		status: null,
		records: [],
		loading: true,
		error: null,
		readError: null,
		busy: /* @__PURE__ */ new Set(),
		dialog: null
	};
	let disposed = false;
	let controller = null;
	let pendingRefresh = false;
	let reviewing = false;
	const publish = (patch) => {
		if (disposed) return;
		state = {
			...state,
			...patch
		};
		for (const listener of listeners) listener();
	};
	const setBusy = (id, busy) => {
		const next = new Set(state.busy);
		if (busy) next.add(id);
		else next.delete(id);
		publish({ busy: next });
	};
	const clearBlock = (id) => {
		const block = blocks.get(id);
		if (!block) return;
		if (ctx.conversation.blocks.storeFor(id).getSnapshot() === block) ctx.conversation.blocks.set(id, void 0);
		blocks.delete(id);
	};
	const block = (id, reason = "Preparing session worktree…") => {
		const own = blocks.get(id);
		const current = ctx.conversation.blocks.storeFor(id).getSnapshot();
		if (current && current !== own) return;
		if (own?.reason === reason && current === own) return;
		const value = { reason };
		blocks.set(id, value);
		ctx.conversation.blocks.set(id, value);
	};
	async function refresh() {
		if (disposed || document.visibilityState === "hidden") return;
		if (controller) {
			pendingRefresh = true;
			return;
		}
		const selected = state.sessionId;
		const abort = new AbortController();
		controller = abort;
		try {
			const status = await request("status", selected ? { sessionId: selected } : {}, abort.signal);
			if (disposed || abort.signal.aborted || selected !== state.sessionId) return;
			publish({
				status,
				records: status.records,
				loading: false,
				readError: null
			});
			reviewNext();
		} catch (error) {
			if (!disposed && !abort.signal.aborted && selected === state.sessionId) publish({
				loading: false,
				readError: errorMessage(error)
			});
		} finally {
			if (controller === abort) controller = null;
			if (pendingRefresh && !disposed) {
				pendingRefresh = false;
				refresh();
			}
		}
	}
	async function cleanup(sessionId) {
		if (disposed || state.busy.has(sessionId)) return;
		setBusy(sessionId, true);
		reviewed.add(sessionId);
		try {
			const result = await request("cleanup", { sessionId });
			if (disposed) return;
			if (result.state === "confirm" && result.confirmation) publish({
				dialog: {
					record: result.record,
					confirmation: result.confirmation
				},
				error: null
			});
			else publish({ error: result.state === "pending" ? result.record.message : null });
		} catch (error) {
			publish({ error: errorMessage(error) });
		} finally {
			setBusy(sessionId, false);
			refresh();
		}
	}
	async function reviewNext() {
		if (disposed || reviewing || state.dialog) return;
		const pending = state.records.find((row) => row.state === "pending" && !reviewed.has(row.sessionId));
		if (!pending) return;
		reviewing = true;
		await cleanup(pending.sessionId);
		reviewing = false;
		if (!state.dialog) reviewNext();
	}
	const selectionChanged = () => {
		const next = currentSession(ctx);
		if (next === state.sessionId) return;
		controller?.abort();
		const previous = state.sessionId;
		if (previous && !state.busy.has(previous)) clearBlock(previous);
		publish({
			sessionId: next,
			status: null,
			loading: true,
			error: null,
			readError: null
		});
		refresh();
	};
	return {
		request,
		getSnapshot: () => state,
		subscribe: (listener) => {
			listeners.add(listener);
			return () => {
				listeners.delete(listener);
			};
		},
		refresh,
		block,
		clearBlock,
		report: (error) => publish({ error: errorMessage(error) }),
		dismissError: () => publish({
			error: null,
			readError: null
		}),
		cleanup,
		keepCheckout() {
			publish({ dialog: null });
			reviewNext();
		},
		async discardCheckout() {
			const dialog = state.dialog;
			if (!dialog || disposed || state.busy.has(dialog.record.sessionId)) return;
			const sessionId = dialog.record.sessionId;
			setBusy(sessionId, true);
			try {
				const result = await request("cleanup", {
					sessionId,
					confirmationId: dialog.confirmation.id
				});
				if (result.state !== "removed") throw new Error(result.record.message || "Cleanup needs a new review.");
				publish({
					dialog: null,
					error: null
				});
			} catch (error) {
				publish({ error: errorMessage(error) });
			} finally {
				setBusy(sessionId, false);
				refresh();
				reviewNext();
			}
		},
		async archive(sessionId) {
			if (disposed || state.busy.has(sessionId)) return;
			setBusy(sessionId, true);
			try {
				await ctx.uiWorkspace.archiveSession(sessionId);
				publish({ error: null });
			} catch (error) {
				publish({ error: errorMessage(error) });
			} finally {
				setBusy(sessionId, false);
				refresh();
			}
		},
		async restore(sessionId) {
			if (disposed || state.busy.has(sessionId)) return;
			setBusy(sessionId, true);
			try {
				const record = await request("restore", { sessionId });
				reviewed.delete(sessionId);
				if (disposed) return;
				await ctx.sessions.refresh();
				if (!disposed) ctx.uiWorkspace.openSession(record.sessionId);
			} catch (error) {
				publish({ error: errorMessage(error) });
			} finally {
				setBusy(sessionId, false);
				refresh();
			}
		},
		async create(sessionId, onCreated) {
			if (disposed || state.busy.has(sessionId)) return;
			setBusy(sessionId, true);
			block(sessionId);
			try {
				const record = await request("create", {
					sessionId,
					requestId: crypto.randomUUID()
				});
				if (disposed) return;
				await ctx.sessions.refresh();
				if (!disposed) onCreated(record);
			} catch (error) {
				publish({ error: errorMessage(error) });
			} finally {
				if (currentSession(ctx) !== sessionId) clearBlock(sessionId);
				setBusy(sessionId, false);
				refresh();
			}
		},
		start() {
			const unsubscribe = ctx.sessions.list.subscribe(selectionChanged);
			const onVisible = () => {
				if (document.visibilityState === "hidden") controller?.abort();
				else refresh();
			};
			document.addEventListener("visibilitychange", onVisible);
			const timer = setInterval(() => {
				refresh();
			}, 7500);
			refresh();
			return () => {
				disposed = true;
				controller?.abort();
				clearInterval(timer);
				unsubscribe();
				document.removeEventListener("visibilitychange", onVisible);
				for (const id of blocks.keys()) clearBlock(id);
				listeners.clear();
			};
		}
	};
}

//#endregion
//#region client/session-components.tsx
const surface = {
	color: "var(--dsw-alias-label-primary)",
	background: "var(--dsw-alias-bg-base)",
	border: "1px solid var(--dsw-alias-border-l3)",
	borderRadius: 12
};
const action = {
	font: "inherit",
	color: "inherit",
	background: "var(--dsw-alias-interactive-bg-hover)",
	border: "1px solid var(--dsw-alias-border-l3)",
	borderRadius: 8,
	padding: "6px 12px",
	cursor: "pointer"
};
function BranchIcon({ size = 16 }) {
	return /* @__PURE__ */ react.default.createElement("svg", {
		width: size,
		height: size,
		viewBox: "0 0 24 24",
		fill: "none",
		stroke: "currentColor",
		strokeWidth: "1.6",
		"aria-hidden": "true"
	}, /* @__PURE__ */ react.default.createElement("circle", {
		cx: "6",
		cy: "5",
		r: "2"
	}), /* @__PURE__ */ react.default.createElement("circle", {
		cx: "6",
		cy: "19",
		r: "2"
	}), /* @__PURE__ */ react.default.createElement("circle", {
		cx: "18",
		cy: "5",
		r: "2"
	}), /* @__PURE__ */ react.default.createElement("path", { d: "M6 7v10m12-10c0 6-12 3-12 8" }));
}
function Dialog({ title, children, footer, onClose, busy = false }) {
	const root = (0, react.useRef)(null);
	const close = (0, react.useRef)(onClose);
	close.current = onClose;
	(0, react.useEffect)(() => {
		const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null;
		const node = root.current;
		node?.querySelector("button:not(:disabled)")?.focus();
		const handleKey = (event) => {
			if (event.key === "Escape") {
				event.preventDefault();
				event.stopPropagation();
				if (!busy) close.current();
			}
			if (event.key !== "Tab" || !node) return;
			const controls = [...node.querySelectorAll("button:not(:disabled), input:not(:disabled), [tabindex=\"0\"]")];
			const first = controls[0];
			const last = controls.at(-1);
			if (!first || !last) {
				event.preventDefault();
				node.focus();
				return;
			}
			if (event.shiftKey && (document.activeElement === first || !node.contains(document.activeElement))) {
				event.preventDefault();
				last.focus();
			}
			if (!event.shiftKey && (document.activeElement === last || !node.contains(document.activeElement))) {
				event.preventDefault();
				first.focus();
			}
		};
		document.addEventListener("keydown", handleKey, true);
		return () => {
			document.removeEventListener("keydown", handleKey, true);
			previous?.focus();
		};
	}, [busy]);
	const titleId = react.default.useId();
	return /* @__PURE__ */ react.default.createElement("div", { style: {
		position: "fixed",
		pointerEvents: "auto",
		inset: 0,
		zIndex: 1e3,
		background: "rgb(0 0 0 / 35%)",
		display: "grid",
		placeItems: "center",
		padding: 20
	} }, /* @__PURE__ */ react.default.createElement("div", {
		ref: root,
		tabIndex: -1,
		role: "dialog",
		"aria-modal": "true",
		"aria-labelledby": titleId,
		style: {
			...surface,
			padding: 24,
			width: "min(560px, 100%)",
			maxHeight: "85vh",
			overflow: "auto",
			boxShadow: "0 12px 48px rgb(0 0 0 / 20%)"
		}
	}, /* @__PURE__ */ react.default.createElement("h2", {
		id: titleId,
		style: {
			fontSize: 18,
			margin: "0 0 16px"
		}
	}, title), children, /* @__PURE__ */ react.default.createElement("div", { style: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: 8,
		marginTop: 20
	} }, footer)));
}
function SessionWorktreesPage({ store }) {
	const state = (0, react.useSyncExternalStore)(store.subscribe, store.getSnapshot);
	const records = state.records;
	const error = state.error ?? state.readError;
	return /* @__PURE__ */ react.default.createElement("section", {
		"aria-label": "Session worktrees",
		style: {
			padding: 28,
			overflow: "auto",
			height: "100%",
			boxSizing: "border-box",
			color: "var(--dsw-alias-label-primary)"
		}
	}, /* @__PURE__ */ react.default.createElement("div", { style: {
		display: "flex",
		alignItems: "center",
		gap: 16
	} }, /* @__PURE__ */ react.default.createElement("h1", { style: { fontSize: 22 } }, "Session worktrees"), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		onClick: () => {
			store.refresh();
		}
	}, "Refresh")), /* @__PURE__ */ react.default.createElement("p", null, "Owned session checkouts remain recoverable here, including archived sessions whose checkout is missing."), /* @__PURE__ */ react.default.createElement("p", { style: { color: "var(--dsw-alias-label-tertiary)" } }, "Use Restore and open before continuing an archived session. Native unarchive actions do not recreate a removed checkout. Turning off Use worktree keeps its checkout."), error && /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error), state.loading && /* @__PURE__ */ react.default.createElement("p", { role: "status" }, "Loading session worktrees…"), !state.loading && records.length === 0 && /* @__PURE__ */ react.default.createElement("p", null, "No session worktrees yet."), /* @__PURE__ */ react.default.createElement("div", { style: {
		display: "grid",
		gap: 16,
		marginTop: 20
	} }, records.map((record) => /* @__PURE__ */ react.default.createElement("article", {
		key: record.sessionId,
		style: {
			...surface,
			padding: 18
		}
	}, /* @__PURE__ */ react.default.createElement("div", { style: {
		display: "flex",
		flexWrap: "wrap",
		alignItems: "center",
		gap: 10
	} }, /* @__PURE__ */ react.default.createElement(BranchIcon, null), /* @__PURE__ */ react.default.createElement("strong", null, record.branch), /* @__PURE__ */ react.default.createElement("span", null, record.state)), /* @__PURE__ */ react.default.createElement("dl", { style: {
		fontSize: 13,
		overflowWrap: "anywhere"
	} }, /* @__PURE__ */ react.default.createElement("dt", null, "Checkout"), /* @__PURE__ */ react.default.createElement("dd", { style: { margin: "4px 0 12px" } }, /* @__PURE__ */ react.default.createElement("code", null, record.path)), /* @__PURE__ */ react.default.createElement("dt", null, "Source"), /* @__PURE__ */ react.default.createElement("dd", { style: { margin: "4px 0 12px" } }, record.repository, " · ", record.sourceRef ?? "HEAD", " · ", record.sourceWorkspaceId), /* @__PURE__ */ react.default.createElement("dt", null, "Session"), /* @__PURE__ */ react.default.createElement("dd", { style: { margin: "4px 0 12px" } }, record.sessionId), /* @__PURE__ */ react.default.createElement("dt", null, "HEAD"), /* @__PURE__ */ react.default.createElement("dd", { style: { margin: "4px 0" } }, /* @__PURE__ */ react.default.createElement("code", null, record.head), record.branchDeleted ? " · Branch removed" : "")), record.message && /* @__PURE__ */ react.default.createElement("p", null, record.message), /* @__PURE__ */ react.default.createElement("div", { style: {
		display: "flex",
		flexWrap: "wrap",
		gap: 8
	} }, record.state === "active" && /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		disabled: state.busy.has(record.sessionId),
		onClick: () => {
			store.archive(record.sessionId);
		}
	}, "Archive session"), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		disabled: state.busy.has(record.sessionId) || record.state === "creating",
		onClick: () => {
			store.restore(record.sessionId);
		}
	}, "Restore and open"), record.state !== "removed" && /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		disabled: state.busy.has(record.sessionId) || record.state === "creating",
		onClick: () => {
			store.cleanup(record.sessionId);
		}
	}, record.state === "pending" ? "Review cleanup" : "Retry cleanup"))))));
}
function SessionOverlay({ store }) {
	const state = (0, react.useSyncExternalStore)(store.subscribe, store.getSnapshot);
	const dialog = state.dialog;
	const error = state.error ?? state.readError;
	const pending = state.records.filter((record) => record.state === "pending") ?? [];
	if (dialog) {
		const busy = state.busy.has(dialog.record.sessionId);
		return /* @__PURE__ */ react.default.createElement(Dialog, {
			title: "Remove archived session checkout?",
			busy,
			onClose: store.keepCheckout,
			footer: /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("button", {
				type: "button",
				style: action,
				disabled: busy,
				onClick: store.keepCheckout
			}, "Keep checkout"), /* @__PURE__ */ react.default.createElement("button", {
				type: "button",
				style: {
					...action,
					color: "var(--dsw-alias-label-danger, #c43c3c)"
				},
				disabled: busy || Date.now() >= dialog.confirmation.expiresAt,
				onClick: () => {
					store.discardCheckout();
				}
			}, "Discard files and remove checkout"))
		}, /* @__PURE__ */ react.default.createElement("p", null, "This checkout contains files that cleanup would discard. This action cannot be undone."), /* @__PURE__ */ react.default.createElement("p", { style: { overflowWrap: "anywhere" } }, /* @__PURE__ */ react.default.createElement("code", null, dialog.record.path)), /* @__PURE__ */ react.default.createElement("p", null, "Branch: ", /* @__PURE__ */ react.default.createElement("strong", null, dialog.record.branch)), /* @__PURE__ */ react.default.createElement("p", { style: { overflowWrap: "anywhere" } }, "HEAD: ", /* @__PURE__ */ react.default.createElement("code", null, dialog.confirmation.head)), /* @__PURE__ */ react.default.createElement("ul", { style: {
			maxHeight: 200,
			overflow: "auto",
			overflowWrap: "anywhere"
		} }, dialog.confirmation.files.map((file, index) => /* @__PURE__ */ react.default.createElement("li", { key: `${index}:${file}` }, /* @__PURE__ */ react.default.createElement("code", null, file)))), /* @__PURE__ */ react.default.createElement("p", { style: { fontSize: 12 } }, "Review expires at ", new Date(dialog.confirmation.expiresAt).toLocaleTimeString(), ". If files or HEAD change, keep the checkout and request a new review."), error && /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error));
	}
	if (!pending.length && !error) return null;
	return /* @__PURE__ */ react.default.createElement("aside", {
		"aria-label": "Session worktree notice",
		style: {
			...surface,
			position: "fixed",
			pointerEvents: "auto",
			bottom: 20,
			right: 20,
			zIndex: 100,
			padding: 14,
			maxWidth: 360
		}
	}, error && /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("p", {
		role: "alert",
		style: { margin: "0 0 8px" }
	}, error), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		onClick: store.dismissError
	}, "Dismiss"), state.readError && /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		onClick: () => {
			store.refresh();
		}
	}, "Retry")), pending.length > 0 && /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("p", { style: { margin: "0 0 8px" } }, pending.length, " archived session checkout", pending.length === 1 ? "" : "s", " need cleanup review. Kept files remain on disk."), /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		style: action,
		disabled: state.busy.has(pending[0].sessionId),
		onClick: () => {
			store.cleanup(pending[0].sessionId);
		}
	}, "Review cleanup")));
}
function SessionLeading(props) {
	const record = (0, react.useSyncExternalStore)(props.store.subscribe, props.store.getSnapshot).records.find((row) => row.sessionId === props.sessionId);
	return record ? /* @__PURE__ */ react.default.createElement("span", {
		title: `Session worktree: ${record.branch}`,
		style: { display: "inline-flex" }
	}, /* @__PURE__ */ react.default.createElement(BranchIcon, null)) : null;
}
function SessionHover(props) {
	const record = (0, react.useSyncExternalStore)(props.store.subscribe, props.store.getSnapshot).records.find((row) => row.sessionId === props.sessionId);
	return record ? /* @__PURE__ */ react.default.createElement("div", { style: {
		fontSize: 12,
		maxWidth: 320,
		overflowWrap: "anywhere"
	} }, /* @__PURE__ */ react.default.createElement("strong", null, "Session worktree"), /* @__PURE__ */ react.default.createElement("div", null, record.branch, " · ", record.state), /* @__PURE__ */ react.default.createElement("div", null, record.path), /* @__PURE__ */ react.default.createElement("div", null, "Source: ", record.repository), record.message && /* @__PURE__ */ react.default.createElement("div", null, record.message)) : null;
}
function CopyCheckout(props) {
	const state = (0, react.useSyncExternalStore)(props.store.subscribe, props.store.getSnapshot);
	const [, close] = props.useMenuOpenState();
	const record = state.records.find((row) => row.sessionId === props.sessionId);
	if (!record) return null;
	return /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		role: "menuitem",
		style: {
			...action,
			width: "100%",
			textAlign: "left"
		},
		onClick: () => {
			close(false);
			navigator.clipboard.writeText(record.path).catch(props.store.report);
		}
	}, "Copy checkout path");
}

//#endregion
//#region client/directory-alias.ts
const DIRECTORY_ALIAS = "conversation.hero.worktree.directoryFlow";
const SOURCE = "conversation.hero.workspace.directoryFlow";
/** RC2 child declarations belong to ONE entry. Use a plugin-owned hole and
* re-register the native flow's public component/inject/locale into it, with
* the same root scope and owner contract. Never mutate native StoredEntry data
* or redeclare its child. Preserve provider disposal/replacement via the ledger.
*/
function mountDirectoryAlias(ctx) {
	ctx.slots.inject(DIRECTORY_ALIAS, () => {
		let previous;
		let unregister;
		const reconcile = () => {
			const entry = [...ctx.slots.entries(SOURCE)].sort((a, b) => (a.options.priority ?? 0) - (b.options.priority ?? 0))[0];
			if (entry === previous) return;
			unregister?.();
			unregister = void 0;
			previous = entry;
			if (!entry || entry.store || entry.children || entry.select || typeof entry.component !== "function") return;
			unregister = ctx.slots.register({
				name: DIRECTORY_ALIAS,
				...entry.locale ? { locale: entry.locale } : {},
				...entry.inject ? { inject: entry.inject } : {}
			}, entry.component);
		};
		const unsubscribe = ctx.slots.subscribe(SOURCE, reconcile);
		reconcile();
		return () => {
			unsubscribe();
			unregister?.();
		};
	});
}

//#endregion
//#region client/session-picker.tsx
const absent = {
	getSnapshot: () => void 0,
	subscribe: (_listener) => () => {}
};
function SessionPicker(props) {
	const { ctx, store } = props;
	const state = (0, react.useSyncExternalStore)(store.subscribe, store.getSnapshot);
	const summary = props.useSessions((list) => {
		const selected = Object.values(list.byId).filter((row) => (row.retainedBy.mainView ?? 0) > 0);
		return selected.length === 1 ? selected[0] : void 0;
	});
	const boundSession = (id) => {
		try {
			return ctx.sessions.binding(id)?.session;
		} catch (error) {
			if (error instanceof Error && error.message.startsWith("uiConversation.binding: unknown session")) return void 0;
			throw error;
		}
	};
	const liveSource = summary ? boundSession(summary.id) ?? absent : absent;
	const live = (0, react.useSyncExternalStore)(react.default.useCallback((listener) => liveSource.subscribe(listener), [liveSource]), react.default.useCallback(() => liveSource.getSnapshot(), [liveSource]));
	const blank = Boolean(live?.blank && !live.promptAttempted);
	const workspaceSnapshot = props.useWorkspaces((value) => value);
	const available = props.useDirectoryFlow((value) => value);
	const [flowOpen, setFlowOpen] = (0, react.useState)(false);
	const [adopting, setAdopting] = (0, react.useState)(false);
	const [folderError, setFolderError] = (0, react.useState)(null);
	const [menuPosition, setMenuPosition] = (0, react.useState)({
		top: 0,
		left: 0
	});
	const menu = (0, react.useRef)(null);
	const attempted = (0, react.useRef)(/* @__PURE__ */ new Set());
	const preferenceBusy = (0, react.useRef)(false);
	const [saving, setSaving] = (0, react.useState)(false);
	const [requested, setRequested] = (0, react.useState)(null);
	(0, react.useEffect)(() => {
		setRequested(null);
	}, [summary?.id, props.selectedId]);
	const latest = (0, react.useRef)({
		sessionId: summary?.id,
		workspaceId: props.selectedId,
		blank,
		onPick: props.onPick
	});
	latest.current = {
		sessionId: summary?.id,
		workspaceId: props.selectedId,
		blank,
		onPick: props.onPick
	};
	const ready = state.sessionId === summary?.id && !state.loading && state.status !== null && (state.status.sourceWorkspaceId === props.selectedId || state.status.current?.workspaceId === props.selectedId);
	const managed = ready ? state.status?.current ?? state.status?.records.find((record) => record.sessionId === summary?.id) : void 0;
	const source = managed?.sourceWorkspaceId ?? state.status?.sourceWorkspaceId;
	const wantsWorktree = requested ?? Boolean(ready && state.status?.defaultEnabled);
	const checked = Boolean(managed || wantsWorktree);
	const busy = saving || Boolean(summary && state.busy.has(summary.id));
	const identityMatches = (sessionId, workspaceId) => {
		const current = latest.current;
		const session = boundSession(sessionId)?.getSnapshot();
		return current.sessionId === sessionId && current.workspaceId === workspaceId && current.blank && currentSession(ctx) === sessionId && Boolean(session?.blank && !session.promptAttempted);
	};
	const create = (sessionId, workspaceId) => store.create(sessionId, (record) => {
		if (record.workspaceId && identityMatches(sessionId, workspaceId)) latest.current.onPick(record.workspaceId);
	});
	(0, react.useLayoutEffect)(() => {
		if (!summary || !blank) return;
		if (state.loading || wantsWorktree && !managed) store.block(summary.id, busy || state.loading ? "Preparing session worktree…" : "Worktree requested. Turn off Use worktree to continue in the shared checkout.");
		else if (!state.busy.has(summary.id)) store.clearBlock(summary.id);
		return () => {
			if (!state.busy.has(summary.id)) store.clearBlock(summary.id);
		};
	}, [
		summary?.id,
		blank,
		ready,
		state.loading,
		state.status,
		managed,
		state.busy,
		wantsWorktree,
		busy,
		store
	]);
	(0, react.useEffect)(() => {
		if (!summary || !blank || !ready || managed || busy || !props.selectedId || !state.status?.defaultEnabled || !state.status.canCreate || requested === false) return;
		if (state.status.sourceWorkspaceId !== props.selectedId) return;
		const key = `${summary.id}:${props.selectedId}`;
		if (attempted.current.has(key)) return;
		attempted.current.add(key);
		create(summary.id, props.selectedId);
	}, [
		summary?.id,
		blank,
		ready,
		managed,
		busy,
		props.selectedId,
		state.status,
		requested,
		store
	]);
	async function toggle(enabled) {
		if (!summary || !props.selectedId || !source || !ready || busy || preferenceBusy.current) return;
		const sessionId = summary.id;
		const workspaceId = props.selectedId;
		preferenceBusy.current = true;
		setRequested(enabled);
		setSaving(true);
		if (enabled) store.block(sessionId);
		try {
			await store.request("preference", {
				workspaceId: source,
				enabled
			});
			if (!identityMatches(sessionId, workspaceId)) return;
			if (enabled && !managed) {
				attempted.current.add(`${sessionId}:${workspaceId}`);
				await create(sessionId, workspaceId);
			} else if (!enabled && managed) latest.current.onPick(managed.sourceWorkspaceId);
		} catch (error) {
			store.report(error);
		} finally {
			preferenceBusy.current = false;
			setSaving(false);
			if (!enabled) store.clearBlock(sessionId);
			store.refresh();
		}
	}
	(0, react.useEffect)(() => {
		if (!available) setFlowOpen(false);
	}, [available]);
	const openDirectory = () => {
		props.onClose();
		setFolderError(null);
		setFlowOpen(true);
	};
	(0, react.useEffect)(() => {
		if (props.open && workspaceSnapshot.phase === "ready" && workspaceSnapshot.items.length === 0 && available && !flowOpen && !adopting) openDirectory();
	}, [
		props.open,
		workspaceSnapshot.phase,
		workspaceSnapshot.items.length,
		available,
		flowOpen,
		adopting
	]);
	(0, react.useLayoutEffect)(() => {
		if (!props.open) return;
		const position = () => {
			const rect = props.anchorRef?.current?.getBoundingClientRect();
			if (rect) setMenuPosition({
				top: Math.min(rect.bottom + 6, window.innerHeight - 100),
				left: Math.max(8, Math.min(rect.left, window.innerWidth - 300))
			});
		};
		position();
		window.addEventListener("resize", position);
		window.addEventListener("scroll", position, true);
		return () => {
			window.removeEventListener("resize", position);
			window.removeEventListener("scroll", position, true);
		};
	}, [props.open, props.anchorRef]);
	(0, react.useEffect)(() => {
		if (!props.open) return;
		menu.current?.querySelector("[role=\"menuitemradio\"][aria-checked=\"true\"], button")?.focus();
		const outside = (event) => {
			const target = event.target;
			if (target instanceof Node && !menu.current?.contains(target) && !props.anchorRef?.current?.contains(target)) props.onClose();
		};
		const key = (event) => {
			if (event.key === "Escape") {
				event.preventDefault();
				event.stopPropagation();
				props.onClose();
				props.anchorRef?.current?.focus();
			}
			if (event.key === "Tab") props.onClose();
			if (![
				"ArrowDown",
				"ArrowUp",
				"Home",
				"End"
			].includes(event.key)) return;
			const items = [...menu.current?.querySelectorAll("button:not(:disabled)") ?? []];
			if (!items.length) return;
			event.preventDefault();
			const index = items.indexOf(document.activeElement);
			items[event.key === "Home" ? 0 : event.key === "End" ? items.length - 1 : (index + (event.key === "ArrowDown" ? 1 : -1) + items.length) % items.length]?.focus();
		};
		document.addEventListener("pointerdown", outside);
		document.addEventListener("keydown", key, true);
		return () => {
			document.removeEventListener("pointerdown", outside);
			document.removeEventListener("keydown", key, true);
		};
	}, [
		props.open,
		props.onClose,
		props.anchorRef
	]);
	const folderFailure = (message) => {
		setFlowOpen(false);
		setFolderError(message);
	};
	const pickWorkspace = (workspaceId) => {
		props.onClose();
		props.onPick(workspaceId);
	};
	const menuOpen = props.open && (workspaceSnapshot.items.length > 0 || !available);
	return /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, blank && /* @__PURE__ */ react.default.createElement("label", {
		style: {
			display: "inline-flex",
			alignItems: "center",
			gap: 6,
			fontSize: 13,
			whiteSpace: "nowrap"
		},
		title: ready ? state.status?.reason || "Remember this choice for the source workspace. Turning off keeps the checkout." : "Checking worktree availability…"
	}, /* @__PURE__ */ react.default.createElement("input", {
		type: "checkbox",
		checked,
		disabled: !ready || busy || !checked && !state.status?.canCreate,
		onChange: (event) => {
			toggle(event.target.checked);
		}
	}), busy ? "Preparing worktree…" : "Use worktree"), menuOpen && /* @__PURE__ */ react.default.createElement("div", {
		ref: menu,
		role: "menu",
		"aria-label": "Workspaces",
		style: {
			...surface,
			position: "fixed",
			...menuPosition,
			width: 290,
			maxHeight: "min(420px, 65vh)",
			overflow: "auto",
			padding: 6,
			zIndex: 500,
			boxShadow: "0 6px 24px rgb(0 0 0 / 15%)"
		}
	}, workspaceSnapshot.items.map((workspace) => /* @__PURE__ */ react.default.createElement("button", {
		key: workspace.workspaceId,
		type: "button",
		role: "menuitemradio",
		"aria-checked": props.selectedId === workspace.workspaceId,
		disabled: adopting,
		title: workspace.path,
		style: {
			...action,
			display: "block",
			width: "100%",
			textAlign: "left",
			marginBottom: 3
		},
		onClick: () => pickWorkspace(workspace.workspaceId)
	}, workspace.title || "Default workspace", props.selectedId === workspace.workspaceId ? " ✓" : "")), workspaceSnapshot.phase === "pending" && /* @__PURE__ */ react.default.createElement("p", { role: "status" }, "Loading workspaces…"), available && /* @__PURE__ */ react.default.createElement("button", {
		type: "button",
		role: "menuitem",
		disabled: adopting,
		style: {
			...action,
			width: "100%",
			textAlign: "left"
		},
		onClick: openDirectory
	}, "Add workspace…"), !available && workspaceSnapshot.items.length === 0 && /* @__PURE__ */ react.default.createElement("p", null, "No workspaces available.")), props.renderSlot(DIRECTORY_ALIAS, {
		open: flowOpen,
		busy: adopting,
		onPicked: (path) => {
			if (adopting) return;
			setAdopting(true);
			props.createWorkspace({ path }).then((workspace) => {
				setFlowOpen(false);
				pickWorkspace(workspace.workspaceId);
			}).catch((error) => folderFailure(error instanceof Error ? error.message : "Could not add workspace.")).finally(() => setAdopting(false));
		},
		onCancel: () => setFlowOpen(false),
		onError: folderFailure
	}), folderError && /* @__PURE__ */ react.default.createElement(Dialog, {
		title: "Could not add workspace",
		onClose: () => setFolderError(null),
		footer: /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("button", {
			type: "button",
			style: action,
			onClick: () => setFolderError(null)
		}, "Cancel"), /* @__PURE__ */ react.default.createElement("button", {
			type: "button",
			style: action,
			disabled: !available,
			onClick: openDirectory
		}, "Choose again"))
	}, /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, folderError)));
}

//#endregion
//#region client/session-slot.tsx
function mountHeroPicker(ctx, store) {
	const directoryFlow = {
		getSnapshot: () => ctx.slots.entries(DIRECTORY_ALIAS).length > 0,
		subscribe: (listener) => ctx.slots.subscribe(DIRECTORY_ALIAS, listener)
	};
	ctx.slots.inject("conversation.hero.workspace", () => ctx.slots.register({
		name: "conversation.hero.workspace",
		priority: -10,
		children: { [DIRECTORY_ALIAS]: {
			kind: "single",
			scope: "root"
		} },
		locale: "workspace",
		inject: () => ({
			createWorkspace: (input) => ctx.workspaces.create(input),
			hooks: { directoryFlow }
		})
	}, (props) => /* @__PURE__ */ react.default.createElement(SessionPicker, {
		...props,
		ctx,
		store
	})));
	mountDirectoryAlias(ctx);
}

//#endregion
//#region client/session-registration.tsx
function mountSessionClient(ctx) {
	const store = createSessionStore(ctx);
	ctx.effect(() => store.start());
	mountHeroPicker(ctx, store);
	ctx.slots.inject("sidebar.session.row.leading", () => ctx.slots.register({
		name: "sidebar.session.row.leading",
		id: "local-worktree-session",
		order: 30
	}, (props) => /* @__PURE__ */ react.default.createElement(SessionLeading, {
		...props,
		store
	})));
	ctx.slots.inject("sidebar.session.row.hover", () => ctx.slots.register({
		name: "sidebar.session.row.hover",
		id: "local-worktree-session",
		order: 30
	}, (props) => /* @__PURE__ */ react.default.createElement(SessionHover, {
		...props,
		store
	})));
	ctx.slots.inject("sidebar.workspaces.session.menu.item", () => ctx.slots.register({
		name: "sidebar.workspaces.session.menu.item",
		id: "local-worktree-copy-checkout",
		order: 350
	}, (props) => /* @__PURE__ */ react.default.createElement(CopyCheckout, {
		...props,
		store
	})));
	ctx.slots.inject("sidebar.panellist", () => shellSeats(ctx).register({
		name: "sidebar.panellist",
		id: "local-session-worktrees",
		order: 15,
		label: "Session worktrees"
	}, BranchIcon));
	ctx.slots.inject("main", () => shellSeats(ctx).register({
		name: "main",
		key: "local-session-worktrees"
	}, () => /* @__PURE__ */ react.default.createElement(SessionWorktreesPage, { store })));
	ctx.slots.inject("shell.overlay", () => shellSeats(ctx).register({
		name: "shell.overlay",
		id: "local-session-worktrees",
		order: 30
	}, () => /* @__PURE__ */ react.default.createElement(SessionOverlay, { store })));
}

//#endregion
//#region client/index.ts
var client_default = {
	name: "local-worktrees",
	inject: [
		"slots",
		"sessions",
		"connection",
		"jobs"
	],
	apply(ctx) {
		ctx.inject?.([
			"workspaces",
			"uiWorkspace",
			"conversation"
		], mountSessionClient);
		ctx.slots.inject("conversation.view", () => {
			const jobs = ctx.jobs;
			const rpc = ctx.connection.rpc;
			return watchCapability({
				sessions: ctx.sessions,
				rpc,
				register: (sessionId) => {
					const reference = ctx.sessions.retain?.(sessionId, { source: "worktreeTab" });
					reference?.ready.catch(() => {});
					const dispose = ctx.slots.register({
						name: "conversation.view",
						id: "worktrees",
						order: 20,
						label: "Worktrees",
						inject: (viewed) => ({ sessionId: viewed })
					}, (props) => props.sessionId === sessionId ? react.createElement(Panel, {
						key: sessionId,
						sessionId,
						jobs,
						rpc
					}) : null);
					return () => {
						dispose();
						if (reference) queueMicrotask(() => reference.release());
					};
				}
			});
		});
	},
	createReader,
	watchCapability,
	Panel
};

//#endregion
exports.default = client_default;
return module.exports.default; } });