// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-worktree", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region shared/contracts.ts
const CHANNEL = "/local-worktrees";

//#endregion
//#region client/reader.ts
function record(value) {
	return typeof value === "object" && value !== null ? value : {};
}
function hasSnapshotEnvelope(value, sessionId) {
	return value.sessionId === sessionId && typeof value.state === "string" && [
		"ready",
		"disabled",
		"unavailable",
		"error"
	].includes(value.state);
}
function unwrap(input, sessionId) {
	const result = record(input);
	if (result?.ok !== true) throw new Error("Worktrees RPC failed.");
	const value = record(result.value);
	if (!hasSnapshotEnvelope(value, sessionId)) throw new Error("Invalid Worktrees response.");
	return value;
}
function createReader(rpc, sessionId, publish) {
	let generation = 0;
	let disposed = false;
	let selection = {};
	let value;
	return {
		async refresh(next = selection) {
			selection = next;
			const token = ++generation;
			publish({
				value,
				loading: true
			});
			try {
				const result = unwrap(await rpc.call(CHANNEL, "snapshot", {
					sessionId,
					...selection
				}), sessionId);
				if (disposed || token !== generation) return;
				if (result.state === "error" || result.state === "ready" && !Array.isArray(result.worktrees)) throw new Error("Invalid Worktrees snapshot.");
				if (result.state === "ready" && result.selected) {
					selection = {
						...selection,
						path: result.selected.path
					};
					if (result.selected.run) selection.runId = result.selected.run.id;
				}
				value = result;
				publish({
					value,
					loading: false
				});
			} catch {
				if (!disposed && token === generation) publish({
					loading: false,
					error: "Worktrees could not refresh. Try again."
				});
			}
		},
		dispose() {
			disposed = true;
			generation++;
		}
	};
}

//#endregion
//#region client/panel.tsx
const visible = () => document.visibilityState !== "hidden";
const panelCss = `
  .wt-panel{--wt-border:var(--dsw-alias-border-l2,#8884);--wt-muted:var(--dsw-alias-label-secondary,#888);--wt-accent:var(--dsw-alias-state-business-primary,#598be8);color:var(--dsw-alias-label-primary,inherit);font:13px/1.5 system-ui,sans-serif;padding:24px;box-sizing:border-box;overflow:auto;height:100%;container-type:inline-size}
  .wt-panel *{box-sizing:border-box}.wt-panel h2,.wt-panel h3,.wt-panel h4,.wt-panel p{margin:0}.wt-panel h2{font-size:20px;letter-spacing:-.4px}.wt-panel h3{font-size:18px;overflow-wrap:anywhere}.wt-panel h4{font-size:13px;font-weight:600}.wt-panel button{font:inherit;cursor:pointer;color:inherit;border:1px solid var(--wt-border);background:transparent;border-radius:8px;padding:7px 11px}.wt-panel button:hover{background:var(--dsw-alias-interactive-bg-hover,#8881)}.wt-panel button:focus-visible{outline:2px solid var(--wt-accent);outline-offset:3px}.wt-panel button:disabled{opacity:.5;cursor:wait}
  .wt-header,.wt-title,.wt-section-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.wt-header{margin-bottom:24px}.wt-subtitle,.wt-path,.wt-muted{color:var(--wt-muted)}.wt-subtitle{margin-top:4px!important}.wt-path{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere;margin-top:6px!important}.wt-layout{display:grid;grid-template-columns:minmax(230px,300px) minmax(0,1fr);gap:24px;max-width:1280px}.wt-list{list-style:none;padding:0;margin:10px 0;display:grid;gap:6px;align-content:start}.wt-panel .wt-card{display:block;width:100%;text-align:left;padding:14px;border-color:transparent}.wt-panel .wt-card[aria-pressed=true]{border-color:var(--wt-accent);background:color-mix(in srgb,var(--wt-accent) 9%,transparent)}.wt-card-name{font-weight:600;display:block;overflow-wrap:anywhere}.wt-branch{display:block;color:var(--wt-muted);font:12px/1.5 ui-monospace,monospace;overflow-wrap:anywhere;margin:3px 0 10px}.wt-badges{display:flex;gap:6px;flex-wrap:wrap}.wt-badge{display:inline-flex;font-size:11px;padding:2px 7px;border:1px solid var(--wt-border);border-radius:20px;color:var(--wt-muted)}.wt-badge[data-state=busy],.wt-badge[data-state=running]{color:var(--wt-accent);border-color:currentColor}.wt-badge[data-state=failed]{color:var(--dsw-alias-state-error-primary,#d86161)}.wt-assignment{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;color:var(--wt-muted);font-size:12px;margin-top:10px}
  .wt-detail{min-width:0;border:1px solid var(--wt-border);border-radius:12px;padding:24px;background:var(--dsw-alias-bg-layer-1,transparent)}.wt-section{margin-top:24px;padding-top:20px;border-top:1px solid var(--wt-border)}.wt-empty{padding:24px 14px;text-align:center;color:var(--wt-muted);border:1px dashed var(--wt-border);border-radius:8px;margin-top:12px!important}.wt-files{list-style:none;padding:0;margin:12px 0 0;max-height:230px;overflow:auto}.wt-files li{display:flex;gap:12px;padding:7px 0;border-bottom:1px solid var(--wt-border);font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}.wt-files code{flex:none;color:var(--wt-accent);white-space:pre}.wt-runs{list-style:none;padding:0;margin:12px 0;display:grid;gap:6px}.wt-panel .wt-run{width:100%;text-align:left;display:flex;gap:12px;align-items:center;padding:10px 12px}.wt-run[aria-pressed=true]{border-color:var(--wt-accent);background:color-mix(in srgb,var(--wt-accent) 7%,transparent)}.wt-run .wt-badge{margin-left:auto}.wt-report{margin-top:16px}.wt-panel pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.7 ui-monospace,monospace;background:var(--dsw-alias-interactive-bg-hover,#8881);border-radius:8px;padding:14px;max-height:320px;overflow:auto;margin:8px 0 16px}.wt-refresh{display:flex;align-items:center;gap:12px}.wt-refresh-status{color:var(--wt-muted);font-size:12px}.wt-notice{margin-bottom:12px!important;color:var(--wt-muted)}.wt-copy-status{font-size:12px;color:var(--wt-muted);margin-top:8px;display:block}.wt-count{font-size:11px;font-weight:400;border:1px solid var(--wt-border);border-radius:20px;padding:1px 7px;margin-left:6px}
  @container(max-width:700px){.wt-layout{grid-template-columns:1fr}.wt-list{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))}.wt-detail{padding:16px}.wt-title{align-items:flex-start;flex-wrap:wrap}.wt-header{align-items:flex-start}}@media(max-width:500px){.wt-panel{padding:16px}}
`;
function Panel({ rpc, jobs, sessionId }) {
	const [state, setState] = react.useState({ loading: true });
	const [copied, setCopied] = react.useState("");
	const readerRef = react.useRef();
	react.useEffect(() => {
		const reader = createReader(rpc, sessionId, setState);
		readerRef.current = reader;
		const refresh = () => {
			if (visible()) reader.refresh();
		};
		const unwatch = jobs.watchRows(sessionId);
		let rows = jobs.state.getSnapshot().rows[sessionId];
		const off = jobs.state.subscribe(() => {
			const next = jobs.state.getSnapshot().rows[sessionId];
			if (next !== rows) {
				rows = next;
				refresh();
			}
		});
		refresh();
		const timer = setInterval(refresh, 1e4);
		document.addEventListener("visibilitychange", refresh);
		return () => {
			reader.dispose();
			off();
			unwatch();
			clearInterval(timer);
			document.removeEventListener("visibilitychange", refresh);
		};
	}, [
		rpc,
		sessionId,
		jobs
	]);
	const value = state.value;
	const selected = value?.selected;
	const choose = (selection) => {
		setCopied("");
		readerRef.current?.refresh(selection);
	};
	const button = (text, onClick, extra = {}) => /* @__PURE__ */ react.createElement("button", {
		type: "button",
		onClick,
		...extra
	}, text);
	const badge = (text, status) => /* @__PURE__ */ react.createElement("span", {
		className: "wt-badge",
		"data-state": status
	}, text);
	const selectedRow = value?.worktrees?.find((row) => row.path === selected?.path);
	return /* @__PURE__ */ react.createElement("section", {
		"aria-label": "Worktrees",
		className: "wt-panel"
	}, /* @__PURE__ */ react.createElement("style", null, panelCss), /* @__PURE__ */ react.createElement("div", { className: "wt-header" }, /* @__PURE__ */ react.createElement("div", null, /* @__PURE__ */ react.createElement("h2", null, "Worktrees"), /* @__PURE__ */ react.createElement("p", { className: "wt-subtitle" }, "Repository checkouts · Session activity")), /* @__PURE__ */ react.createElement("div", { className: "wt-refresh" }, /* @__PURE__ */ react.createElement("span", {
		className: "wt-refresh-status",
		role: "status",
		style: { visibility: state.loading && value ? "visible" : "hidden" }
	}, "Updating…"), button("Refresh", () => readerRef.current?.refresh(), { disabled: state.loading && !value }))), state.loading && !value && /* @__PURE__ */ react.createElement("p", { role: "status" }, "Loading worktrees…"), state.error && /* @__PURE__ */ react.createElement("p", { role: "alert" }, state.error), value?.state === "error" && /* @__PURE__ */ react.createElement("p", { role: "alert" }, value.message), (value?.state === "unavailable" || value?.state === "disabled") && /* @__PURE__ */ react.createElement("p", { role: "status" }, "Worktree integration is unavailable for this session."), value?.state === "ready" && value.worktrees && /* @__PURE__ */ react.createElement("div", { className: "wt-layout" }, /* @__PURE__ */ react.createElement("nav", { "aria-label": "Repository worktrees" }, /* @__PURE__ */ react.createElement("div", { className: "wt-section-title" }, /* @__PURE__ */ react.createElement("h4", null, "Checkouts"), badge(String(value.worktrees.length))), /* @__PURE__ */ react.createElement("p", {
		className: "wt-path",
		title: value.repository
	}, value.repository), value.truncated && /* @__PURE__ */ react.createElement("p", { className: "wt-muted" }, "Showing the first 100 repository worktrees."), value.worktrees.length === 0 && /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "No worktrees found."), /* @__PURE__ */ react.createElement("ul", { className: "wt-list" }, value.worktrees.map((row) => /* @__PURE__ */ react.createElement("li", { key: row.path }, button(/* @__PURE__ */ react.createElement(react.Fragment, null, /* @__PURE__ */ react.createElement("span", { className: "wt-card-name" }, row.name), /* @__PURE__ */ react.createElement("span", { className: "wt-branch" }, row.branch ?? "detached / bare"), /* @__PURE__ */ react.createElement("span", { className: "wt-badges" }, badge(`Worker: ${row.workerStatus}`, row.workerStatus), badge(row.changes.error !== void 0 ? "Git unavailable" : row.changes.count === 0 ? "Clean" : `${row.changes.count} changed ${row.changes.count === 1 ? "file" : "files"}`)), row.cleanupUncertain && /* @__PURE__ */ react.createElement("span", { className: "wt-assignment" }, "Cleanup uncertain"), row.latestAssignment && /* @__PURE__ */ react.createElement("span", { className: "wt-assignment" }, row.latestAssignment)), () => choose({ path: row.path }), {
		className: "wt-card",
		"aria-label": `${row.name} — ${row.branch ?? "detached / bare"}`,
		"aria-pressed": selected?.path === row.path
	}))))), selected ? /* @__PURE__ */ react.createElement("section", {
		"aria-label": "Selected worktree",
		className: "wt-detail"
	}, /* @__PURE__ */ react.createElement("div", { className: "wt-title" }, /* @__PURE__ */ react.createElement("div", null, /* @__PURE__ */ react.createElement("h3", null, selectedRow?.name ?? selected.path.split(/[\\/]/).at(-1)), /* @__PURE__ */ react.createElement("p", { className: "wt-branch" }, selectedRow?.branch ?? "detached / bare")), button("Copy checkout path", async () => {
		try {
			await navigator.clipboard.writeText(selected.path);
			setCopied("Copied checkout path.");
		} catch {
			setCopied("Copy failed. Select and copy the path above.");
		}
	})), /* @__PURE__ */ react.createElement("p", { className: "wt-path" }, selected.path), /* @__PURE__ */ react.createElement("span", {
		role: "status",
		className: "wt-copy-status"
	}, copied), /* @__PURE__ */ react.createElement("div", { className: "wt-section" }, /* @__PURE__ */ react.createElement("h4", null, "Changed files", /* @__PURE__ */ react.createElement("span", { className: "wt-count" }, selected.changes.error !== void 0 ? "—" : selected.changes.count))), selected.changes.error !== void 0 ? /* @__PURE__ */ react.createElement("p", null, selected.changes.error) : /* @__PURE__ */ react.createElement(react.Fragment, null, selected.changes.count === 0 && /* @__PURE__ */ react.createElement("p", null, "No changed files."), /* @__PURE__ */ react.createElement("ul", { className: "wt-files" }, selected.changes.files.map((file, index) => /* @__PURE__ */ react.createElement("li", { key: index }, /* @__PURE__ */ react.createElement("code", null, file.status), /* @__PURE__ */ react.createElement("span", null, `${file.path}${file.from ? ` ← ${file.from}` : ""}`)))), selected.changes.truncated && /* @__PURE__ */ react.createElement("p", null, "Showing the first 500 changed files.")), /* @__PURE__ */ react.createElement("div", { className: "wt-section" }, /* @__PURE__ */ react.createElement("h4", null, `This session’s recorded runs (${selected.runs.length})`)), selected.runs.length === 0 && /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "No recorded runs for this worktree."), selected.runs.length > 0 && !selected.run && /* @__PURE__ */ react.createElement("p", null, "The selected run is no longer available. Select a retained run below."), /* @__PURE__ */ react.createElement("ol", { className: "wt-runs" }, selected.runs.map((run, index) => /* @__PURE__ */ react.createElement("li", { key: run.id }, button(/* @__PURE__ */ react.createElement(react.Fragment, null, /* @__PURE__ */ react.createElement("span", { className: "wt-muted" }, `#${selected.runs.length - index}`), /* @__PURE__ */ react.createElement("span", null, run.mode === "read-only" ? "Read-only run" : "Write run"), badge(run.status, run.status)), () => choose({
		path: selected.path,
		runId: run.id
	}), {
		className: "wt-run",
		"aria-label": `${selected.runs.length - index}. ${run.mode} · ${run.status}`,
		"aria-pressed": selected.run?.id === run.id
	})))), selected.run && /* @__PURE__ */ react.createElement("div", { className: "wt-report" }, /* @__PURE__ */ react.createElement("h4", null, "Full assignment"), /* @__PURE__ */ react.createElement("pre", null, selected.run.task), /* @__PURE__ */ react.createElement("h4", null, "Available report"), /* @__PURE__ */ react.createElement("pre", null, selected.run.report ?? "No report available."))) : /* @__PURE__ */ react.createElement("p", { className: "wt-empty" }, "Select a worktree. The previous selection may no longer be registered.")));
}

//#endregion
//#region client/capability.ts
function watchCapability({ sessions, rpc, register, interval = setInterval, clear = clearInterval, document: doc = document }) {
	let current;
	let generation = 0;
	let offTab;
	let stopped = false;
	let pending;
	const remove = () => {
		offTab?.();
		offTab = void 0;
	};
	function check() {
		const selected = Object.values(sessions.list.getSnapshot().byId).filter((session) => (session.retainedBy.mainView ?? 0) > 0);
		const id = selected.length === 1 ? selected[0].id : void 0;
		if (id !== current) {
			current = id;
			generation++;
			pending = void 0;
			remove();
		}
		if (stopped || !id || doc.visibilityState === "hidden" || pending) return;
		const token = generation;
		pending = Promise.resolve().then(() => rpc.call(CHANNEL, "capability", { sessionId: id })).then((result) => {
			if (stopped || token !== generation) return;
			const value = unwrap(result, id);
			if (value?.sessionId === id && value.state === "ready") {
				if (!offTab) offTab = register(id);
			} else remove();
		}).catch(() => {
			if (!stopped && token === generation) remove();
		}).finally(() => {
			if (token === generation) pending = void 0;
		});
	}
	const off = sessions.list.subscribe(check);
	const timer = interval(check, 1e4);
	doc.addEventListener("visibilitychange", check);
	check();
	return () => {
		stopped = true;
		generation++;
		remove();
		off();
		clear(timer);
		doc.removeEventListener("visibilitychange", check);
	};
}

//#endregion
//#region client/index.ts
var client_default = {
	name: "local-worktrees",
	inject: [
		"slots",
		"sessions",
		"connection",
		"jobs"
	],
	apply(ctx) {
		ctx.slots.inject("conversation.view", () => {
			const jobs = ctx.jobs;
			const rpc = ctx.connection.rpc;
			return watchCapability({
				sessions: ctx.sessions,
				rpc,
				register: (sessionId) => ctx.slots.register({
					name: "conversation.view",
					id: "worktrees",
					order: 20,
					label: "Worktrees",
					inject: (viewed) => ({ sessionId: viewed })
				}, (props) => props.sessionId === sessionId ? react.createElement(Panel, {
					key: sessionId,
					sessionId,
					jobs,
					rpc
				}) : null)
			});
		});
	},
	createReader,
	watchCapability,
	Panel
};

//#endregion
exports.default = client_default;
return module.exports.default; } });