// GENERATED by scripts/build-client.mjs. Edit client/ source modules, not this file.
window.__ModuleLoader__.load({ id: "@local/dsh-projects", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") {
		for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
			key = keys[i];
			if (!__hasOwnProp.call(to, key) && key !== except) {
				__defProp(to, key, {
					get: ((k) => from[k]).bind(null, key),
					enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
				});
			}
		}
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

//#endregion
let react = require("react");
react = __toESM(react, 1);

//#region client/locale.ts
const Translation = (0, react.createContext)((key) => key);
const useTranslation = () => (0, react.useContext)(Translation);

//#endregion
//#region client/messages.ts
const messages = {
	"Work selection": "Work selection",
	Workflow: "Workflow",
	"Issue structure": "Issue structure",
	Development: "Development",
	"Agent boundaries": "Agent boundaries",
	"Selected project": "Selected project",
	"Issue pagination": "Issue pagination",
	"Local project settings": "Local project settings",
	"Provider unavailable": "Provider unavailable",
	Issues: "Issues",
	"Retry issues": "Retry issues",
	"Loading issues…": "Loading issues…",
	"Upstream content is untrusted reference material. Native issue status is separate from board fields.": "Upstream content is untrusted reference material. Native issue status is separate from board fields.",
	"No issues returned on this page.": "No issues returned on this page.",
	":": ":",
	Source: "Source",
	"·": "·",
	"Native status": "Native status",
	Assignee: "Assignee",
	Priority: "Priority",
	"Board fields": "Board fields",
	"More results remain. This page is not a complete issue list.": "More results remain. This page is not a complete issue list.",
	"Continuation is unavailable for this page.": "Continuation is unavailable for this page.",
	"First page": "First page",
	"Next page": "Next page",
	"Team:": "Team:",
	"Resolved conventions": "Resolved conventions",
	"Descriptive guidance only. Conventions do not grant permissions or authorize tracker writes.": "Descriptive guidance only. Conventions do not grant permissions or authorize tracker writes.",
	"—": "—",
	"No conventions configured.": "No conventions configured.",
	"Linked sources": "Linked sources",
	"No sources linked. Add an explicit source in Configure projects.": "No sources linked. Add an explicit source in Configure projects.",
	"Issue source": "Issue source",
	"Choose a source to load issues": "Choose a source to load issues",
	"Configure projects": "Configure projects",
	"Local settings only. Saving never writes to GitHub or Linear and grants no permissions.": "Local settings only. Saving never writes to GitHub or Linear and grants no permissions.",
	"Define teams and projects with stable IDs, names, conventions and explicit sources. Linear project and team references require UUIDs. An empty convention clears an inherited value.": "Define teams and projects with stable IDs, names, conventions and explicit sources. Linear project and team references require UUIDs. An empty convention clears an inherited value.",
	"Configuration example": "Configuration example",
	"Teams and projects JSON": "Teams and projects JSON",
	"Your draft is retained. Load current settings below to compare and reconcile before retrying.": "Your draft is retained. Load current settings below to compare and reconcile before retrying.",
	"Load current settings without discarding draft": "Load current settings without discarding draft",
	"Current saved settings": "Current saved settings",
	"Compare with your draft above. Adopting this revision does not merge changes.": "Compare with your draft above. Adopting this revision does not merge changes.",
	"I reconciled my draft; use this revision": "I reconciled my draft; use this revision",
	Projects: "Projects",
	"Read-only upstream projects. Local conventions are descriptive, not permissions.": "Read-only upstream projects. Local conventions are descriptive, not permissions.",
	"Retry catalog": "Retry catalog",
	"Loading projects…": "Loading projects…",
	"Refresh catalog": "Refresh catalog",
	"GitHub provider unavailable. Load and configure the GitHub integration to read its sources.": "GitHub provider unavailable. Load and configure the GitHub integration to read its sources.",
	"Linear provider unavailable. Load and configure the Linear integration to read its sources.": "Linear provider unavailable. Load and configure the Linear integration to read its sources.",
	"No projects configured. Choose Configure projects to add local teams, projects and explicit GitHub or Linear sources.": "No projects configured. Choose Configure projects to add local teams, projects and explicit GitHub or Linear sources.",
	Project: "Project",
	"Choose a project": "Choose a project",
	"configured projects. Choose a project and source to fetch issues; other projects are not fetched.": "configured projects. Choose a project and source to fetch issues; other projects are not fetched.",
	"Not provided": "Not provided",
	"No team": "No team",
	"(Explicitly cleared)": "(Explicitly cleared)",
	"Saving local settings…": "Saving local settings…",
	"Save local settings": "Save local settings",
	"Close configuration": "Close configuration",
	"Local settings saved. No tracker writes were made.": "Local settings saved. No tracker writes were made."
};

//#endregion
//#region client/projects.tsx
function safeUrl(value) {
	try {
		const url = new URL(value ?? "");
		return url.protocol === "https:" && ["github.com", "linear.app"].includes(url.hostname) && !url.username && !url.password && !url.port ? url.href : void 0;
	} catch {
		return;
	}
}
const message = (error) => error instanceof Error ? error.message : "Projects are unavailable.";
const styles = `.local-projects{height:100%;overflow:auto;padding:24px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);box-sizing:border-box;overflow-wrap:anywhere}.local-projects *{box-sizing:border-box}.local-projects h1{font-size:24px}.local-projects h2{font-size:20px}.local-projects h3{font-size:16px}.local-projects button,.local-projects select,.local-projects textarea{font:inherit;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-3);border:1px solid var(--dsw-alias-border-l2);border-radius:6px;padding:8px;max-width:100%}.local-projects button{cursor:pointer}.local-projects button:disabled{opacity:.6;cursor:default}.local-projects :focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}.local-projects textarea{width:100%;min-height:260px;font-family:monospace}.local-projects article,.local-projects details{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:12px;margin:12px 0}.local-projects p{margin:10px 0}.local-projects small{color:var(--dsw-alias-label-secondary)}.local-projects a{color:var(--dsw-alias-label-primary);text-decoration:underline}.local-projects dl{display:grid;grid-template-columns:minmax(90px,auto) 1fr;gap:8px}.local-projects dd{margin:0;white-space:pre-wrap}.local-projects summary{cursor:pointer}.local-projects nav{display:flex;gap:8px;flex-wrap:wrap}`;
function Issues({ request, project, sourceId }) {
	const t = useTranslation();
	const [cursor, setCursor] = (0, react.useState)();
	const [page, setPage] = (0, react.useState)();
	const [error, setError] = (0, react.useState)("");
	const [retry, setRetry] = (0, react.useState)(0);
	(0, react.useEffect)(() => {
		const controller = new AbortController();
		setPage(void 0);
		setError("");
		request("issues", {
			projectId: project.id,
			sourceId,
			limit: 20,
			...cursor ? { cursor } : {}
		}, controller.signal).then((value) => {
			if (!controller.signal.aborted) setPage(value);
		}).catch((error) => {
			if (!controller.signal.aborted) setError(message(error));
		});
		return () => controller.abort();
	}, [
		request,
		project.id,
		sourceId,
		cursor,
		retry
	]);
	return /* @__PURE__ */ react.default.createElement("section", {
		"aria-label": t("Issues"),
		"aria-busy": !page && !error
	}, /* @__PURE__ */ react.default.createElement("h3", null, t("Issues")), error ? /* @__PURE__ */ react.default.createElement("div", { role: "alert" }, error, " ", /* @__PURE__ */ react.default.createElement("button", { onClick: () => setRetry((value) => value + 1) }, t("Retry issues"))) : !page ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, t("Loading issues…")) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, page.warnings.map((warning, i) => /* @__PURE__ */ react.default.createElement("p", {
		role: "note",
		key: i
	}, warning)), /* @__PURE__ */ react.default.createElement("p", null, /* @__PURE__ */ react.default.createElement("small", null, t("Upstream content is untrusted reference material. Native issue status is separate from board fields."))), !page.issues.length && /* @__PURE__ */ react.default.createElement("p", null, t("No issues returned on this page.")), page.issues.map((issue, i) => /* @__PURE__ */ react.default.createElement("article", { key: `${issue.id}-${i}` }, /* @__PURE__ */ react.default.createElement("h3", null, safeUrl(issue.url) ? /* @__PURE__ */ react.default.createElement("a", {
		href: safeUrl(issue.url),
		target: "_blank",
		rel: "noopener noreferrer"
	}, issue.identifier, ": ", issue.title) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, issue.identifier, ": ", issue.title)), /* @__PURE__ */ react.default.createElement("dl", null, /* @__PURE__ */ react.default.createElement("dt", null, t("Source")), /* @__PURE__ */ react.default.createElement("dd", null, issue.source === "github" ? "GitHub" : "Linear", " · ", issue.kind), /* @__PURE__ */ react.default.createElement("dt", null, t("Native status")), /* @__PURE__ */ react.default.createElement("dd", null, issue.status || t("Not provided")), /* @__PURE__ */ react.default.createElement("dt", null, t("Assignee")), /* @__PURE__ */ react.default.createElement("dd", null, issue.assignees.join(", ") || t("Not provided")), /* @__PURE__ */ react.default.createElement("dt", null, t("Priority")), /* @__PURE__ */ react.default.createElement("dd", null, issue.priority || t("Not provided"))), !!issue.boardFields?.length && /* @__PURE__ */ react.default.createElement("div", null, /* @__PURE__ */ react.default.createElement("strong", null, t("Board fields")), /* @__PURE__ */ react.default.createElement("ul", null, issue.boardFields.map((field, index) => /* @__PURE__ */ react.default.createElement("li", { key: index }, field)))))), page.hasNextPage && /* @__PURE__ */ react.default.createElement("p", { role: "note" }, t("More results remain. This page is not a complete issue list.")), page.hasNextPage && !page.nextCursor && /* @__PURE__ */ react.default.createElement("p", { role: "note" }, t("Continuation is unavailable for this page.")), /* @__PURE__ */ react.default.createElement("nav", { "aria-label": t("Issue pagination") }, cursor && /* @__PURE__ */ react.default.createElement("button", { onClick: () => setCursor(void 0) }, t("First page")), page.hasNextPage && page.nextCursor && /* @__PURE__ */ react.default.createElement("button", { onClick: () => setCursor(page.nextCursor) }, t("Next page")))));
}
function Project({ project, catalog, request }) {
	const t = useTranslation();
	const [sourceId, setSourceId] = (0, react.useState)("");
	return /* @__PURE__ */ react.default.createElement("section", { "aria-label": t("Selected project") }, /* @__PURE__ */ react.default.createElement("h2", null, project.name), /* @__PURE__ */ react.default.createElement("p", null, project.description), /* @__PURE__ */ react.default.createElement("p", null, t("Team:"), " ", project.teamName || t("No team")), /* @__PURE__ */ react.default.createElement("details", null, /* @__PURE__ */ react.default.createElement("summary", null, t("Resolved conventions")), /* @__PURE__ */ react.default.createElement("p", null, t("Descriptive guidance only. Conventions do not grant permissions or authorize tracker writes.")), Object.keys(project.effectiveConventions).length ? /* @__PURE__ */ react.default.createElement("dl", null, Object.entries(project.effectiveConventions).map(([key, value]) => /* @__PURE__ */ react.default.createElement(react.default.Fragment, { key }, /* @__PURE__ */ react.default.createElement("dt", null, t({
		workSelection: "Work selection",
		workflow: "Workflow",
		issueStructure: "Issue structure",
		development: "Development",
		agentBoundaries: "Agent boundaries"
	}[key] ?? key)), /* @__PURE__ */ react.default.createElement("dd", null, value || t("(Explicitly cleared)"), " ", /* @__PURE__ */ react.default.createElement("small", null, t("—"), " ", project.conventionOrigins[key] === "team" ? `${t("Team:")} ${project.teamName ?? project.teamId}` : t("Project")))))) : /* @__PURE__ */ react.default.createElement("p", null, t("No conventions configured."))), /* @__PURE__ */ react.default.createElement("h3", null, t("Linked sources")), !project.sources.length ? /* @__PURE__ */ react.default.createElement("p", null, t("No sources linked. Add an explicit source in Configure projects.")) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("label", null, t("Issue source"), " ", /* @__PURE__ */ react.default.createElement("select", {
		value: sourceId,
		onChange: (event) => setSourceId(event.target.value)
	}, /* @__PURE__ */ react.default.createElement("option", { value: "" }, t("Choose a source to load issues")), project.sources.map((source) => /* @__PURE__ */ react.default.createElement("option", {
		key: source.id,
		value: source.id
	}, source.id, " · ", source.kind)))), /* @__PURE__ */ react.default.createElement("ul", null, project.sources.map((source) => /* @__PURE__ */ react.default.createElement("li", { key: source.id }, source.id, ": ", source.kind, t("—"), " ", "owner" in source ? `${source.owner}/${"repo" in source ? source.repo : `project ${source.projectNumber}`}` : "project" in source ? source.project : source.team, !(source.kind.startsWith("github") ? catalog.providers.github : catalog.providers.linear) && ` — ${t("Provider unavailable")}`))), sourceId && /* @__PURE__ */ react.default.createElement(Issues, {
		key: sourceId,
		request,
		project,
		sourceId
	})));
}
function Editor({ catalog, request, saved, onBusy }) {
	const t = useTranslation();
	const [draft, setDraft] = (0, react.useState)(() => JSON.stringify(catalog.configuration, null, 2));
	const [error, setError] = (0, react.useState)("");
	const [busy, setBusy] = (0, react.useState)(false);
	const [revision, setRevision] = (0, react.useState)(catalog.revision);
	const [latest, setLatest] = (0, react.useState)();
	const controller = (0, react.useRef)();
	(0, react.useEffect)(() => () => controller.current?.abort(), []);
	async function save() {
		setError("");
		try {
			const value = JSON.parse(draft);
			if (!value || typeof value !== "object" || !("teams" in value) || !Array.isArray(value.teams) || !("projects" in value) || !Array.isArray(value.projects)) throw new Error("Enter an object with teams and projects arrays.");
			const configuration = value;
			controller.current = new AbortController();
			setBusy(true);
			onBusy(true);
			const result = await request("configure", {
				configuration,
				expectedRevision: revision
			}, controller.current.signal);
			if (!controller.current.signal.aborted) saved(result);
		} catch (error) {
			if (!controller.current?.signal.aborted) setError(message(error));
		} finally {
			if (!controller.current?.signal.aborted) {
				setBusy(false);
				onBusy(false);
			}
		}
	}
	return /* @__PURE__ */ react.default.createElement("section", { "aria-label": t("Local project settings") }, /* @__PURE__ */ react.default.createElement("h2", null, t("Configure projects")), /* @__PURE__ */ react.default.createElement("p", null, t("Local settings only. Saving never writes to GitHub or Linear and grants no permissions.")), /* @__PURE__ */ react.default.createElement("p", null, t("Define teams and projects with stable IDs, names, conventions and explicit sources. Linear project and team references require UUIDs. An empty convention clears an inherited value.")), /* @__PURE__ */ react.default.createElement("details", null, /* @__PURE__ */ react.default.createElement("summary", null, t("Configuration example")), /* @__PURE__ */ react.default.createElement("pre", { style: { whiteSpace: "pre-wrap" } }, JSON.stringify({
		teams: [{
			id: "team",
			name: "Team",
			conventions: { workflow: "Review before merging" }
		}],
		projects: [{
			id: "example",
			name: "Example",
			teamId: "team",
			conventions: {},
			sources: [{
				id: "repo",
				kind: "github-repository",
				owner: "OWNER",
				repo: "REPO"
			}]
		}]
	}, null, 2))), /* @__PURE__ */ react.default.createElement("label", null, t("Teams and projects JSON"), /* @__PURE__ */ react.default.createElement("textarea", {
		value: draft,
		disabled: busy,
		onChange: (event) => setDraft(event.target.value),
		spellCheck: false
	})), error && /* @__PURE__ */ react.default.createElement("p", { role: "alert" }, error, " ", t("Your draft is retained. Load current settings below to compare and reconcile before retrying.")), error && /* @__PURE__ */ react.default.createElement("button", {
		disabled: busy,
		onClick: async () => {
			controller.current = new AbortController();
			setBusy(true);
			onBusy(true);
			try {
				const value = await request("catalog", {}, controller.current.signal);
				if (!controller.current.signal.aborted) setLatest(value);
			} catch (error) {
				if (!controller.current.signal.aborted) setError(message(error));
			} finally {
				if (!controller.current.signal.aborted) {
					setBusy(false);
					onBusy(false);
				}
			}
		}
	}, t("Load current settings without discarding draft")), latest && /* @__PURE__ */ react.default.createElement("div", null, /* @__PURE__ */ react.default.createElement("h3", null, t("Current saved settings")), /* @__PURE__ */ react.default.createElement("pre", { style: { whiteSpace: "pre-wrap" } }, JSON.stringify(latest.configuration, null, 2)), /* @__PURE__ */ react.default.createElement("p", null, t("Compare with your draft above. Adopting this revision does not merge changes.")), /* @__PURE__ */ react.default.createElement("button", {
		disabled: busy,
		onClick: () => {
			setRevision(latest.revision);
			setLatest(void 0);
			setError("");
		}
	}, t("I reconciled my draft; use this revision"))), /* @__PURE__ */ react.default.createElement("button", {
		disabled: busy,
		onClick: () => void save()
	}, busy ? t("Saving local settings…") : t("Save local settings")));
}
function Projects({ request }) {
	const t = useTranslation();
	const [catalog, setCatalog] = (0, react.useState)();
	const [error, setError] = (0, react.useState)("");
	const [refresh, setRefresh] = (0, react.useState)(0);
	const [selected, setSelected] = (0, react.useState)("");
	const [editing, setEditing] = (0, react.useState)(false);
	const [saving, setSaving] = (0, react.useState)(false);
	const [notice, setNotice] = (0, react.useState)("");
	(0, react.useEffect)(() => {
		const controller = new AbortController();
		setError("");
		setCatalog(void 0);
		request("catalog", {}, controller.signal).then((value) => {
			if (!controller.signal.aborted) setCatalog(value);
		}).catch((error) => {
			if (!controller.signal.aborted) setError(message(error));
		});
		return () => controller.abort();
	}, [request, refresh]);
	const project = catalog?.projects.find((project) => project.id === selected);
	return /* @__PURE__ */ react.default.createElement("section", {
		className: "local-projects",
		"aria-label": t("Projects")
	}, /* @__PURE__ */ react.default.createElement("style", null, styles), /* @__PURE__ */ react.default.createElement("h1", null, t("Projects")), /* @__PURE__ */ react.default.createElement("p", null, t("Read-only upstream projects. Local conventions are descriptive, not permissions.")), notice && /* @__PURE__ */ react.default.createElement("p", { role: "status" }, notice), error ? /* @__PURE__ */ react.default.createElement("div", { role: "alert" }, error, " ", /* @__PURE__ */ react.default.createElement("button", { onClick: () => setRefresh((value) => value + 1) }, t("Retry catalog"))) : !catalog ? /* @__PURE__ */ react.default.createElement("p", { role: "status" }, t("Loading projects…")) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("nav", null, /* @__PURE__ */ react.default.createElement("button", {
		disabled: saving,
		onClick: () => setEditing((value) => !value)
	}, editing ? t("Close configuration") : t("Configure projects")), /* @__PURE__ */ react.default.createElement("button", {
		disabled: editing,
		onClick: () => setRefresh((value) => value + 1)
	}, t("Refresh catalog"))), !catalog.providers.github && /* @__PURE__ */ react.default.createElement("p", { role: "note" }, t("GitHub provider unavailable. Load and configure the GitHub integration to read its sources.")), !catalog.providers.linear && /* @__PURE__ */ react.default.createElement("p", { role: "note" }, t("Linear provider unavailable. Load and configure the Linear integration to read its sources.")), editing ? /* @__PURE__ */ react.default.createElement(Editor, {
		catalog,
		request,
		onBusy: setSaving,
		saved: (value) => {
			setCatalog(value);
			setEditing(false);
			setSelected("");
			setNotice(t("Local settings saved. No tracker writes were made."));
		}
	}) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, !catalog.projects.length ? /* @__PURE__ */ react.default.createElement("p", null, t("No projects configured. Choose Configure projects to add local teams, projects and explicit GitHub or Linear sources.")) : /* @__PURE__ */ react.default.createElement(react.default.Fragment, null, /* @__PURE__ */ react.default.createElement("label", null, t("Project"), " ", /* @__PURE__ */ react.default.createElement("select", {
		value: selected,
		onChange: (event) => setSelected(event.target.value)
	}, /* @__PURE__ */ react.default.createElement("option", { value: "" }, t("Choose a project")), catalog.projects.map((project) => /* @__PURE__ */ react.default.createElement("option", {
		key: project.id,
		value: project.id
	}, project.name)))), /* @__PURE__ */ react.default.createElement("p", null, catalog.projects.length.toLocaleString(), " ", t("configured projects. Choose a project and source to fetch issues; other projects are not fetched.")), project && /* @__PURE__ */ react.default.createElement(Project, {
		key: `${catalog.revision}-${project.id}`,
		project,
		catalog,
		request
	})))));
}

//#endregion
//#region client/registration.tsx
function Icon({ size, active }) {
	return /* @__PURE__ */ react.default.createElement("svg", {
		width: size,
		height: size,
		viewBox: "0 0 24 24",
		fill: "none",
		stroke: "currentColor",
		strokeWidth: active ? 2 : 1.5,
		"aria-hidden": "true"
	}, /* @__PURE__ */ react.default.createElement("path", { d: "M3 7h7l2-3h9v16H3z" }));
}
function apply(ctx) {
	ctx.effect(() => ctx.locale.register("local-projects", "en", messages));
	const translate = ctx.locale.bind("local-projects");
	const subscribe = (listener) => ctx.locale.subscribe(listener);
	const snapshot = () => ctx.locale.getSnapshot();
	function Panel() {
		const locale = (0, react.useSyncExternalStore)(subscribe, snapshot);
		const t = react.default.useCallback((key) => translate(key), [locale]);
		return /* @__PURE__ */ react.default.createElement(Translation.Provider, { value: t }, /* @__PURE__ */ react.default.createElement(Projects, { request }));
	}
	const request = async (endpoint, input, signal) => {
		const result = await ctx.connection.rpc.call("/projects", endpoint, input, signal);
		if (!result.ok) throw new Error(result.error.message);
		return result.value;
	};
	ctx.slots.inject("sidebar.panellist", () => ctx.slots.register({
		name: "sidebar.panellist",
		id: "local-projects",
		label: () => translate("Projects"),
		order: 10
	}, Icon));
	ctx.slots.inject("main", () => ctx.slots.register({
		name: "main",
		key: "local-projects"
	}, Panel));
}
var registration_default = {
	inject: [
		"slots",
		"connection",
		"locale"
	],
	apply
};

//#endregion
exports.default = registration_default;
return module.exports.default; } });